### ISSUE TITLE
Update references to Waffle.io with zenhub on Zowe.org

### ISSUE THREAD

**Issue by alvin-tan** [zowe/community#101]
https://zowe.org/contribute/

![image.png](https://images.zenhubusercontent.com/5cc07ad0b42cd5232a817044/53d56fd2-3318-42d0-8a11-36bcaf689620)

**Comment by Tbr00ksy** [comment]
Need to update the community readme (https://github.com/zowe/community/blob/master/README.md) with links to the zenhub boards. Also would be good to add the call out to the committers.md (https://github.com/zowe/community/blob/master/COMMITTERS.md) for the org structure section.
