### ISSUE TITLE
Need to consolidate on a Single scan and commit to resolving issues found by that scan for each release of Zowe

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#1034]
We have many security scans that run but no commitment to act on the results as a single community.
Since we run GIthub dependency checker maybe that would be the best one.

Currently available and at least somewhat run scanners:
- BlackDuck
- Snyk
- GitHub dependency Checker

Tasks:
- [ ] Propose which tool/s we will commit
- [ ] Propose the commitment with respect to how fast we fix the found bugs.

**Comment by balhar-jakub** [comment]
What tool we will consolidate?

**Comment by balhar-jakub** [comment]
Dependency Checker
OWASP

Snyk.io

**Comment by balhar-jakub** [comment]
The achieved consensus was that we will figure out what tools are currently used and limit us to one or two that the Zowe will depend on and will fix the bugs from them as priority. 

As for the process of actually fixing the bugs and how it will fit into the release we didn't actually reach any conclusion.

**Comment by balhar-jakub** [comment]
Part of the question is what commitments we as a Zowe make towards fixing the issues found via the security scanning?

To be discussed whether and how we will fit such a solution to the release process.

**Comment by balhar-jakub** [comment]
Start with the Github Dependency Checker as the first tool to focus on.

**Comment by balhar-jakub** [comment]
This is somehow linked issue from before: https://docs.zowe.org/stable/getting-started/summaryofchanges.html

**Comment by balhar-jakub** [comment]
Polaris
Veracode

**Comment by balhar-jakub** [comment]
Addressing the security issues in the open-source dependencies. 
GitHub dependency creating a PR to update the dependency

Every three weeks the squad should look for the issues from GitHub dependencies. 

BlackDuck - could be run on RC and helping us to understand the issue. The Rocket can publish the BlackDuck reports. 

Would it be possible to use the weekly build of the Zowe to test the security?
  - It seems that this could be used.

**Comment by balhar-jakub** [comment]
Presentation covering options and current status together with recommendation.  

[https://app.zenhub.com/files/145870120/ef2bec66-f59e-4874-a725-138a85144ef2/download](https://app.zenhub.com/files/145870120/ef2bec66-f59e-4874-a725-138a85144ef2/download)

**Comment by balhar-jakub** [comment]
The current state is that we accept multiple resources for scanning. 
As for the dependency scan at the moment the main source of truth are BlackDuck scans provided by the API ML squad.

**Comment by balhar-jakub** [comment]
I am closing this as in general the usage of BlackDuck is well established and reaching towards the daily scans of the Zowe.
