### ISSUE TITLE
Expedite the Zowe Explorer Conformance Program / Deliver something this PI

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1049]
Issue:  

- Zowe Explorer as "core" Zowe component has no conformance program
- Many VS Code Extensions  are in-progress and may be at risk of "non-conformance"
- This situation may result in many undesirable outcomes including:

  - Inconsistent behavior / User Experience
  - Inability to leverage "common" code (i.e .Profile Management)
  - high probability of technical debt / rework required to earn "conformance"
  - extenders unable / unwilling to desire the Zowe badge
  - Ultimately, USERS lacking confidence in uniting these technologies

Suggestion:  Tap the Zowe Community for Volunteers to draft Zowe Explorer Conformance Criteria and publish the first "phase" of Zowe Conformance for Zowe Explorer Extenders before the end of this PI.

**Comment by balhar-jakub** [comment]
@dkelosky @zFernand0 Could you please make sure that the draft will be visible here?

**Comment by dkelosky** [comment]
@jellypuno

**Comment by jellypuno** [comment]
@dkelosky @zFernand0 @phaumer @zdmullen @crawr
I created a list on what I think should be added in the ZE conformance criteria. Please let me know what you think.

**Infrastructure**
1. Extensions should be built on Zowe Node.js SDK
2. Extensions that would like to extend Zowe Explorer context menu should adhere to the contextual string format that the Zowe explorer provides
```
		"menus": {
			"view/item/context": [
				{
                                    "when": "view == zowe.uss.explorer && viewItem =~ /^binaryFile.*/",
                                    "command": "zowe.uss.text",
                                    "group": "2_systemSpecific@2"
                                },
            ],
        ..
        ..
   }
```

3. Extensions that would like to use Zowe Explorer APIs should register their extension and use `ZoweExplorerApi` interfaces.
4. Extensions that wishes to have a dependency on Zowe Explorer should specify the extension dependency in their package.json
```
    "extensionDependencies": [
		"zowe.vscode-extension-for-zowe"
	],
```
5. Extensions that wishes to have a dependency on Zowe Explorer should use `vscode.extensions.getExtension('zowe.vscode-extension-for-zowe');` to gain access to Zowe Explorer APIs
``` shell
export function activate(context: vscode.ExtensionContext) {
    const EXTENDER_API;
    const baseExt = vscode.extensions.getExtension('zowe.vscode-extension-for-zowe');
    try {
        if (baseExt && baseExt.exports) {
            EXTENDER_API = baseExt.exports.getExplorerExtenderApi();
            return;
        }
    } catch (error) {
        vscode.window.showWarningMessage("Unable to access Zowe Explorer API");
    }
}
```

**Profiles**

6. Extensions should share a profile with Zowe CLI (includes team configuration file and yaml files)
7. Extensions should support Base profiles and Tokens
8. Extensions should support Secure Credential Store
9. Extensions who wishes to acquire profile information from Zowe Explorer should use the `ZoweExplorerApi.IApiExplorerExtender` interface

**Support**
10. Submitter describes how Support is provided and Support details are clearly documented


References: 
- https://github.com/zowe/vscode-extension-for-zowe/issues/837 
- https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Extending.md

**Comment by jellypuno** [comment]
I am not sure if this is valid but I would like extensions that extends Zowe Explorer APIs should have their own error message tag.

**Comment by Joe-Winchester** [comment]
@jellypuno - many thanks for starting to put this together.  

 1. Extension for menus

If an extension adds a menu pop-up against an item in one of the 3 Zowe Explorer trees, should there be some enforcement of how that behaves ?  In IDEs like Eclipse I used to see menu actions that plugins provided that didn't respect things like disable/enable or a consistent way of providing error feedback.   Some would write errors to files, some to the console, some to the UI, ...  

2. Data providers

The rse profile is able to provide a back end for data in the 3 UIs that is useful for customers who don't, or can't, use z/OSMF as their REST endpoint.  FTP also is available although with less function (minus jobs). Can the conformance program cover the extension points by which this occurs to ensure there is a consistent user experience and also backwards compatibility between others who might want to provide back end services.  

3. Profiles

Not all Zowe Explorer extensions will use CLI profiles.  For example, there may be an existing VS Code extension that wishes to operate outside of Zowe Explorer (i.e. not a pre-req) that has its own endpoint/auth mechanism but provide value if Zowe Explorer is co-installed in the same shell.  In that case it shouldn't fail conformance as sharing profiles is a usability feature, however there should be a defined API where the extension can detect the presence of Zowe profiles, query them, and use them in their UI.  Should there also be a conformant enforced way to make sure the other extension tool writes profile data back if their UI chose to ?

4. Distribution

Currently there are many extensions in the VS Code marketplace that have tagged Zowe, so you can see them when you filter for Zowe.  It'd be good if there was a way for a user to know which of these have a conformance badge, so a Zowe Explorer Conformant extension could be asked to display the conformance badge on their marketplace home page.

**Comment by dkelosky** [comment]
> Data providers
The rse profile is able to provide a back end for data in the 3 UIs that is useful for customers who don't, or can't, use z/OSMF as their REST endpoint. FTP also is available although with less function (minus jobs). Can the conformance program cover the extension points by which this occurs to ensure there is a consistent user experience and also backwards compatibility between others who might want to provide back end services.

Yes - conformance should cover these.

> Extensions should be built on Zowe Node.js SDK
...
Extensions should share a profile with Zowe CLI (includes team configuration file and yaml files)
Extensions should support Base profiles and Tokens
Extensions should support Secure Credential Store

Instead of `should` perhaps `must`.  

> Not all Zowe Explorer extensions will use CLI profiles. For example, there may be an existing VS Code extension that wishes to operate outside of Zowe Explorer (i.e. not a pre-req) that has its own endpoint/auth mechanism but provide value if Zowe Explorer is co-installed in the same shell. In that case it shouldn't fail conformance as sharing profiles is a usability feature, however there should be a defined API where the extension can detect the presence of Zowe profiles, query them, and use them in their UI. Should there also be a conformant enforced way to make sure the other extension tool writes profile data back if their UI chose to ?

@Joe-Winchester If it has its own endpoint/auth mechanism - where would that configuration be stored?   Do you have an extension in mind here?

**Comment by jellypuno** [comment]
> 1. Extension for menus
> 
> If an extension adds a menu pop-up against an item in one of the 3 Zowe Explorer trees, should there be some enforcement of how that behaves ? In IDEs like Eclipse I used to see menu actions that plugins provided that didn't respect things like disable/enable or a consistent way of providing error feedback. Some would write errors to files, some to the console, some to the UI, ...

@Joe-Winchester Regarding the menus: I agree. We do need more documentation about this. Especially about the groupings of the menu items. I will think about this more.

Regarding Error Messages: I'm thinking of the same thing. I think we should have an enforced rule about error messaging. One of the solution that I have in mind is an Error Message IDs (e.g. IEF237I) similar to mainframe. This message ID will be added in errors that are pop-out in the extension, added in logs or outputs. What do you think?


> 1. Profiles
> 
> Not all Zowe Explorer extensions will use CLI profiles. For example, there may be an existing VS Code extension that wishes to operate outside of Zowe Explorer (i.e. not a pre-req) that has its own endpoint/auth mechanism but provide value if Zowe Explorer is co-installed in the same shell. In that case it shouldn't fail conformance as sharing profiles is a usability feature, however there should be a defined API where the extension can detect the presence of Zowe profiles, query them, and use them in their UI. Should there also be a conformant enforced way to make sure the other extension tool writes profile data back if their UI chose to ?

ZE has an API point `ZoweExplorerApi.IApiExplorerExtender` . This allows extenders to get a Profile Information that is available in the tree  and reload Profile list in the tree as well.

> 
> 1. Distribution
> 
> Currently there are many extensions in the VS Code marketplace that have tagged Zowe, so you can see them when you filter for Zowe. It'd be good if there was a way for a user to know which of these have a conformance badge, so a Zowe Explorer Conformant extension could be asked to display the conformance badge on their marketplace home page.

I agree. We could also create a small badge like the picture below and link it here: https://www.openmainframeproject.org/projects/zowe/conformance
![image](https://user-images.githubusercontent.com/45042840/110103118-da459080-7da5-11eb-909f-98c9055e245b.png)

**Comment by Joe-Winchester** [comment]
@dkelosky 

>..@Joe-Winchester If it has its own endpoint/auth mechanism - where would that configuration be stored? Do you have an extension in mind here?

The scenario could work for Db2 Developer for z/OS.  This can be loaded independently of Zowe Explorer and a user can add connection details that their extension persists.  If however a user has Zowe CLI present, is there a way the Db2 extension can detect that and in their `Add Connection` UI have an API to query the Zowe profile, see which ones are type `base` or `zosmf` as it's likely that the host name might be shared and if there are type `db2` then these can provide a Db2 connection port and location.  

The user problem to tackle is that they should be able to define connection details for a Db2 connection once and have that shared between tools, without a hard pre-req between those tools.  Perhaps there is an SDK way to do this so that the profile information is able to be used by other VS Code extensions without bringing in all of Zowe Explorer UI if they wish to just use profiles, and rather than each provider writing their own connection management that's provided as an SDK complete with user interface.  

![image](https://user-images.githubusercontent.com/28100302/110116202-10d3d900-7daf-11eb-9f75-bf0348374e59.png)

**Comment by dkelosky** [comment]
@Joe-Winchester Zowe CLI /Zowe Explorer are built on the Zowe Node SDK which has (and will have more) programmatic APIs to load profile information.  Other VS Code extensions could be built this way as well and have no technical prereq for Zowe Explorer itself. 

For example, the JCLCheck and Endevor VS Code extensions behave this way.  They're built on top of Zowe Node SDK infrastructure (they also connect to Zowe conformant APIs).  

Db2 Developer for z/OS seems to have no association to any component of Zowe in it's current form.

**Comment by Joe-Winchester** [comment]
>..Db2 Developer for z/OS seems to have no association to any component of Zowe in it's current form.

Maybe a sample is needed for an extension has no pre-req can operate stand-alone but wants value to work co-hosted with Zowe Explorer.  From Kendrick's demo last week I saw he had a pop-up "Run as SQL" against a Zowe Explorer database member so that's an example of side by side user added value without a hard pre-req against Zowe Explorer.

**Comment by dkelosky** [comment]
> From Kendrick's demo last week I saw he had a pop-up "Run as SQL" against a Zowe Explorer database member so that's an example of side by side user added value without a hard pre-req against Zowe Explorer.

That's great!  Do you know how they're doing that?  For example, is it using Zowe Explorer APIs (which would be direct integration)?  Or, are they using VS Code capabilities?  

For example, if I had a C language formatter that operates on C source files opened in VS Code, and I opened C source in a mainframe data set via Zowe Explorer and formatted it -> would that make this extension a Zowe conformant one?

**Comment by phaumer** [comment]
@dkelosky in VS Code any extension can access any open document, determine cursor location etc as well as define new commands. See @jellypuno's example above for defining an action with context, e.g. one could add a new context menu for a specific language etc. Conformance should only come into play when it is about reusing or augmenting specific capabilities the base extension offers that goes beyond VS Code APIs.

**Comment by phaumer** [comment]
We are tracking the conformance work in this item: https://github.com/zowe/vscode-extension-for-zowe/issues/837

So far the main focus was on Number (2) in @Joe-Winchester's list, which maps to points (3 to 5) in @jellypuno's list. I think those could be accelerated. I know of two VS Code extensions that use these: Zowe Explorer FTP and Z Open Editor. Are there any others? 

For the other points I would like to discuss a bit more as several of these should be extracted from Zowe Explorer as reusable APIs as well or some could perhaps even be handled by CLI/Imperative, such as a reusable Profiles cache that make using secure credentials automatic for extenders if the base uses it.

**Comment by dkelosky** [comment]
> @dkelosky in VS Code any extension can access any open document, determine cursor location etc as well as define new commands.

thanks - do you think any extension that has this level of integration would be conformant?  it seems like a broad range of extensions would meet conformance criteria if so.  would this make sense?

**Comment by jellypuno** [comment]
## Updated Version 

Github Discussion: https://github.com/zowe/vscode-extension-for-zowe/discussions/1269
Excel Sheet: https://ent.box.com/s/hqzfsia30z09hsjo8gj40kunhjaw9ebj

**Comment by phaumer** [comment]
Next version evolves here: <https://github.com/zowe/vscode-extension-for-zowe/pull/1290>

**Comment by balhar-jakub** [comment]
As the program is underway, I am closing the issue.
