### ISSUE TITLE
Figure out the process for shared slide decks and templates. 

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1052]
**Is your feature request related to a problem or limitation? Please describe.**
To help presenters with the presentation about Zowe and to have at least some level of consistency. We should figure out the right way to keep the templates, update them and share them with those who need them. 

There is already a PR linked to this attempt here: https://github.com/zowe/community/pull/704

**Comment by Joe-Winchester** [comment]
There was an update to the Zowe overview on zowe.org recently and the presentation used for that is here:
[https://github.com/zowe/community/tree/master/videos/Zowe%20Overview](https://github.com/zowe/community/tree/master/videos/Zowe%20Overview)

One problem I've found is that there is a git commit limit of 100M and .mp4 files tend to be larger.  I've tried to use gitlfs but not manage successfully to find a way to upload large videos to the repo.

**Comment by balhar-jakub** [comment]
May be an issue as there are different requirements and different audiences. 

There is an OMP related template somewhere within GitHub.

**Comment by balhar-jakub** [comment]
Maybe a way to share the existing presentation, dumping ground for the presentations where possible.
