### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1053]
The ultimate goal is to provide configuration and setup that would be highly available.

In the context of one LPAR, this means that the Zowe services will be redundant and if one is killed then either there is at least another running instance or that there is a hot backup for the service that is used instead of the original instance. 

In the context of multiple LPARs within Sysplex this means that even if one of the LPARs went down the Zowe services will still remain accessible for the users.

**Comment by jackjia-ibm** [comment]
@balhar-jakub we can discuss the status in next TSC meeting. Here is the [Zowe_HA_Status_202103.pptx](https://github.com/zowe/community/files/6167339/Zowe_HA_Status_202103.pptx).

@1000TurquoisePogs @Joe-Winchester please feel free to update if I missed anything. Thanks.

**Comment by balhar-jakub** [comment]
Released and supported
