### ISSUE TITLE
CLI ZOS-FILES command should support GDGs

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#1058]
**Is your feature request related to a problem or limitation? Please describe.**
ZOS-FILES doesn't support GDG-s

**Describe the experience you'd like**
Add GDG related operations:
create, delete
add/replace generation - upload a file, roll-in a seq ds, roll-in a PDS member, etc
download a generation eg: 0 - latest, -10 - tenth

**Describe alternatives you've considered**

**Additional context**

**Comment by balhar-jakub** [comment]
@MikeBauerCA This looks like CLI related?

**Comment by MikeBauerCA** [comment]
Yes, it was also opened in the zowe-cli repo -> https://github.com/zowe/zowe-cli/issues/969
