### ISSUE TITLE
Authentication error zss

### ISSUE THREAD

**Issue by folkon84** [zowe/community#1065]
Thank you for taking the time to submit a blog post proposal.

Please reference [Zowe Blog Guidelines](https://github.com/zowe/community/blob/master/blogging/blog_guidelines.md).

**Blog category**

Zowe blogs are categorized to allow readers to distinguish content that discusses software that is available in Zowe core together with other technology available under permissive open source licenses by being flagged as `{Core}`.  Blogs that describe commercial offerings available under vendor licenses are permitted but are flagged as `{Ecosystem}` and the commercial offering should be Zowe conformant.  Projects that are under Zowe incubation are flagged `{Incubation}` to indicate the solution being discussed isn't part of a Zowe Long Term Support (LTS) release

What kind of blog are you proposing ?

- [ ] Zowe Core  
- [ ] Zowe Ecosystem  
- [ ] Zowe Incubation

If your blog falls out of one of these categories please submit it anyway and the editorial team will let you know if it is an article that is likely to be accepted.

**Comment by balhar-jakub** [comment]
@folkon84 Any reason why you created this as a blog post?

**Comment by folkon84** [comment]
STDOUT: 
ZWES1013I ZSS Server has started. Version '1.19.0+20210106'
 ZWES1033I Using server config file '/global/zowe/workspace/app-server/serverConfig/server.json'
 ZWES1035I ZSS Server settings: Address='127.0.0.1', port='8542'
 ZWES1036W Server startup problem: Ret='0', res='0x0'

> @folkon84 Any reason why you created this as a blog post?

No, this problem was not found

**Comment by balhar-jakub** [comment]
@1000TurquoisePogs This looks like a topic to move to the zlux repository.

**Comment by folkon84** [comment]
Problem solved by running ICSF Address Space (S CSF)
