### ISSUE TITLE
Categorize Zowe blogs per component

### ISSUE THREAD

**Issue by nannanli** [zowe/community#1082]
Currently, Zowe Medium blogs are listed into the following categories: 
- Zowe Core  
- Zowe Ecosystem  
- Zowe Incubation

It would be helpful to find a way to organize blogs per component, for example, a CLI user can find all blogs talking about Zowe CLI. We can also associate the blogs with component introduction on zowe.org then.

**Comment by jmertic** [comment]
@Maemalynn ^

**Comment by Joe-Winchester** [comment]
The current site has the header area
![image](https://user-images.githubusercontent.com/28100302/119373051-e871c180-bcaf-11eb-87f7-431fc6785514.png)
This isn't currently used consistently (and the tabs point to out of date articles).
I was able to edit the layout to add in the categories @nannanli mentioned above
![image](https://user-images.githubusercontent.com/28100302/119374189-32a77280-bcb1-11eb-8154-75836311f678.png)
For articles you can add a tag of `ZoweCore`, `ZoweEcosystem`, or `ZoweIncubator` and the tabs take you to the articles that have been flagged up.
If this looks good I can start to go and re-tag all of the existing content, we prob have around 40 or so articles to go through and tag, each one takes about 20 seconds to do.

**Comment by balhar-jakub** [comment]
@Joe-Winchester This looks better to me than the previous one.

**Comment by MikeBauerCA** [comment]
It would also be nice to have all blogs related to the security of Zowe in a single location as well.

**Comment by balhar-jakub** [comment]
It's linked to this effort: https://github.com/zowe/docs-site/issues/3209

**Comment by RASakach** [comment]
Some thoughts from the 4/19 Onboarding Meeting:

1. The categories are inconsistent (some use ZOWE, others do not"
2. The reference to INCUBATION is not accurate, incubation is a Squad designation, not a software designation.  Should use UNDER DEVELOPMENT or TECH PREVIEW or another term that covers both
3. Some blogs are old and outdated - should we perform a review and remove those that may lead the reader down an inaccurate (for present day) path?

**Comment by jmertic** [comment]
Suggestion on the blogs - I’d recommend against removing in favor of adding verbiage that the content is out of date with a link to the new content - or update and indicate that the content was updated and how it was.On Apr 19, 2024, at 8:36 AM, Rose Sakach ***@***.***> wrote:﻿
Some thoughts from the 4/19 Onboarding Meeting:

The categories are inconsistent (some use ZOWE, others do not"
The reference to INCUBATION is not accurate, incubation is a Squad designation, not a software designation.  Should use UNDER DEVELOPMENT or TECH PREVIEW or another term that covers both
Some blogs are old and outdated - should we perform a review and remove those that may lead the reader down an inaccurate (for present day) path?

**Comment by Joe-Winchester** [comment]
Hi @jmertic ,
The component categorization of the blogs has been completed.    You can see this today by viewing medium.com/zowe and looking at the banner that has the new categories at the top, which like to the new tags.  This has been well received by customers who are able to see at a glance which blogs pertain to the components that they are interested in (such as Zowe Explorer, or Zowe CLI, ...).
<img width="846" alt="image" src="https://github.com/zowe/community/assets/28100302/220aa7ba-9a1f-4861-b0c8-e169841f0023">
I'm happy to demo this whenever is a good time,  last week I was at the OSSummit in Seattle so missed a number of Zowe community calls, but back in UK at my desk for the next three weeks.

**Comment by jmertic** [comment]
All looks good - my only comment was not to remove content as pointed out by @RASakach.

**Comment by RASakach** [comment]
@Joe-Winchester can we please plan to review these changes with the Onboarding-DOC Squad scrum in 2 weeks? 

We have some minor recommendations and would like to understand the thinking behind the categories.  TYVM
