### ISSUE TITLE
Prepare Conformance Criteria for Support

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1084]
The work is happening within the ZLC on the preparation of the Support conformance criteria.

**Comment by RASakach** [comment]
Zowe Support Conformance Criteria has been drafted and revised.

Current state:  Being reviewed by ZLC members.

**Comment by balhar-jakub** [comment]
Questions raised by the ZLC towards the TSC:
 - What is a "core" for Zowe and how do we change it
 - What is the authentication process for the z/OS, distributed and containers. 
 - Code quality practices (Quality, tooling, coverage)
 - Who is an active contributor?

**Comment by balhar-jakub** [comment]
The support conformance was published.
