### ISSUE TITLE
Add a toolbar with dynamic menus to ZFM

### ISSUE THREAD

**Issue by timgerstel** [zowe/community#1093]
Start with download button

**Comment by balhar-jakub** [comment]
@timgerstel Could you please provide a bit more information about what you are looking for? Based on this information I don't even have an idea on which squad should be responsible for this. 

What does the ZFM means in this case?

**Comment by DivergentEuropeans** [comment]
@balhar-jakub This was an issue incorrectly categorized into the "Community" repo. Apologies 🙂
