### ISSUE TITLE
zOSMF compatibility and verification

### ISSUE THREAD

**Issue by jandadav** [zowe/community#1094]
**Is your feature request related to a problem? Please describe.**
zOSMF is developing at different pace than APIML. We have to provide compatibility with zOSMF versions 2.3 and 2.4 and various APARS.

**Describe the solution you'd like**
zOSMF releases and APARS are understood and evaluated as they come out. Process is documented (what where).
Internal mock is tested against applied updates/APARS for accuracy, problems are identified early.
Ideally we would like to own a ZOSMF instance where we can alter the setup/config/version/applied apars

**Comment by balhar-jakub** [comment]
Would be good to know what is current compatibility today. 
Is there a beta for the zOSMF related new versions?

How do we verify against new versions of zOSMF. 
What do we actually support at the moment?
