### ISSUE TITLE
Create a common zowe data model

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/community#110]
We have and will end up with a bunch of common attributes across zowe such as Jobs, Data-sets, files, address spaces, sysplex, LPARs etc.
In order to let extenders easily work with us in a predictable and relatable way we need to specify these and share them across zowe.

We need a strategy around how we collaboratively define these - how and where are they stored across different languages? (Swagger model?)

I guess this is a 2.0 items as currently I guess that the explorers, zss and cli all have different data models and will need merging together.

**Comment by balhar-jakub** [comment]
We are missing end-user documentation on how do we use the imperative to link the concepts across the JS libraries.

The audience
- Someone who wants to build an application and wants a feature that is not freely available within the desktop. 

No description of how to use Node SDK in the Desktop app. The desktop has a different session object than the SDK. The API ML authentication token could be used by both and therefore it would be possible to connect them. 

The possible outcome could be a sample app to build such an example application.
