### ISSUE TITLE
Docker GA Plan

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/community#1128]
Zowe's tech preview for having server content in a docker image has been available since the beginning of the year and we've been improving it with feedback that we've gotten, but a limiting factor to getting even more feedback is a chicken-and-egg problem about that some users wont try it because it is "tech preview" rather than released.

Because the docker preview is in good shape, I would like the TSC to discuss what is needed, if anything, in order to bring it out of tech preview and consider it an officially supported part of zowe. There are terms such as "zowe core" to describe components of zowe and how they relate to our primary offerings, but this isn't a component as much as it is a download option. I don't know what terms apply, but I'd like to give users assurance that they can use docker and in order to do that, I want to hear from the TSC that we're good to go or not.

**Comment by Joe-Winchester** [comment]
Great to hear improvements are being made based on feedback.  My question would be if the current docker tech preview went GA,  could it be evolved into the longer term solution of having more granular components for each component/micro-service that operated in a k8s stack ?   I recall @jackjia-ibm and others were looking at the long play solution it'd be good to know if/how the current tech preview GA would fit into that, whether we'd have two in play and what the timeline is.

**Comment by 1000TurquoisePogs** [comment]
Yes, I see no problem with doing a migration, where you start with z/os, move to this docker bundle, then move to the per-server images you are talking about. A migration could go in any order between those 3 types of installs in my mind, because I don't see anything that prevents the differences from being merely:
1) where the configuration & settings live and in what format, where migration can be solved by documentation & scripting conversions between the formats
2) how to start & stop zowe, as it will be different for each. this is solved by documentation.

**Comment by balhar-jakub** [comment]
As we have the final plan to deliver containers in 21PI3 I am closing this issue.
