### ISSUE TITLE
TSO session REGION size

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#1169]
Hi,

Our TSO session size for user is 4096. With ZOWE we got: IKJ56423I REGION SIZE 0065536 EXCEEDS LIMIT SIZE 0004096 errors.
I didn't find any settings where we can limit the REGION size. Is there a server side setting for this?
In the tso-profile there is a REGION parameter, but it doesn't apply to zosmf-profile and for VSCode profiles (also zosmf-profile or rse).

**Comment by zszabo14** [comment]
@MikeBauerCA

**Comment by balhar-jakub** [comment]
@MikeBauerCA Does this belong to the CLI repository?

**Comment by MikeBauerCA** [comment]
@zszabo14 you will need to have your TSO max region size adjusted to be 65536. It is documented [here](https://docs.zowe.org/stable/user-guide/systemrequirements-zosmf.html#z-os-requirements-for-z-osmf-configuration).

**Comment by MikeBauerCA** [comment]
Note that this is needed for zos-files and zos-jobs functions and is a requirement of the underlying z/OSMF REST APIs. @balhar-jakub we could move it, but I think we can just handle this question here.

**Comment by balhar-jakub** [comment]
The question was answered. As there is no response for a month we are closing the issue. If something else is needed, feel free to reopen. 

https://docs.zowe.org/stable/user-guide/configure-uss.html#address-space-region-size

**Comment by zszabo14** [comment]
@MikeBauerCA I understand, that this in the documentation.  If we want to give users a zowe based solution, which they use occasionally, but we have to increase REGION size to 65K. TSO session doesn't requires so much memory (we usually give 4K) so, we waste 61K/user!

**Comment by MikeBauerCA** [comment]
@zszabo14 For core Zowe CLI files functionality, the z/OSMF z/OS data set and file REST interface is used. For these APIs, the region size must be at least 65536KB as per IBM z/OSMF 2.1-2.3 doc. I found the [doc](https://www.ibm.com/docs/en/zos/2.4.0?topic=services-configure-zos-data-set-file-rest) for 2.4 and it appears that this setting may have been reduced to 50MB (a little better). 

> The topic IZUPRMxx reference information describes options for the TSO/E logon procedure that can be specified on the COMMON_TSO statement. You can specify a different TSO/E logon procedure name, account number, and address space region size, or use the default specifications.
The defaults should be adequate for most z/OS installations. If you specify alternative values, you must ensure that the z/OSMF user and z/OSMF administrator security groups are authorized to use the logon procedure name and account number that you specify. Also, ensure that the address space region size is at least 50 MB, and that your SMFLIMxx parmlib member and IEFUSI exit allow TSO/E users to use this amount of memory.
All z/OSMF users must have TSO segments that are defined in your installation's security database. Failure to have a TSO segment causes some z/OSMF functions not to work.

Another potential option for files functionality is our [z/OS FTP Plug-in for Zowe CLI](https://www.npmjs.com/package/@zowe/zos-ftp-for-zowe-cli). Although, ideally, I'd recommend using z/OSMF if possible.

If this remains a blocker for you, please let us know. We could open an RFE with IBM z/OSMF and see if they can adjust this setting.

+@dkelosky

**Comment by zszabo14** [comment]
@MikeBauerCA Thank you for the answer. I think the best solution would be to add a --region parameter to zowe CLI commands (or profile) and have a different REGION on the TSO login screen.

zowe zos-files list data-set "ibmuser.asm" --region 65536

while 

![image](https://user-images.githubusercontent.com/42870072/124175057-64c8a300-daad-11eb-98b6-c290108abf00.png)

**Comment by MikeBauerCA** [comment]
Zowe CLI or any REST client doesn't tell the z/OSMF API what region size to use. The API simply requires that region size to perform the request. 

I wouldn't think that changing the value in the IZUPRMxx would change the value in the 3270 TSO login screen.

+@balhar-jakub @jp669844

**Comment by zszabo14** [comment]
Hi, 

"I wouldn't think that changing the value in the IZUPRMxx would change the value in the 3270 TSO login screen." 

We had memory errors when we tried to use the CLI, our sysprog fixed it by increasing the user's region size (which is on the TSO login screen) to 65K. Did he wrong?

**Comment by MikeBauerCA** [comment]
That would fix it, but I think you may be able to just adjust this for z/OSMF only if increasing the user's region size is an obstacle in your environment. I'm hoping someone else can help advise us here - @balhar-jakub @jp669844 @plavjanik @dkelosky
