### ISSUE TITLE
Zowe Blog: How to Deploy a Zowe Sample API Service to z/OS

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#117]
Ready for OMP social promotion: https://medium.com/@dkelosky/how-to-deploy-a-zowe-sample-api-service-to-z-os-8c629f26f009

**Comment by Tbr00ksy** [comment]
FYI @dkelosky

**Comment by dkelosky** [comment]
thanks @Tbr00ksy - I'm going to try a series of these, it might take some time to finish them all:
![image](https://user-images.githubusercontent.com/14940561/58816638-df394700-85f7-11e9-95b4-219bf7943a53.png)

**Comment by Tbr00ksy** [comment]
@dkelosky this is great stuff! When you have published them, if you create an issue and tag myself or @jmertic and add to this epic we can help promote.

**Comment by christinevblum** [comment]
I will get social scheduled
