### ISSUE TITLE
git support

### ISSUE THREAD

**Issue by peterkendlbacher** [zowe/community#12]

**Comment by peterkendlbacher** [comment]
I would need support for git in the zowe gui.

This means I would like to access files on my windows machine with zowe. The files should be checked into a common non zos git somewhere on a linux machine.

What do I want to store there:

Mainly maven projects with the following content:

-> java
-> pl/1
-> cics configurations (for WLM, Platform, Applications, Bundles,...)
-> batch jobs
-> batch applications

The stuff should work somehow the same way eclipse works.

**Comment by peterkendlbacher** [comment]
This should not be a git connection to the mainframe, only a git connection to the local windows machine.

A modern aproach would store, compile the artifacts on a non mainframe environment and then deploy the finished artifacts on the mainframe.

**Comment by Tbr00ksy** [comment]
Hey @jordanCain can you add this to the work for the editors?

**Comment by jordanCain** [comment]
The only clean way to implement local file access would be to introduce a web server to the local system that makes the files available to a Zowe app/plugin. 

A File and Directory API exists in a non supported and non standardized form which would remove the need for a local web server but until this is a standardized feature we would not be able to implement a local file access solution.
 https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API

I think the only implementable solution today would be storing a git repo on the remote z/OS system. 

I will table this for discussion on the weekly webUI call for prioritization

**Comment by jplinardon** [comment]
Revisiting this thread. The Zowe team does development for the mainframe from their local workstations running Linux or Windows. Git is used locally, and work items are deployed to the mainframe. At the same time, it is possible to use git on the mainframe and do local development using the editor. The remote repos are all in the cloud, so remote.
These are traditional models. The request to use a remote git repo from the mainframe is very challenging and would require a server on the remote git host.
It is unlikely we would go down this path.
@1000TurquoisePogs for comments on interest to pursue this avenue.

**Comment by balhar-jakub** [comment]
We don't plan to implement anything in this area. As such I am closing this issue as Won't implement.
