### ISSUE TITLE
Release Cadence List/Table

### ISSUE THREAD

**Issue by IgorCATech** [zowe/community#1208]
**Is your feature request related to a problem or limitation? Please describe.**

As a Zowe user/committer/contributor, I'd like to have a list of release cadence of all Zowe components.

**Describe the experience you'd like**

A nice table with this information would be a great solution.

**Describe alternatives you've considered**

Leave everything as is, though it's not a great alternative

**Additional context**
N/A

**Comment by balhar-jakub** [comment]
Relevant topic. Figure out how to do it and how to automate it.
