### ISSUE TITLE
ChatOps

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1240]
Zowe itself may use some chatbots to simplify some of the common operations and questions answering. On top of that there may be a way to help customers deploy the chat bots solutions using Zowe based tooling.

**Comment by armstro** [comment]
I think it would be useful to have some agreement on what the community means when we say chatops - here are some thoughts: 
- Using chat to ask and receive answers to questions from Zowe doc 
- Using chat to ask and receive answer from z/OS REST APIs (somewhat like CLI but in a chat UI) 
- Use of natural language to ask questions 
- Chat as virtual "war room" with several people working a problem and contributing debug info, share the info, issuing commands in real time 
- Chat receiving events from monitoring tools to trigger debug activity 
- Chat is combination with dev tools to have debug include CI/CD pipeline and dev info (example when did a application last change? what automated testing was done?) 
- Per comments above - chat to simplify operations (need some examples) 
- Zowe to assist chatbot deployment (or chat to assist with Zowe tool deployment?) 

I think chat is a new UI technology in addition to Desktop, CLI and VS Code that could benefit from the same SSO, MFA infrastructure we are building in Zowe. I think we would provide vendor neutral ways to integrate/extend what we would deliver.

**Comment by pdubz3** [comment]
Thanks for the summary Bruce.  This is definitely aligned with that I think chatops means in Zowe.  We should create foundation within Zowe that enables all of those capabilities, and ideally the natural language support would be "pluggable" so that vendors can add intelligence based on their solutions.

**Comment by balhar-jakub** [comment]
Closing this one as result is the new incubation squad with the project under development.
