### ISSUE TITLE
Provide API Documentation on zowe.org with repo specific GH pages

### ISSUE THREAD

**Issue by zFernand0** [zowe/community#1296]
**Is your feature request related to a problem or limitation? Please describe.**
The API documentation for CLI/SDK related developers is very limited.

**Describe the experience you'd like**
Having a publicly available link will help

**Describe alternatives you've considered**
The only other alternative is cloning the project, and building the documentation manually

**Comment by zFernand0** [comment]
After discussing with the TSC, this issue could be split into multiple steps:

1. Address the look-and-feel of the existing Core SDK documentation under Zowe Technical Preview on [Zowe.org](https://www.zowe.org/download.html)
![image](https://user-images.githubusercontent.com/37381190/135480007-dab198a6-525b-411f-bb02-b2927884cf07.png)

    [`-> Browse SDK Reference`](https://docs.zowe.org/stable/typedoc_next/index.html) -> https://docs.zowe.org/stable/typedoc_next/index.html

    See an example here: https://zfernand0.github.io/zowe-cli-cics-plugin/

2. Discuss with the Docs Squad on how to differentiate between Core SDK Reference and Extended SDK Reference

**Comment by balhar-jakub** [comment]
@MikeBauerCA Is there any progress?

**Comment by zFernand0** [comment]
I guess I was hoping we could leverage GitHub pages for individual repositories (specially plugins) to provide SDK documentation.
But I'm fine with closing this if we don't think it's worth the effort 😋

**Comment by zFernand0** [comment]
After some discussion, I believe there are better ways to expose this information.
Closing! 
Hint: Typedoc Generator Repo coming soon
Thanks @t1m0thyj  😋
