### ISSUE TITLE
Maven Support

### ISSUE THREAD

**Issue by peterkendlbacher** [zowe/community#13]

**Comment by peterkendlbacher** [comment]
I would like like to check out maven projects from git and edit them in zowe.

To make this work fine a maven integration is needed, to unpack and manage dependencies. This should be somehow the same than eclipse works. 

A Maven Install in zowe should run a local windows maven install. A maven integration on z/os is not needed.

**Comment by Tbr00ksy** [comment]
@jordanCain similar to issue number 12.

**Comment by balhar-jakub** [comment]
We don't plan to work on this area, as such I am closing this issue as not planned.
