### ISSUE TITLE
21PI4 Planning

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#1306]
I would like to lock in the PI Planning Kickoff Meeting and Dates. I proposes that we do the following

Kickoff Meeting: Monday September 27 at 9:00 am. Squads will present their PI Input Objectives
PI Planning: October 27, 28, 29

Tentative Dates:
**21PI4 - (2021/10/26 - 2021/01/24)**
Planning - 2021/10/26 - 2021/11/01
Sprint 1 - 2021/11/02 - 2021/11/15 (Innovation Sprint)
Sprint 2 - 2021/11/16 - 2021/11/29
Sprint 3 - 2021/11/30 - 2021/12/13
Sprint 4 - 2021/12/14 - 2021/12/27
Sprint 5 - 2021/12/28 - 2022/01/10
Sprint 6 - 2022/01/11 - 2022/01/24

**Comment by jalel01** [comment]
Please bear in mind that 28 Oct is a public holiday in the CR. I would expect many to also take a vacation on the 29 Oct. Perhaps on this occasion planning could run from 25-27 Oct?

**Comment by nkocsis** [comment]
> Please bear in mind that 28 Oct is a public holiday in the CR. I would expect many to also take a vacation on the 29 Oct. Perhaps on this occasion planning could run from 25-27 Oct?

Yes, Elliot I don't see any reason why we couldn't hold it at that time

**Comment by balhar-jakub** [comment]
Planning is completed. As such closing this.
