### ISSUE TITLE
Clarify the Zowe Vnext and Vprior compatibility policy

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1346]
Consumers & Extenders of Zowe need a clear understanding of the Zowe LTS Version compatibility policy.
More specifically, the following expectations need to be explicitly clarified:

- will Zowe Vnext plug-ins work with the prior Zowe release?  (i.e. will Zowe V2 plug-ins work with Zowe V1 lts?)
- will Zowe Vprior plug-ins work with Zowe Vnext?  (i.e. will Zowe V1 plug-ins with with Zowe V2?)
- will CORE Zowe plug-ins work with Zowe Vprior and Zowe Vnext?
- What is the Zowe deprecation policy?
- What is the Zowe compatibility policy?
- Vendors may choose a different policy (i.e. they may choose to ensure Vprior plug-ins work with Zowe Vnext) and we can encourage them to provide their own compatibility matrix

Note:  The "RELEASE TIMELINE" posted at Zowe.org (download section) states the following - this appears to be the only "policy" we have related to compatibility:
_The combination of Active and Maintenance release provides two guarantees:
Critical defects will be fixed. The criteria for what constitutes a critical defect is covered in Release Process.
Extenders who achieve Zowe conformance for the long-term support version will not need to modify their product for it to remain functional when the Zowe community provides distributions within the release or modification level boundary within the same major version.
Production applications should only use Active or Maintenance releases due to the contract with extender products remaining functional and the community’s commitment to fix critical defects._

This needs to be addressed ASAP to allow extenders / consumers the ability to prepare for V2 in February 2022.

**Comment by pdubz3** [comment]
Rose and I have been working on an outreach communication for extenders which John Mertic has offered to deliver once we finalize the content.  What we have so far can be found [here](https://ent.box.com/s/x1g06qefyw9du5ygfxpa7m2httzu36xe).  In the message we've highlighted (in purple) some documents that need to be created publicly and included as links.  One is the "what's new in V2" document including both new features and breaking changes, as we discussed on the TSC call this week.  One is the V2 conformance criteria, as we know it today.  And one is the FAQs document that needs to be started.  Once those documents all exist with a public link we can update this communication and send it to all extenders.  Please review the document when you get a chance and provide any feedback you have.  Thank you!

**Comment by balhar-jakub** [comment]
Done and integrated in the zowe.org page
