### ISSUE TITLE
MVS and USS Explorer won't open

### ISSUE THREAD

**Issue by AnilKozan** [zowe/community#1369]
Hello everyone, 
We are installing Zowe v1.24. We have a problem with using MVS and USS Explorer. While using Zowe's MVS and USS Explorer components, it tries to open a TSO session, but gets the error "login: received unexpected msgType=3" and cancels the TSO session.
Please see and advise.
Have a good day.

**Comment by balhar-jakub** [comment]
Closing the issue as stale.
