### ISSUE TITLE
Zowe V2 Onboarding Tasks and Squad Asks

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1372]
Tasks:

1. Prepare XLS for V2 conformance criteria (work-in-progress):  

- https://ibm.box.com/s/fwlub33qln51r276c1qkijdcq7pgql0i
- Need assistance from squad members to complete.

2. Prepare EXTENDER NOTIFICATION letter:  Onboarding Squad is waiting on the "V2" zowe.org page
3. Prepare V2 FAQs:  https://ibm.box.com/s/tyv2hw3niv0wxni3pkzdffgrn3ttz2hw

Asks:
1.  Identify a member from each Squad to attend the EXTENDER OFFICE HOURS (hosted every-other Wed at 12pm ET) beginning on 12/15.  KICKOFF meeting will be on 12/8 [NOTE:  this is a change, we were hoping to do this on 12/1 but won't have enough time].  The OFFICE HOURS series will end on 2/23 (*very important to have a presenter on 12/8 kickoff to review changes in conformance with the audience)
2. Need someone to change the ZOWE CALENDAR and replace these Zowe Onboarding Squad meetings with ZOWE V2 OFFICE HOURS (PING Rose for details and confirmation on the changes)
3. The zowe.org/V2 page must be ready before we can send the Extender Notification letter, please advise the ETA (preferably week of 11/29)

**Comment by balhar-jakub** [comment]
Update the schedule to start with the CLI first week in January (01/05) and doing weekly calls. 

01/05 CLI
01/12 API
01/19 Explorers
01/26 App Framework
02/02 Systems/Install

02/09 - General Topics (Optional)
02/16 - General Topics (Optional)
02/23 - General Wrap-Up

**Comment by balhar-jakub** [comment]
I am closing this one, as all the squad Office hours happened successfully.
