### ISSUE TITLE
Cannot get APIML properly started; cannot log into zowe desktop

### ISSUE THREAD

**Issue by BLJeffery** [zowe/community#1385]
I have been trying for quite some time to get Zowe running on Z/OS properly.  I have installed Zowe version: v1.24.0    though some of the components indicate v1.25.  I have configured a RACF keyring using the sample job.  Regardless of what I attempt, I cannot logon to the zowe desktop without getting:
2022-01-05 17:37:50.893 <ZWED:16780356> ZWESVUSR WARN (org.zowe.zlux.auth.safsso,zssHandler.js:136)  Error: connect ECONNRE
    at TCPConnectWrap.afterConnect Ýas oncomplete¨ (net.js:1154:16) {                                                      
  errno: -1128,                                                                                                            
  code: 'ECONNREFUSED',                                                                                                    
  syscall: 'connect',                                                                                                      
  address: '9.12.24.81',                                                                                                   
  port: 7554                                                                                                               
}                                                                                                                          

I cannot find errno -1128 either.   I am attaching a log file from the latest attempt.  I have been hitting this wall for 2 weeks regardless of what I try.

Regards.  Please advise, log file attache
[ZOWE.LOG.D004.TXT](https://github.com/zowe/community/files/7816809/ZOWE.LOG.D004.TXT)
d

**Comment by 1000TurquoisePogs** [comment]
Hi,
The logs indicate a networking issue.
Can you reach "https://monos99.pok.stglabs.ibm.com:7554/" in a web browser? Does it contain any errors or is it just showing green marks for each service indicating success? The logs show a lot of socket errors and timeouts, so its not clear to me if the servers are actually accessible over the host monos99.pok.stglabs.ibm.com or ip 9.12.24.81. Is there a firewall configuration preventing binding to ports 7554, 7553, 8544 and other ports seen in the instance.env file?

**Comment by BLJeffery** [comment]
I cannot reach the url you specified.  As I look at the network stats,  several of the ZOWE ports are not 'listening'.  I have just put them all in the IP profile to reserve the specific numbers in the instance.env file.  There is no firewall that I am aware of.  The only page I can get to is the Zowe Desktop (https://monos99.pok.stglabs.ibm.com:8544/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html) but I cannot log in - ECONNREFUSED.  Port 7554 is not connected.

**Comment by BLJeffery** [comment]
What has to be increased for the timeouts you're seeing?  Can you give me a specific socket error?   I'm an MVS technician - the logs don't make a lot of sense to me.

**Comment by 1000TurquoisePogs** [comment]
All the Zowe ports are TCP, and the timeouts you see are a result of the ports not listening.
port 7554 is for an important server for several parts of zowe so if its not running, others may fail too.

Here's a picture with all the port numbers showing what part of zowe they're from https://docs.zowe.org/assets/images/zowe-architecture-1ab66b02afb86255c9d94c3f8e53c9a9.png

Do you have TCPIP logs that show an attempt to do something on a port such as 7554, so we can learn why the servers cannot bind? One interesting thing to note is the technology: 8544 is nodejs, whereas 7554 is java.

Another log you can use is to set `APIML_DEBUG_MODE_ENABLED=true` in a new line within the "instance.env" file found in the Zowe instance USS folder. Changes to that file take effect when restarting the zowe ZWESVSTC.
When using this, you do not need to attempt login to those websites anymore, simply startup the servers, check for a TCPIP bind within a couple of minutes (or not) and then the logs may tell us more.

**Comment by BLJeffery** [comment]
Thank you for your response.  The log I sent did have APIML debugging turned on.   As it turns out, I applied maintenance to Java 8.0 and the connection issues resolved.  I will be closing this issue.

B. Jeffery
