### ISSUE TITLE
Automate new zowe.yaml creation

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/community#1386]
One of the biggest zowe v2 usability problems I have encountered so far is how much manual entry I need to get a zowe instance configured. In v1, several configuration options were known when running scripts: nodejs and java locations, hostname, ip, and more.
But the v2 instructions state to take a .yaml example file and customize it, so there's much more manual work to do, making the installation more error prone and take longer.

Here are ideas to improve v2:

Make a "zwe" instance init command which will create a zowe.yaml file in a folder of your choice, with the following values passed in as arguments, or automatically found, or prompted for if automation fails:
- Java location
- nodejs location
- hostname
- ip
- runtime directory (should be the location of zwe/.. )

Likewise, certificate config has more manual entry than I'd like. There's sections in zowe.yaml where you list hostnames and domains, and locations of keystore and keystore objects, which can often be derived or redundant.
If "zwe" had cert init commands, the amount of input can be reduced.

**Comment by jackjia-ibm** [comment]
Few comments on my thoughts and status:

- java/node location should be optional. I have code trying to automatically detect where are they. I can double check if anywhere is still hardcoded to require those definition. That means, users are not required to customize `java.home` and `node.home`, just leave them empty. Once i verified, I will comment out whose configs from `example-zowe.yaml`.
- I need to think more about detecting `hostname`. There are so many errors in the past related to incorrect hostname setup. There is no reliable way to detect hostname. The user needs to understand what are externalDomains and what are HA instance hostnames. They are different.
- There is no place to really use IP in v2. If the user doesn't have hostname/domain name, they can put IP in externalDomains or HA instance hostname. The only place asking for IP specifically is ZWEKRING jcl RACDCERT command, and I think we may be able to improve it to be more smart. Resolving IP from hostname is not reliable.
- `zowe.setup.certificate.san` is optional. I will comment them out by default.
- The next build, with keyring support, will also have an option of `--update-config`. This will write the certificate setup back to zowe.yaml based on `zowe.setup.certificate` information. Hope this simplifies certificate setup and we can go from there.

  With this improvements, the minimal the user needs to define is:
  ```
  zowe:
    setup:
      certificate:
        type: PKCS12
        pkcs12:
          directory: /keystore-dir
  ```
  or
  ```
  zowe:
    setup:
      certificate:
        type: JCERACFKS
        keyring:
          name: ZoweKeyring
  ```
  No other actions are required if he passes `--update-config` option.
  Without `--update-config` option, the init process will display a section showing what should be updated in zowe.yaml.
