### ISSUE TITLE
APIML - zss 500 error

### ISSUE THREAD

**Issue by BLJeffery66** [zowe/community#1388]
Zowe version: v1.25.0 
ZWES1013I ZSS Server has started. Version '1.25.0+20211013' 
 
I am able to reach the API Mediation Layer via port 7554.   I am able to using CLI from a Windows deskotp.  However, I cannot log into the Zowe Desktop Webpage on port 8554.  The error received is:
  ZSS 500
org.zowe.zlux.auth.safsso: ZSS 500 
{"messages":[{"messageType":"ERROR","messageNumber":"ZWEAG708E","messageContent":"The request to the URL '/api/v1/zss/login' failed after retrying on all known service instances. Caused by: java.net.ConnectException: EDC8128I Connection refused. (errno2=0x74940000) (Connection refused)","messageKey":"org.zowe.apiml.gateway.connectionRefused"}]}

SSO is not running.  Is it required?  I cannot tell.  RBAC is also turned off.

**Comment by BLJeffery66** [comment]
ZWEAG708E#

The request to the URL '%s' failed after retrying on all known service instances. Caused by: %s
Reason:
Request to the server instance could not be executed on any known service instance.

Action:
Verify the status of the requested instance.


This is not the least bit helpful.

**Comment by BLJeffery66** [comment]
The full message from the started task log is:

2022-01-11 18:25:54.165 <ZWED:33555639> ZWESVUSR WARN (_zsf.auth,webauth.js:364) ZWED0003W - User=undefined (org.zowe.zlux.auth.safsso): Session authenticate failed. Plugin response: {"success":false,"error":{"message":"ZSS 500 ","body":"{\"messages\":Ý{\"messageType\":\"ERROR\",\"messageNumber\":\"ZWEAG708E\",\"messageContent\":\"The request to the URL '/api/v1/zss/login' failed after retrying on all known service instances. Caused by: java.net.ConnectException: EDC8128I Connection refused. (errno2=0x74940000) (Connection refused)\",\"messageKey\":\"org.zowe.apiml.gateway.connectionRefused\"}¨}"},"reason":"ConnectionError","apiml":true,"zss":true,"sso":false,"canChangePassword":true}   

ZWED0003W  is not documented anywhere I can find.

**Comment by BLJeffery66** [comment]
Also, I do not run ATTLS on this system.  Is is required?

**Comment by 1000TurquoisePogs** [comment]
Hi,
Can you check if port 8542 is bound? It is the port of "zss", where the connection is failing. Logs about zss/8542 may be shown with prefixes "ZWES" in the job output.
ATTLS is not required.
SSO is only required under circumstances such as MFA being used.

**Comment by BLJeffery66** [comment]
Hi, sorry for the delay in my response.  8542 is not bound.  I see this in the log:

ZWES1035I ZSS Server settings: Address='monos99.pok.stglabs.ibm.com', port='8542', protocol='http'                        
ZWES1025I Will not accept JWTs: Disabled in the configuration.                                                            
ZWES1063I Caching Service settings: gateway host 'monos99.pok.stglabs.ibm.com', port 7554                                 
Plugin=org.zowe.configjs, found 0 data service(s)                                                                         
Plugin=org.zowe.explorer-ip, found 1 data service(s)                                                                      
Dataservice: /usr/lpp/zowe/components/app-server/share/explorer-ip/lib/ipExplorer.so loaded.                              
CEE3501S The module zssServer was not found.                                                                              
         From entry point ipExplorerDataServiceInstaller at statement 1074 at compile unit offset +0000009A at entry      
         offset +0000009A at address 1D623452.

**Comment by BLJeffery66** [comment]
This is running on z/OS 2.5.  Java 8-64, nodejs 14, make 4.3

**Comment by BLJeffery66** [comment]
attaching log of started task and zss log with debug turned on.
[zssServer-2022-01-13-17-16.log.txt](https://github.com/zowe/community/files/7864759/zssServer-2022-01-13-17-16.log.txt)
[zowe.log.d013.txt](https://github.com/zowe/community/files/7864776/zowe.log.d013.txt)

**Comment by BLJeffery66** [comment]
the 'missing' module, zssServer is in /usr/lpp/zowe/components/zss/bin .   Where should it be?  What path variable points to it?

**Comment by BLJeffery66** [comment]
This fails on both z/OS 2.5 and z/OS 2.4

**Comment by BLJeffery66** [comment]
Is there some other forum I should be putting this information since I don't seem to be getting much help on this one?

**Comment by BLJeffery66** [comment]
no body interested.
