### ISSUE TITLE
Split the Web UI into Web UI and ZSS squad

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1396]
Topic to discuss.

**Comment by 1000TurquoisePogs** [comment]
Some background:

# Technical
The app-server (which powers the desktop) and its apps conditionally depend upon ZSS, much like apiml conditionally depends upon ZSS. The condition is if you're trying to access some z-specific operation.
There is some commonality between app-server and zss, about how they can read common parameters and can operate on different portions of the same plugins.
However, zss does not depend on app-server. It can run by itself, as we see when using containers.
And, the codebase is completely different.

Where ZIS lives is also a thing to consider. ZIS is also standalone, but ZSS tends to use it under certain configs though it can start without it. ZIS is however in the same codebase as ZSS, and you need related skills to work on either.

# Managerial
Today, app-server, desktop, apps, zss and zis are all managed by the same people.
ZIS and ZSS should be managed by the same group of people.
But the people who manage ZIS and ZSS do not necessarily have the skills/interest to manage app-server,desktop and apps, and vice-versa.

Irek (current webui squad TSC representative) and Joe Devlin currently are the primary people in the Zowe community are experts in ZIS & ZSS, historically are willing to do reviews of incoming pull requests, and get involved in architectural improvements.

# Proposal 
As the webui squad lead, I'd like to give them the power to split the webui such that zss and zis are split into their own squad, and then have them determine which other squad members they'd like. There are a couple other people in the webui squad who would fit the bill, likely being squad members in both squads.

**Comment by balhar-jakub** [comment]
Close as there is now proposal to track the issue.
