### ISSUE TITLE
Refine "extensions" versus "components"

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/community#1398]
Our documentation defines the difference between the server-side concepts of "extensions" and "components" as:
```
component:

Component refers to the most generic way to describe a program which can work within Zowe. It can be a microservice, a Zowe App Framework plug-in, or even just a shared program to be used by other Zowe components. This is also the generic word when referring to both Zowe core components and extensions. In most of the cases described in this topic, this terminology does not include programs running on the client side, like Zowe CLI plug-in or Zowe Explorer (VSCode extension).

extension:

Extension is similar to component but excludes Zowe core components. It is recommended that you install all Zowe extensions into a shared extension directory.
```

However, the truth in the code is that there is no difference in the contract of "manifest.yaml" between components and extensions. From our code point of view, extensions ARE components, and there's really just 2 things: built-in components and extension components.
I think we should update this because mutual understanding of terms is critical to frameworks and zowe community often colloquially has more than one word for a part of zowe. I just want people to write their code to spec without confusion.

**Comment by balhar-jakub** [comment]
First I agree that we should make sure that we use the terms in a way where we use one term for one thing. 

I believe that we need the two terms though but in different meanings.

Let's keep the component as it is now, so the things that are installed with manifest.yaml and are living within the Zowe instance folder will remain a component on the server-side. 

We need to name properly the products that are conformant with the API Mediation Layer that isn't living within the Zowe instance in any way and are onboarding dynamically, therefore there is nothing directly linked to the Zowe apart from the URL of Zowe. Could we then call these services extensions?

**Comment by 1000TurquoisePogs** [comment]
To elaborate on what Jakub and I said
On zowe server infrastructure, there is a metadata and packaging standard for files used by zowe, whether builtin or added. Collections of files packaged to the standard are "components", but the above doc also says they're sometimes "extensions"

Servers can attach to the mediation layer without any files, but the conformance program still applies to them so that you can know the servers are using the mediation layer properly. So, there is a way to extend the mediation layer that is only seen at runtime, not at rest. At minimum, you could call the servers "Zowe-conformant servers".

From a marketing perspective, it's easy enough to say "Our product is zowe conformant" without saying if its a component or a server that adheres to our rules.

But from a code perspective, terms are a problem when you try to unify client terms with server terms.

```
Component: Any built-in or 3rd party code that is started by Zowe.
Extension: Any 3rd party code that adds to Zowe, regardless of if its a CLI, desktop, zis, or zis plugin or a gateway service.
```

In this way, "extensions" are sometimes "components". I don't think CLI uses "component" in this way so far, but if it became compatible with the component manifest we use on servers, it would be able to participate with how we can install multiple extensions with a single command due to "component manifest" including more than one extension, such as both a desktop plugin and a gateway service. It would be beneficial for the times we present Zowe as 1 thing.
