### ISSUE TITLE
Extract the Intellij plugin as a separate squad from the CLI

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1449]
There is a new intellij plugin in a beta that is now handled and owned by the CLI squad and this feels like it isn't the right place for it.

**Comment by MikeBauerCA** [comment]
We are nearing publication of a technical preview on the JetBrains Marketplace. The IntelliJ Zowe Explorer plug-in will be listed [here](https://plugins.jetbrains.com/organizations/Zowe). An associated blog will also be published following the release. 

I'd like the following for this new squad and product:
- A zoom account and access to add events to the Zowe calendar to schedule public standups/planning meetings
- Representation on zowe.org
- Representation on our Zowe Downloads page
- Representation in PI Planning events 
- A representative from that team to join our TSC calls and provide updates
- Representation on our Zowe Docs Site

**Comment by balhar-jakub** [comment]
Close as there is now a valid proposal to track the issue.
