### ISSUE TITLE
User feedback, Q&A

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/community#1451]
One or two people who have installed and work with other users to install Zowe's servers have offered their time to share their experiences with us on Tuesday, 22nd.
Let's hear from them what they like about Zowe's install & config, and what we could improve upon.

I believe the individuals also work with products built on top of Zowe, so I'm curious how well we do or what more we can do to have zowe make zowe-based products be easier to install/config by leveraging zowe constructs & knowledge, but looking for other valuable questions to discuss.

**Comment by 1000TurquoisePogs** [comment]
Some notes I took from this meeting:

- Zowe on z/os often considered infrastructure software (because its a prereq for zowe-based products)
    * Often managed by z/OS sysprogs
* z/OS users often have extreme separation of duties (~10 people with different permissions) therefore needing many people to handle different steps of zowe install
* Installation of products prereqing zowe often done by a different person, repeating the issue.
* These users always used SMPE, never pax. (Perhaps pax/smpe division is dev vs prod users)
* Documentation skips between SMP/E and non-SMP/E instructions which could confuse
* Installation steps consist of semi-automated, fully automated, manual steps... is this a good thing? Should we have more of one or the other? At least, can we make it easy to know which steps are which at a glance in our documentation
    * More automation=better, but dry-run mode needed?
* Different places of code have the same name for different things (think: ZOSMF_HOST vs ZOWE_ZOSMF_HOST. VERIFY_CERTIFICATES vs APIML_VERIFY_CERTIFICATES. label vs alias)
* Install mix-matches USS and MVS... is this divided well so that you don't have to be a master of both worlds?
*

**Comment by 1000TurquoisePogs** [comment]
I missed good notes for the later portions of the call but it seems like there were action items about Jorn, Joe, Onno continuing the conversation as needed around test systems covering a wide range of situations more accuretly.

**Comment by jthyssenrocket** [comment]
[2022-02-22 Zowe install observations.pptx](https://github.com/zowe/community/files/8118682/2022-02-22.Zowe.install.observations.pptx)

**Comment by 1000TurquoisePogs** [comment]
Some take aways that I missed in the first comment:
* Every step must be automatable, but can be done step-by-step if desired
* Dry-run mode where the effect of a step is seen before it is done
* Clearly documented separation between... 
    * area in which installer writes out customized JCLs for using, from a read-only template area
* "Don't make me learn another new thing, even if the other old thing is worse, I already know it" - Paraphrased from user recently
* The system admins are not likely the users of Zowe, so our attempts to modernize do not need to be as aggressive on the install/config/admin side.
