### ISSUE TITLE
General guidelines for the acceptance of new squads in Zowe 

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1456]
When talking about acceptance of the new squad we are discussing some kind of checklist that would help TSC understand whether the squad is actually a good fit to the Zowe.

**Comment by 1000TurquoisePogs** [comment]
We already did this last year:
https://github.com/zowe/community/blob/master/.github/ISSUE_TEMPLATE/proposal.md

https://github.com/zowe/community/blob/46fbebe8fb80f70ecddcb861d984d9d45d39107a/Technical-Steering-Committee/lifecycle.md#proposal-acceptance-process

https://github.com/zowe/community/pull/1241

You asked for the adoption of a squad to be postponed until it was filled out, and now it is: https://github.com/zowe/community/issues/1460
Let's continue the discussion on the latest proposal.

**Comment by balhar-jakub** [comment]
@1000TurquoisePogs I created this issue to figure out something like internal conformance criteria for the squads to become active so that the squads have a checklist that they need to go through and when they are done, it gives us easy way to verify that it's time to move the squad to the active state. 

It isn't that heavily focused on the zOS related squad. We will need to resolve this for 5 more incubators at the moment and I guess there will be more coming in future.

**Comment by balhar-jakub** [comment]
Done and merged
