### ISSUE TITLE
Onboarding Asks for Zowe V2 Consumer-Focused Office Hours

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1458]
(1) Agree on session delivery dates
(2) Upon completion of  (1), update Zowe Office Hours calendar entries with focus topics (see proposed schedule below)
(3) Update zowe.org/vnext with new office hours schedule & reverse the order of the current matrix (i.e. most current on top)
(4) Update zowe.org/vnext with instructions on joining the "Zowe consumer mailing list" (position at the top of the v2 Office Hours matrix)
(5) Discuss / approve proposed format for Consumer-focused sessions
   - Overarching Zowe V2 messaging
   - What's new with Zowe xxxxxxx (value-add changes for this component from a user's perspective)
   - What does it mean for Zowe xxxxxx users (the User Experience perspective) DEMO is preferred here...
   - Does it change the installation, upgrade, or configuration for Zowe xxxxxx (if yes, describe how; point to doc)
   - Feature by feature list that includes:  Feature Name, benefit to the USER (demo if it makes sense)
   - Who / how to contact if questions

(6) Proposed schedule:  30 minute recorded sessions [these are short on purpose] - if more time is necessary, we can schedule PART 1 and PART 2 sessions:
  - Wed 3/16 (Zowe API ML)
  - Wed 3/23 (Zowe CLI)
  - Wed 3/30 (Zowe Explorer)
  - Wed 4/6   (Zowe Web UI)
  - Wed 4/13 (OPEN Q&A)
  - Wed 4/20 (OPEN Q&A)
  - Wed 4/27 (OPEN Q&A)

**Comment by balhar-jakub** [comment]
Closing as the office hours ended.
