### ISSUE TITLE
Zowe Explorer for IntelliJ Squad Proposal

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/community#1461]
Thank you for being interested in becoming a squad within Zowe. To help you with the proposal we will need you to provide following information. To learn more about the whole process, please consult [lifecycle](../../Technical-Steering-Committee/lifecycle.md).

* Name of squad (must be unique within Zowe)
  * Zowe Explorer for IntelliJ Squad

* Squad description (what it does, why it is valuable, origin and history)
  *  Intellij-based IDEs are some of the most popular integrated development environments among software developers. The best known variant is focused on Java development - IntelliJ, but there are also options for other languages. More specifically, the Zowe Explorer IntelliJ plug-in can support mainframe access for IntelliJ, PyCharm, PhpStorm, WebStorm, CLion, RubyMine, DataGrip, Rider, AppCode, Android Studio, and GoLand. This project was originally accepted as an incubation project under the Zowe CLI squad. It has progressed beyond that stage and has a technical preview available on the marketplace.
  * The Zowe Kotlin SDK should also reside with this squad as the Zowe Explorer for IntelliJ is the primary consumer of this technology today. 

* Statement on alignment with Zowe mission and principles
  * This project aligns with Zowe’s mission to reduce the learning curve and attract new people to z/OS by enabling them to leverage their IDE of choice.

* Ambassador from Zowe (helps mentor projects) - Preferrably TSC or ZAC member
  * Joe Winchester & Michael Bauer

* External dependencies (including licenses)
  * None

* Initial committers (how long working on project)
  * Uladzislau Kalesnikau 
  * Valiantsin Krus
  * Valery Aranouski
  * Pavlin Zahariev
  * Aliaksei Burak

* Infrastructure requests (CI / OMP Cluster)
  * We would like to leverage Zowe CI infrastructure or GitHub actions

* Communication channels (Slack, irc, mailing lists) - Zowe has Slack channels, Mailing lists and forums, let us know if you already have channels we should be aware of. 
  * We have the `#zowe-explorer-intellij` channel on OMP slack
 
* Preferred stage (incubation, active)
  * Incubation

Further notes:

* Zowe project requires code contributions to Zowe to be made under the [Eclipse Public License 2.0 (EPL-2.0)](https://spdx.org/licenses/EPL-2.0.html) and all non-code contributions to be made under the [Creative Commons Attribution 4.0 International license (CC-BY-4.0)](https://spdx.org/licenses/CC-BY-4.0.html) and having each committer agree to the [DCO](https://developercertificate.org/)
* Zowe project expects squads to have the projects under [Zowe GitHub](https://github.com/zowe)
* Zowe project expects squads to use GitHub for tracking issues and common ZenHub board to have visibility across the whole Zowe.

[Zowe Explorer IntelliJ Repo](https://github.com/zowe/zowe-explorer-intellij)
[LICENSE](https://github.com/zowe/zowe-explorer-intellij/blob/main/LICENSE)
[Blog Announcement](https://medium.com/zowe/intellij-for-mainframe-powered-by-zowe-76afbd3a1945)
[Technical Preview](https://plugins.jetbrains.com/organizations/Zowe)

**Comment by balhar-jakub** [comment]
Accepted as Incubator Squad within Zowe.
