### ISSUE TITLE
What does a breaking change mean?

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1466]
In the release process, we reflect on the breaking changes. It seems that we all had a tacit understanding of what it means. 

We got feedback that this is not the case and we need to have a discussion on what would it mean. 

Most probably we should ask all the squads to provide their definitions in the written form.

**Comment by plavjanik** [comment]
Slides for discussion: https://docs.google.com/presentation/d/1kBX9ZN9cgGfU8EYW1zzZ74bUFkhOiF8OBePmjSMJmZA/edit?usp=sharing

**Comment by balhar-jakub** [comment]
Discussed within the architecture and TSC. 

The proposal is for a policy where we will ask each squad to outline how they approach deprecation and make sure that there is obvious place to do so.

**Comment by balhar-jakub** [comment]
Accepted and published.
