### ISSUE TITLE
Create & Manage a Zowe Consumer Distribution List

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1470]
What:  An optional, opt-in Zowe Consumer Distribution list
Why:   The OMP has provided the Zowe Community with a Zowe Extenders Distribution list, we do not have a similar distribution list for Zowe Consumers and thus rely on Consumers to constantly check-in at Zowe.org, social media, etc.
When:  ASAP to begin sharing Zowe V2 information and educational opportunities

How:  Present zowe.org visitors with an option to JOIN OUR MAILING LIST, where consumers will have the opportunity to add (or remove) their preferred email address.  The mailing list will be made available to a limited number of designated Zowe Community Squad Members who will ensure appropriate usage.

The Onboarding Squad is looking for guidance and guidelines from OMP.  @jmertic we are hoping you can assist with this request.

**Comment by jmertic** [comment]
Thanks for raising this @RASakach. 

There currently is a https://lists.openmainframeproject.org/g/zowe-user list which probably would make sense to leverage, but not sure if that makes sense to use. It would also be good to know if this is more announcement oriented, or if there is expectation of interaction.

**Comment by jmertic** [comment]
I think this is done now? @RASakach

**Comment by balhar-jakub** [comment]
@jmertic Creation is done. Thanks for the help.

We still need to figure out the management part.

**Comment by RASakach** [comment]
Idea for managing:
(1) any new announcement should probably be sent to this list 
(2)  a new OMP blog introduction / contents should be sent to this list
(3) Onboarding will produce a policy on how this list is managed, maintained etc.

Finalization is in-progress
