### ISSUE TITLE
Publish the Zowe V2 Conformance programs

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1471]
The Zowe V2 Conformance Program is scheduled to be available on April 25, 2022 (when V2 LTS is announced)

Requirements Include:

1. Modifications to the (or the addition of a new)  conformance program website:  [](https://www.openmainframeproject.org/projects/zowe/conformance)
2. Creation of Zowe V2 Conformance badges for all eligible components including:  API MEDIATION LAYER,  APP FRAMEWORK, CLI, EXPLORER FOR VISUAL STUDIO CODE
3. Modifications to the (or the addition of a new) Support Provider program website:  [](https://www.openmainframeproject.org/projects/zowe/conformant-support-provider)
4. Creation of Zowe V2 Conformance badges for all existing SUPPORT PROVIDER eligible items including:  COMPREHENSIVE, API MEDIATION LAYER, APP FRAMEWORK, CLI, EXPLORER FOR VS CODE
5.  Creation and publication of the V2 Testing Criteria for all eligible Zowe components
6.   Creation and publication of the V2 Testing Criteria for the Support Provider Program
7.  Revised PARTICIPANT FORMS:  eliminate the single form for ALL programs and produce a form for EACH component (Note:  A single form may be used for the SUPPORT PROVIDER PROGRAM)
8. Revised process that requires the applicant to include the completed checklist as part of or in addition to the DOCUSIGN participation form
9.  A community-managed GitHub storage location to house approved participant forms
10.  OMP Interactive Landscape updates to reflect the 2 new programs

Breakdown of work effort:
- Onboarding Squad:  1, 3, 5, 6, 9
- OMP:  2, 4, 10
- Onboarding + OMP:  7, 8 

Note:  Ideally, we would like to offer existing extenders the opportunity to pre-apply for V2 conformance prior to April 25th (beginning April 1st).  The work effort associated with this is TBD.

**Comment by jmertic** [comment]
Great to see! Let me know if there might be any changes to the T&Cs, as we will need a bit of lead time to get that through legal.

Also confirming at that point we will deprecate the v1 program - correct?

**Comment by RASakach** [comment]
Thanks for joining the weekly Onboarding Scrum call @jmertic !

Some key decisions on this request:

1. The V1 Conformance Program will remain ACTIVE, however, the Conformance Landing Page [](https://www.openmainframeproject.org/projects/zowe/conformance) will showcase the V2 Conformance Badges.  Additionally the landing page will offer the applicant the opportunity to apply for EITHER V1 or V2 Conformance.  
2. The Zowe.org "extend" page:  [](https://www.zowe.org/extend.html) will showcase ALL Conformance badges to mitigate any concern over a small representation of V2 conformant extensions
3. The Onboarding Squad will produce the .MD version / table format of the V2 Testing Criteria for all applicable components
4. The Onboarding Squad will produce a "draft" of the proposed V2 conformance application process, including how to store the completed "Testing Criteria" form
5. @jmertic (and Onboarding Squad) will review the existing T&Cs to determine if any changes are necessary in support of the V2 application process as well as the storing of the completed testing criteria
6. The "new" application process will not be ready / available for pre-apply thus we will need to draft an alternative process

**Comment by jp669844** [comment]
PR for v2 conf. docs is here: [https://github.com/openmainframeproject/foundation/pull/232](https://github.com/openmainframeproject/foundation/pull/232).

**Comment by jmertic** [comment]
Logos at https://github.com/openmainframeproject/artwork/pull/35 - note there is an issue with the SVG ones where the text isn't being embeded right that I'm having them fix.

**Comment by jmertic** [comment]
Logos are now ready to review at https://624b5ad791216c0008620766--mystifying-edison-1a481c.netlify.app/

**Comment by jmertic** [comment]
Anything left to do here?

**Comment by RASakach** [comment]
We agreed to postpone the revisions to the Conformance Application process until V3.
This issue can be closed.
