### ISSUE TITLE
Configure a Pre-Apply Process for Zowe V2 Conformance

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1484]
Propose a process for V2 pre-application to be day-1 ready with a V2 conformance landscape with all qualifying extensions.

The Zowe Onboarding Squad has agreed to the following process proposal:

- Publish the 5 Zowe V2 Conformance Testing Criteria Checklists (API-ML, App Framework, CLI, Explorer for VS Code, Support Provider)
- Modify the existing single-form "application" to link to the new checklists and reference the V2 program
- Send a pre-apply notice to ALL existing V1 conformant Extenders with instructions on how to apply in advance 
- Open the program on or before 4/8
- Close the program on 4/25 / prepare the new V2 Conformance Pages for the formal process; publication TBD

To implement, we need @jmertic to help with the following tasks:

1. Approve the PULL request to create the individual testing Criteria forms in the proper format:  https://github.com/openmainframeproject/foundation/pull/232
2. Create the V2 version of the DOCUSIGN: and name it v2_participation_form.md for reference the initial version is located here:  https://github.com/openmainframeproject/foundation/blob/main/zowe_conformance/participation_form.md
3. Suggested modifications to item 2 are as follows:  _The Participant confirms that the products and services identified below as Qualifying Offerings either (a) have passed all of the tests that are marked required below, as described in the corresponding Test Evaluation Guide or for Participant Conformance as described in the V2 Support Provider Evaluation Guide and are Qualifying Offerings under the Program Terms; or (b) prior to usage of the Conformance Marks, will pass all of the tests described in the Test Evaluation Guide, and will be Qualifying Offerings under the Program Terms._
4. Suggested changed throughout the document:  _change all Zowe v1 to Zowe v2_
5. Tag @RASakach when 1 -4 are completed and you approve opening the pre-application process for Zowe V2 conformance

**Comment by jmertic** [comment]
We also need to think about how to manage v1 conformance for people net-new with v2 conformance as discussed during the ZAC meeting.

**Comment by RASakach** [comment]
Update:  we are hoping to open Zowe V2 Conformance to pre-applications the week of April 18th.  Pending creation of the V2 Docusign and the V2 Testing Criteria PDF.

**Comment by jmertic** [comment]
Forms at https://github.com/openmainframeproject/foundation/pull/234#issuecomment-1099222818
