### ISSUE TITLE
Zowe Packaging & Containerization Requirements

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1488]
Need clarity and closure on this topic for Zowe V2 (and beyond).

(1) Containerization for Zowe Extensions
- It is possible for an extender to produce a Zowe extension for a Zowe component (that participates in the conformance program) and package it in a container. 
- If YES, that conformance criteria SHOULD include a section titled CONTAINERIZATION that is only required to be completed if the extension is containerized.  If NO, no change to the conformance criteria.

(2) Determine how best to "guide" Vendors (et al) who produce an Application (?) built on top of Zowe
 - How can they certify their Application is interoperable with any given release of Zowe?
 - How can they certify they meet PACKAGING & CONTAINERIZATION requirements for Zowe?
 - - One idea, add a section on PACKAGING and CONTAINERIZATION requirements within Zowe Docs

**Comment by Joe-Winchester** [comment]
Thanks @jackjia-ibm ,  I hadn't realized that the container packaging critera are included in the  `/extend/`  docs area.

**Comment by balhar-jakub** [comment]
Are there any further steps we want to take?

**Comment by jackjia-ibm** [comment]
My understanding is there are three questions remaining open for future, but no immediate needs.

1. How Zowe conformance handles new plugin format, for example, ZIS or ZSS plugin, or potentially ZoweChat plugins. They will have different criteria to build their plugins.
2. Currently packaging format are embedded into APIML and AppFramework plugins, but it should also apply to any new server component/plugin conformance.
3. Whether we should create containerization badge, if it provides marketing value, or if extenders see the badge has value to promote their extension.

If we go further with App Store idea, how the badges will showing up in App Store and potentially the current extend page listing page is a prototype of App Store listing.

**Comment by RASakach** [comment]
What is the value of containerization of Zowe extensions to the consumer?
If a single extension is  (Zowe-conformant)  "containerable" how is it valuable to the consumer?
Is it only valuable if ALL extensions are capable of being containerized?
Are we talking about containerization at a Zowe component level OR something else (i.e. all Zowe Desktop Apps are containerized)

Who is building the containers?  The users?  (i.e. they create containers that include various Zowe CLI plug-ins and Zowe Desktop apps for appropriate "roles" within their organization).

Action Item:  Mike D will speak with Mark for more details.

**Comment by RASakach** [comment]
We will bring the proposal to close this out to TSC, given we have documentation for the packaging and containerization requirements

**Comment by balhar-jakub** [comment]
Closing as discussed and agreed there is nothing else to do.
