### ISSUE TITLE
ZAC Repo Mgmt & Community Access

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1489]
ZAC members are unable to approve / merge pull requests against the ZAC repo and need help in understanding and restructuring access.

Ideally access should be similar to the Project Management folder
[community](https://github.com/zowe/community)/[Project Management](https://github.com/zowe/community/tree/master/Project%20Management)/PI Planning/

ZAC is looking for assistance in executing on this request.

**Comment by MarkAckert** [comment]
The access rules for the ZAC repo have been updated to mirror the access rules in the community repo.

**Comment by balhar-jakub** [comment]
I believe that with all the changes that happened around this topic this issue is done now.
