### ISSUE TITLE
Joint Innovation Week

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1556]
Thank you for taking the time to submit a topic for the TSC discussion.s

**Comment by balhar-jakub** [comment]
Discussed at TSC with the resolution that we are interested and the ZAC will try to find support inside the companies. 

The proposal is to discuss on the architecture call (26th of July) the ideas and proposals on what to do and then
to showcase the created work on architecture call (9th of August)

**Comment by balhar-jakub** [comment]
It would be great if it was public enough so that the extenders/customers are interested and involved in this effort. 

Could we somehow publicize the opportunity?

**Comment by nkocsis** [comment]
Is there anything that John can do ? @jmertic

**Comment by jmertic** [comment]
We could certainly promote through the project channels and do a blog post with the support of this group. Is there a meeting Mae and I could come to where this is being discussed?

**Comment by nkocsis** [comment]
@balhar-jakub @RASakach Jakub/Rose, what do you think. I think the next opportunity would be on the ZAC call on Tuesday 07/12
