### ISSUE TITLE
New Zowe conformance criteria suggestion - Compatibility/breaking changes

### ISSUE THREAD

**Issue by plavjanik** [zowe/community#1558]
I am not sure what is the right way how to suggest new conformance criteria. This repository seems like the best one for this.

### Situation

While working on the breaking changes policy (https://github.com/zowe/community/pull/1499), we have realized that our conformance criteria do not cover breaking changes. But the Zowe users usually expect that new versions of the plug-ins will be compatible with the existing ones. Some issues were noticed in the plug-ins of a vendor and are not difficult to be made accidentally.

### Suggestion

Squads with conformance criteria should factor in criteria about breaking changes into their conformance criteria. The criteria should be done in accordance with #1499.

**Comment by balhar-jakub** [comment]
The compatibility of extensions with each other is outside the scope of the Zowe project. We cannot ask vendors to validate compatibility with extensions, regardless of whether they are from the same or from different vendors.

Therefore, we will not add this requirement to the conformance program and leave it to the vendors to solve internally for their own extensions and to discuss specific extensions across vendors.
