### ISSUE TITLE
Spike: Prepare plan on how to approach the topic. 

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1569]
Advance E&C efforts to a documented progression PLAN

- Includes research on viable "types" of learning and testing i.e. no labs / no technical backend required? simulation? real z machine? anticipated costs
- Include a very basic, proposed curriculum with maintenance model
- TSC approval of plan

**Comment by RASakach** [comment]
Next Steps:
- Brainstorm ways to move this topic forward and deliver on the PI commitment

**Comment by jmertic** [comment]
We have a full training team we could bring in to brainstorm with the group if there is interest. I think @RASakach they spoke with the onboarding squad before; they really like to work collaboratively with groups to help them form ideas and directions.

**Comment by jmertic** [comment]
Looks good - I'm going to try to attend as I'm keen on seeing this get moving.

**Comment by RASakach** [comment]
Initial plan drafted & reviewed with TSC (and Linux Foundation)
Next steps:  Begin Pilot and introduce 1 simple course
