### ISSUE TITLE
Secure content for the CY22 conferences

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1571]
**Is your feature request related to a problem or limitation? Please describe.**

The goal is to collect the relevant conferences for the Zowe and make sure that there is a Zowe presence.

**Comment by jmertic** [comment]
Please keep @Maemalynn in the loop on these and let her know of any help she can provide

**Comment by RASakach** [comment]
@Maemalynn FYI:  we are using this Gsheet for tracking: [](https://docs.google.com/spreadsheets/d/1Aa6etnp9zye2q-YvcopBeNCIJwsH6k9JIFtwUpS4dWc/edit#gid=1268820395
)

**Comment by jmertic** [comment]
Thanks - we should get these integrated together. Can we make this happen?

**Comment by RASakach** [comment]
Conference schedule seems complete for CY22
