### ISSUE TITLE
Extender Mailing List

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1573]
Make sure that the extenders list exists and is used. 
The information also needs to become part of the zowe.org

**Comment by RASakach** [comment]
@jmertic - as mentioned during a prior Onboarding Squad call, we would like to create a Group / Group Email Address for Zowe-extender similar to zowe-user:  https://lists.openmainframeproject.org/g/zowe-user

One thought we had was to repurpose the ZLC Group.  Before doing that we have questions - could you please help us with these?  Once we have the response we will socialize a plan to proceed with the ZAC members.

1.  Is it possible to rename the "zowe zlc" group to "zowe extender"?
2.  If no, is there any way to port over the existing members of the "zowe-zlc" group to the "zowe-extender" group?
3.  If we are not able to repurpose "zowe zlc" and the ZAC agrees it is no longer needed, can we delete it?

**Comment by jmertic** [comment]
Easy one - renamed the list now to https://lists.openmainframeproject.org/g/zowe-extender

I would like to rename/repurpose the zowe-zlc-private list to zowe-tsc-private. Right now it's just used for submitting the release upload terms and sending the monthly security scans; both of which seem more appropriate for that list. Let me know if that seems reasonable to everyone.

**Comment by RASakach** [comment]
@jmertic we agreed at the recent ZAC call to rename/repurpose this list.  Please go forward.

**Comment by RASakach** [comment]
Let's revisit this next meeting and determine if we can close it out.
