### ISSUE TITLE
Refresh the User mailing list

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1574]
Make sure that the the user mailing list is used at least for the release related announcements.

**Comment by RASakach** [comment]
Action item: 
- add an item to the ANNOUNCEMENTS to give consumers an opportunity to join our mailing list

**Comment by RASakach** [comment]
Pull request created:  https://github.com/zowe/zowe.github.io/pull/821
[need someone to review to ensure the changes are correct]
