### ISSUE TITLE
Create a question of a month for the zowe.org page

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1576]

**Comment by jmertic** [comment]
Not sure of the full context of this one but seems interesting. Can you add some context?

**Comment by balhar-jakub** [comment]
The main problem we are trying to resolve within Zowe is to get more feedback from the users. We were trying to provide a twice a year a questionnaire, but we have very few answers, partly due to the length of it, but also it seems that we weren't reaching the right people. 

As we have around 7k people monthly looking at zowe.org based on the statistics, we were looking for a way to integrate single question that will be easy to answer and that will help us understand our users better. 

If we had paid version of SurveyMonkey we could just integrate the question from SurveyMonkey there.

**Comment by jmertic** [comment]
Yes - makes sense for sure.

I wonder if being a bit more proactive in engaging could help; often I see communities sit back and wait for responses to come in. Some ideas...

- We have a community forum ( community.openmainframeproject.org ) you could use for a more interactive version of this "question of the week". That would at least keep the feedback more open and lighter weight, and could easily be promoted via social.
- Maybe a "tell us your Zowe story, get a prize" campaign, where you could give out t-shirts or something like that for folks that do start asking more questions to help reward them and incentivize others.
- Or even on the bug reports - find users that are submitted tons of good ones and publically recognize them

I think the big thing is - people need to find a reason on why they should give you feedback. How does it help them? Happy to brainstorm here.

**Comment by RASakach** [comment]
Action item:  research possibilities of integrating Survey Monkey in with a "Question of the month"

Discussion:
How do we plan to use this Question of the month?

Where should we place it?
- start at the landing page

Showing the data:
- display the results of current (as it is happening)?
- consider display the results of the prior month survey
- display the results (in-progress) after you vote

Backlog of survey questions is here:  [Rose will insert the box link here]
- First survey question:  Do you plan to use Zowe V2 by or before 12/31/2022?  (YES/NO)
  https://www.surveymonkey.com/r/zowev2plans

**Comment by RASakach** [comment]
Question of the month backlog is here:  https://ibm.box.com/s/o1rcn557z7vcawewasc98qbe8mv90xtq

We are in the process of preparing a question for Zowe Chat.

**Comment by RASakach** [comment]
PRIOR TO CLOSING:

(1) Respond to Community feedback on improving the zowe.org rendering of the Question-of-the-month
(2)  Post a link to where response details are stored:  [https://ibm.box.com/s/716fnxmdnup0mfrfs0a2tfpynerpw17e](url)
