### ISSUE TITLE
ZOWE Day at SHARE Columbus

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1578]
SHARE has approved a request from the Zowe Community to host 4 Zowe sessions in row on Monday Aug 22.  We refer to this as Zowe Day.  The sessions run from 9:45am - 4:15pm. In-person and live steamed

Expect 100-200 attendees

Schedule:

- 9:45 AM - 10:45 AM - Zowe Day Part 1: Overview of Zowe, Today, and Beyond
- 11:00 AM - 12:00 PM - Zowe Day Part 2: How Zowe Helps DevOps 
- 1:45 PM - 2:45 PM - Zowe Day Part 3: Deploy and Configure Zowe - Security Updates 
- 3:15 PM - 4:15 PM - Zowe Day Part 4: How to Extend Zowe

Other needs:

- Swag 
   - Stickers - Open Mainframe Project + Zowe, 300 of each - John/Deb
   - T-shirts - First 50 ( all L/XLs ) - Deb
- Promotion
   - Add to events page - Mae
   - Social - Mae
   - Event Snackable - Mae
   - Dedicated Blog post ( Zowe Day + all sessions ) - Mae
   - Newsletter mention - John/Mae
   - Mention in next Techstrong TV session - Mae
   - Slide in presenter decks to promote Open Mainframe Summit - Mae/Domenico/Rose
   - Wrap up blog post - Rose/Domenico
   - Vendor put note about Zowe Day on registration bag inserts - IBM/Broadcom/Rocket
- Live tweeting - Mae ( waiting for pass from SHARE )

Other opportunities:
- BOF
- Other technical track sessions.

**Comment by jmertic** [comment]
Sure - can you get us a budget for the lunch?

For swag, I think I have a bunch of stickers ( will double check ). For the bigger items, I'd recommend code for people to purchase these through the Open Mainframe Project Store ( store.openmainframeproject.org ) instead, just to make things easier. Let me know if you'd agree/

**Comment by RASakach** [comment]
@jmertic as mentioned during the ZAC call earlier - we have not been approved to offer a "Lunch-and-Learn" session by the SHARE organization.  We will keep you posted if/when that changes.

@Domenico-DAlterio 

Latest version of the ABSTRACT for Zowe Day:

Zowe Day offers 4 information-packed educational sessions designed to be consumable regardless of experience level or role.

**Session 1** kicks off the day with a general Zowe overview and is recommended for all, but a must for those new to Zowe.  If your organization is interested in enabling mainframe DevOps - don’t miss _Session 2_ where the focus on Zowe Command Line Interface (CLI) Use Cases will demonstrate its applicability. System Administrators responsible for the install and configuration of Zowe will want to reserve a seat for _Session 3_ where the experts will offer step-by-step best practices with guidance on security options and additional recommendations for consideration. We will conclude the day with a focus on the development community interested in extending Zowe. _Session 4_ will showcase the programmable interfaces and their associated Zowe Conformance programs. Attend just one or as many as you like - this is a great opportunity to meet and learn from the experts! Join our vibrant community and help shape the future of Zowe.

**Comment by Domenico-DAlterio** [comment]
@RASakach I submitted the abstract agreed and I asked for the possibility to have a Birds of a Feather session with the abstract agreed via slack, copied below to kee track of it.

"Zowe Birds of a Feather – INCUBATORS. How does an idea become a part of the most successful Open Source Project for mainframe? It’s accepted as a Zowe Incubator! Learn about active incubator projects and the Zowe code contribution process. Join the discussion and share your ideas for Zowe futures and comment on ideas under consideration."

**Comment by Domenico-DAlterio** [comment]
Birds of a Feather sessions will be offered Wednesday and Thursday evening after session times. 
If that works, we will be able to submit a Birds of a Feather Request form starting August 18th. The link to the request form will be available on the [Speaker Resource](https://urldefense.proofpoint.com/v2/url?u=https-3A__www.share.org_Events_SHARE-2DColumbus-2D2022_Speaker-2DResources&d=DwMGaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=dHnDj7q2tr3SWK0xqlP9jz9nRqG0mg1ZVrSVANbVpAA&m=bAZTg5M6WhmYrGBQHWDfLiuQS2dy7xZnLIbwosbdo6iPa0Ugqpvf58GI7I3GOYQZ&s=UWDN-zy9YpYgUW8_DoZ_kRYoqRUPKDKufuxQP-W5cBI&e=) page.

**Comment by pdubz3** [comment]
(Domenico - June 10) Proposal is accepted, still waiting to determine who the speakers will be.  Will be able to determine that after we know which sessions have been accepted.

**Comment by RASakach** [comment]
Confirm with @1000TurquoisePogs (Sean Grady) he will be attending and willing to present at Zowe Day

**Comment by RASakach** [comment]
@1000TurquoisePogs, @Joe-Winchester @MikeBauerCA  FYI:  The SHARE Zowe Day PPTs have been started.  I am working on completing SESSION 1, please let me know who can take the lead on SESSION 2, 3, and 4.  Assuming Joe will take 2, Sean will take 3, and Mike B will take 4.  Here's the link to the folder:  https://ibm.box.com/s/dmkrsthgbokrfwv5akd8br69kewvh9hi

**Comment by RASakach** [comment]
Retrospectively:  
Live Stream showed speaker & table:  good
The visual / presentation was not ideal but readable
We had no Zowe swag for Zowe day
Onsite attendance was reasonable / we had a steady group on the live stream
Many folks were not aware of Zowe Day despite OMP / Community Social and SHARE's Email
Lots of parallel tracks sort of encouraged folks to skip Zowe Day because it would be available as a replay

We need to start planning for SHARE in Atlanta / consider asking for the same thing.

**Comment by jmertic** [comment]
Good insight @RASakach - a few thoughts...

- Parallel tracks will be a challenge when you have an event-in-an-event like this.
- Swag, presentations, and awareness feels like an area where having stronger event operations might help. There are so many nuances to doing an event like this that we might want to consider stronger staff support.
- It might make sense to start conversations with SHARE now versus later - something we could potentially help with. 

Great event overall!
