### ISSUE TITLE
Question: How should the committers files be maintained?

### ISSUE THREAD

**Issue by zFernand0** [zowe/community#1585]
Now that we have individual contributors/committers/admins, should we remove these files below ?
[COMMITTERS.md](https://github.com/zowe/community/blob/master/COMMITTERS.md)
[COMMITTERS.csv](https://github.com/zowe/community/blob/master/COMMITTERS.csv)

If we still want to keep them...
- [COMMITTERS.md](https://github.com/zowe/community/blob/master/COMMITTERS.md)
  - Should we link to the individual teams (same as the [API Squad](https://github.com/zowe/community/blob/master/COMMITTERS.md#zowe-api-squad)) ?
- [COMMITTERS.csv](https://github.com/zowe/community/blob/master/COMMITTERS.csv)
  - Can we have a GH workflow to automatically update this `.csv` file based on the individual teams ?

**Comment by jmertic** [comment]
To throw another idea in here, within the LFX Project Control Center we have a way to maintain groups of people that I think might be interesting to pursue. I could show this in a future meeting if there is interest.

**Comment by balhar-jakub** [comment]
There is issue to automate the sync to the .csv file - https://github.com/zowe/community/issues/1727
The .md file is intended as signpost linking to all the contributors and committers teams for all the squads across the project. The actual people shouldn't be there and as such the maintenance burden happens only when new squad is added or old disbanded.
