### ISSUE TITLE
Change Description on Conformance Badge

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1592]
Broadcom Product Manager is requesting that OMP make a change to the following  **API Mediation Layer Zowe V1 Conformance Badge**:
- Database Management Solutions for Db2 for z/OS

Existing description reads:  RESTful APIs for Db2 for z/OS data access and management
NEW description requested:  Provides Db2 for z/OS administration, performance monitoring, and DevOps capabilities using modern API and CLI interfaces

@jmertic can you let us know how to initiate this change?

**Comment by trode05** [comment]
@RASakach Thank you for opening the issue, this is exactly what I was asking for.
@jmertic Please initiate the change.

**Comment by jmertic** [comment]
Hi! Please see the process for making changes to the Zowe Conformance listings at https://github.com/openmainframeproject/omp-landscape#corrections.
