### ISSUE TITLE
Product Teams Waiting on V2 Conformance Confirmation

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1593]
I have received many inquiries on the status of their respective V2 Conformance Applications.  Since we have no formal process for investigating this with OMP, I have opened this issue as a means to track them and provide a transparent forum for communication.

APPLICANTS WAITING:  Please add a comment, include your name, the name of your extension and the date you submitted the application

**Comment by jmertic** [comment]
Hey - apologizes for all the delays here. Yarille on our team took this over and had some personal issues which delayed getting these processed. We should be caught up now, so please let me know if you see any missing.

Going forward, we are building a better process for processing these in a timely manner. We are thinking that a turnaround of 5 business days should be ok ( let's her spend a day a week processing them all at once )- let me know if you think that is too long and we can adjust.

And regarding "formal process" - please just ask me. I don't bite ;-)
