### ISSUE TITLE
Squad Input for CY22Q3 Roadmap Requirements

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1633]
Instructions:
Each squad copy the template below and add your details in this single issue in the form of a comment:
====================================================================
Squad Name:   

_For EACH problem you are trying to solve, provide the following information:_
(Note:  PLEASE DO NOT list every item you are working on, consolidate them into the LARGER problem you are solving)

Zowe Component:
What problem are you solving?
What are you doing to solve it?
When do you plan to start the work?   
When do you plan to deliver the solution?  

[example provided in the next comment]

**Comment by RASakach** [comment]
**EXAMPLES**   for the CLI Squad

Squad Name:  CLI

Zowe Component:  _Zowe CLI_
What problem are you solving?  _Some customers are not able to install the SCS for their credentials management_
What are you doing to solve it?  _Provide customers with an alternative that facilitates storing credentials in-memory_
When do you plan to start the work?  _CY22Q3_
When do you plan to deliver the solution?  _CY22Q4_

Zowe Component:  Zowe CLI  
What problem are you solving?   _Customers are asking for full Zowe CLI Script Samples_
What are you doing to solve it?   _Publish pre-written sample scripts in the Zowe CLI Web help_
When do you plan to start the work?  _CY22Q4_
When do you plan to deliver the solution?  _CY23Q1_

Zowe Component:  _Zowe Client SDK_
What problem are you solving?  _Customers like to program in PHP (Web Interface Language)_
What are you doing to solve it?  _Provide customers with this programming language option in Zowe's Client SDK_
When do you plan to start the work?  _CY23Q2_
When do you plan to deliver the solution?  _CY24Q1__

**Comment by balhar-jakub** [comment]
I've added the information for API ML Squad in the objectives document to the bottom 
https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/22PI3%20Planning/Zowe%20API%20ML%20Squad%20Objectives.md

**Comment by 1000TurquoisePogs** [comment]
https://app.zenhub.com/workspaces/zlux-core-5ca217c7d74bd07972cb77db/roadmap?invite=true

**Comment by MarkAckert** [comment]
Chat Squad: https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/22PI3%20Planning/Zowe%20Chat%20Squad%20Objectives.md#roadmap-items 

Systems Squad:
https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/22PI3%20Planning/Zowe%20Systems%20Squad%20Objectives.md#roadmap-items

**Comment by JillieBeanSim** [comment]
@RASakach planning doc has been updated https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/22PI3%20Planning/Zowe%20Explorer%20Objectives.md#roadmap

**Comment by RASakach** [comment]
The Zowe Roadmap will be introduced to the Community at the 9/28 Quarterly Webinar.
Draft roadmap is here:  

The Roadmap should be posted at zowe.org (off the landing page, not on it)
We need to provide consumers with a means to comment / ask questions about it
We need to update it quarterly and refresh it
Each quarterly webinar will contain a roadmap segment
Do we want to record a series of Roadmap snippets?

**Comment by RASakach** [comment]
Onboarding has collected preliminary roadmap information during 22PI3
We have produced a template for ongoing PI plannings:
