### ISSUE TITLE
Develop Zowe Committers List

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#164]
The community needs a way to manage who has committer (read/write) access to repos in the community. A committer who has made a contribution within the last 6 months of a community vote will be eligible to cast a binding vote (i.e. ZLC elections). 

Each committer who wants to cast a vote must commit to the .md file and list the email address they want to receive their ballot to. 
https://github.com/zowe/community/blob/Committer-List/Zowe%20Committers.md

This is common practice in other open source communities such as CNCF:  https://github.com/cncf/toc/blob/master/CONTRIBUTORS.md

It is recommended that each person commit their name and email address to this file and the DCO would cover the data privacy signoff as part of clause d.: 
 (d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

**Comment by dan-jast** [comment]
Dan Jast
Daniel.Jast@ibm.com
917-763-6207(Work Mobile)

**Comment by Tbr00ksy** [comment]
@dan-jast I actually need you to go in to the Committer List branch, edit the Committer.md and add your info to the list. You will be asked to do a sign-off using DCO.

DCO: https://github.com/zowe/zlc/tree/master/scripts/dco

Committer branch and .md: https://github.com/zowe/community/blob/Committer-List/Zowe%20Committers.md

**Comment by Joe-Winchester** [comment]
@Tbr00ksy - can you add Steve Horsman to the committer list please ?  cc: @stevenhorsman
