### ISSUE TITLE
Conference Schedule for CY23

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1667]
Make sure that we are aware of Zowe related content for the CY23 and that we are present on the key conferences. 

Store the information about the conferences and talks here:
  https://docs.google.com/spreadsheets/d/1Aa6etnp9zye2q-YvcopBeNCIJwsH6k9JIFtwUpS4dWc/edit#gid=1268820395

**Comment by RASakach** [comment]
Link has been updated, all sessions are listed
