### ISSUE TITLE
Eureka failed to endpoint

### ISSUE THREAD

**Issue by GilPen** [zowe/community#1683]
**Describe the bug**

Usually after few minutes Eureka accepts the sessions
But now the message appears all the time : (_zsf.apiml,EurekaClient.js:710) Eureka request failed to endpoint

Regardind to the log, I suppose a certificate problem. So I generate new cetificates with the the script zowe-setup-certificate.sh and the zowe-setup-certificate.env file. The result of the operation was "successfull". After restart ZOWE the problem occurs again.

**Steps to Reproduce**

1.  Try to connect to ZLUX

**Expected behavior**
I would like to connect to ZLUX

**Logs**

Everytime I try to connect ZLUX, these messages appear in the log 

2022-08-19 07:00:08.444 <ZWED:189> ZWESVUS INFO (_zsf.auth,webauth.js:364) ZWED0070I - User=undefined (org.zowe.zlux.auth.trivial): Session authenticate successful. Plugin response: é"success":trueè
(node:189) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
 Error: unable to get issuer certificate                    
     at TLSSocket.onConnectSecure (_tls_wrap.js:1506:34)    
     at TLSSocket.emit (events.js:315:20)                   
     at TLSSocket._finishInit (_tls_wrap.js:948:8)          
     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) é 
   code: 'UNABLE_TO_GET_ISSUER_CERT'                        
 è               

**Details**

z/OSMF 2.4.0/wlp-1.0.50.cl210320210309-1101
ZOWE version 1.27.1
nodejs version v12.18.0
java version J8.0_64

Regards
Gilles Peniguel

**Comment by timgerstel** [comment]
@GilPen could you post or upload the output zowe-setup-certificate.sh please?

**Comment by GilPen** [comment]
Hello 

The log is in the attach files.

Regards
Gilles 
[zowe-setup-certificates-2022-08-30-08-40-34.log](https://github.com/zowe/community/files/9450503/zowe-setup-certificates-2022-08-30-08-40-34.log)
