### ISSUE TITLE
A tool proposal to monitor label hygiene

### ISSUE THREAD

**Issue by anton-brezina** [zowe/community#1688]
We'd like to discuss a visualisation tool https://9-volt.github.io/bug-life/?repo=zowe/api-layer which we are currently considering and evaluating in the api-layer repository.
The aim is to not have any long living labels and keep an eye on issues which are growing old in the repository.

**Comment by boris-bc** [comment]
The value that BugLife may provide is about backlog management. The label usage is only one side of the benefits. The final goal is to be able to identify issues that are ignored or lost in the noise and attend them. The final result should be a backlog with very few long standing issues and with a manageable amount of open labels.

Below is a comparison of the zowe/api-layer backlog with the mozilla/application-services. From the first glance, several trends could be noticed:
api-layer: https://9-volt.github.io/bug-life/?repo=zowe/api-layer
- number of labels is on the high side
- number of open enhancements issues is growing
- number of open technical excellence issues is growing
mozilla/application-services: https://9-volt.github.io/bug-life/?repo=mozilla/application-services
- more manageable usage of labels
- number of issues with no label is increasing
- many unlabeled issues were closed at a certain point (probably without solution)

<img width="801" alt="image" src="https://user-images.githubusercontent.com/63061368/188587931-3e7169d4-75be-44b5-a2d7-e6ec364491ba.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/63061368/188588423-23a9d472-30c1-4546-b254-b8c7bb3434f4.png">


We would like to propose for Zowe to host a modified version of BugLife where the graph legend does not show labels with zero opened issues. We would also like to propose the regular use of BugLife to audit Zowe repositories and plan corresponding actions to avoid having long-term open issues as we believe this would improve the interactions with the community.
<img width="220" alt="image" src="https://user-images.githubusercontent.com/63061368/188588873-ecb4044e-f633-4076-9cdf-ea851cd60bc1.png">

**Comment by boris-bc** [comment]
It was agreed to use this tool as is for the next squad readouts during the PI planning.

**Comment by balhar-jakub** [comment]
We will integrate the results in TSC updates and we will evaluate latest in a year on what it brought to us.
