### ISSUE TITLE
Zowe.org Backlog Links (Waffle)

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#169]
**Describe the bug**
Waffle has been sunset but the links of Zowe.org and GitHub all still point to Waffle, leading to an error message.

**Steps to Reproduce**

1. Navigate to Contribute page https://zowe.org/contribute/
2. Scroll down to Contribute with GitHub https://waffle.io/zowe/community
3. Also need to update this page: https://github.com/zowe/community/blob/master/README.md

**Expected behavior**
There is a new ZenHub Workspaces feature that might be able to replace what the community previously had with Waffle. 
https://www.zenhub.com/workspaces

It would be ideal that we implement ZenHub Workspaces and then update the Zowe.org and git hub locations with the new ZenHub workspaces link.

**Comment by jackjia-ibm** [comment]
@Tbr00ksy in the Contribute page, there are waffle links in the feature groups. For example, API Mediation Layer has a link to `Waffle (Backlog): https://waffle.io/zowe/api-layer`. Do you know if we have 1-to-1 match on the Zenhub for similar links?

**Comment by Tbr00ksy** [comment]
I believe @MarkAckert had originally set up the waffle boards to pull in all the  issues from the repos associated with that squad? 

For example, with API ML the waffle board pulled in the issues from:
- https://github.com/zowe/api-layer
- https://github.com/zowe/explorer-api-common
- https://github.com/zowe/data-sets
- https://github.com/zowe/jobs

Looks like he has also been able to create the zenhub board to also map to those multiple repos:
<img width="1112" alt="Screen Shot 2019-07-03 at 1 05 57 PM" src="https://user-images.githubusercontent.com/36775778/60611038-572f9400-9d93-11e9-8f93-fcaa100eeb8d.png">

Link to API ML Zenhub: https://github.com/zowe/api-layer#workspaces/api-layer-5c7e802bcfa1d10365963ef7/board?repos=155383451,162463317,157888365,157852345
or looks like we can use (only if you have the plug-in installed): https://github.com/zowe/api-layer#zenhub

**Comment by jackjia-ibm** [comment]
Thanks @Tbr00ksy for the info, I've updated all waffle links to zenhub links similar to https://app.zenhub.com/workspaces/community-5c93e02fa70b456d35b8f0ed, so it works without plugin. Please let me know if there are issues.

**Comment by Tbr00ksy** [comment]
Thank you @jackjia-ibm website looks great.
