### ISSUE TITLE
Zowe Training:  Publish Pilot for feedback

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1720]
Next steps in Zowe Education Curriculum:

- Introduce a single, pilot education course

- Keep technology requirements simple (i.e. minimal to zero z/OS requirements)
Will we need mock-ups?

- Pilot the course, host retrospective for next steps

Starting:
- Write out the tasks
- Run the tasks past an Intern to confirm all steps are there
- Examine the time-to-completion (15 - 20 hours optimal for non-managers)
- Clearly define the problem the technology is solving
- Include, what needs to happen (when all goes well), include TROUBLE-SHOOTING 
- Chapters s/b ~ 45 minutes
- Labs s/b ~ 45 minutes
- Each chapter:  highlight 5 most important things to know/learn and associate facts with them

**Comment by RASakach** [comment]
We have a working draft for API-ML 101
The draft has been shared with OMP for feedback

**Comment by jmertic** [comment]
This looks good to me - I will share with Tim on LF Training via email.

**Comment by balhar-jakub** [comment]
This is the link: https://github.com/zowe/community/tree/tsc/education/pilot/Education/Zowe101ApiUsers

**Comment by RASakach** [comment]
Next steps given the LF feedback from the 2/17 meeting:
- Obtain a "best practice" sample training course from LF
- Make appropriate adjustments / review with LF
- Proceed to build out the first "Pilot" course (API-ML)

**Comment by jmertic** [comment]
Good progress! Any sense of timing on these next steps?

**Comment by RASakach** [comment]
We have an opportunity to partner with Interskill
Next steps:
(1) Schedule a checkpoint with Interskill to review our current state (we will use the OB meeting for this session)
(2) Determine next set of deliverables

**Comment by RASakach** [comment]
Latest information is located here: https://github.com/zowe/community/tree/tsc/education/pilot/Education

**Comment by RASakach** [comment]
Next steps:  @RASakach to schedule a meeting with Interskill to launch this effort
Expectation:
- Review our current plan 
- Determine what they may require to move it forward OR discuss an alternative

**Comment by RASakach** [comment]
@RASakach met with Darren S (Interskill) in June.  Darren felt focusing on Install & Config (pain-point areas) made sense - we need to determine when and how to engage Interskill in this effort.

**Comment by RASakach** [comment]
@RASakach will be scheduling a call with Darren to kick off this new effort.

**Comment by RASakach** [comment]
Target 1st week of August for introductory call with Interskill and Zowe members

**Comment by RASakach** [comment]
Onboarding agreed to partner with Interskill for Zowe training.  Please follow this new issue: https://github.com/zowe/community/issues/2055 for progress.
