### ISSUE TITLE
22PI4 Zowe Roadmap Maintenance & next steps

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1752]
Revise and deliver the most current version of the Zowe Roadmap

(1) Ensure squads have included their latest rev of their roadmap
(2) Update the existing template with the latest revisions
(3) Enable the "consumer" self-service mechanism (make the roadmap available at zowe.org)

**Comment by RASakach** [comment]
CY22Q4 roadmap has been saved here:  https://ibm.box.com/s/osxrsj1nz3pfhpz5k40mex3yjtke1h98

@balhar-jakub :  I'm looking for assistance in copying over the PDF version of the roadmap to the designated github REPO: https://github.com/zowe/zowe.github.io  I'm not sure which area within that repo is appropriate.  Can you please help?  Once the PDF is in the repo, I can update the announcements to point to it.

**Comment by balhar-jakub** [comment]
I've prepared PR with the new directory for roadmaps - https://github.com/zowe/zowe.github.io/pull/692
