### ISSUE TITLE
Restore COMMITTERS.csv

### ISSUE THREAD

**Issue by jmertic** [zowe/community#1769]
Hi!

I see this PR removed the COMMITTERS.csv file...

https://github.com/zowe/community/pull/1728

We need to have a machine readable file for committers in order to process Committer badges. The COMMITTERS.md file isn't sufficent for this.

**Comment by balhar-jakub** [comment]
That's a good point, can you please share what exactly do you need? The current one doesn't reflect reality in any way and we are looking to create automation for generating the information from the github teams.

**Comment by jmertic** [comment]
If you look at the COMMITTERS.csv from before, if you could replicate that exactly it would be amazing.

I'm also trying to see how we can connect this with LFX Project Control Center where there is a space for maintaining committer lists as well.

**Comment by balhar-jakub** [comment]
Ok, I will keep this as requirement for the work being done for handling committers.

**Comment by balhar-jakub** [comment]
I am closing the issue as the file was restored and we have an issue for automation to sync the data from the Github Teams.
