### ISSUE TITLE
Install ZOWE 2.2.0

### ISSUE THREAD

**Issue by GilPen** [zowe/community#1773]
Hello

I'm trying to install the version 2.2.0. The installation seems to be good because I can see the API Mediation Layer page on a web browser and API CATALOG as well. But I can't connect to ZLUX page. I think it's  a cerificate problem.

I ran the script "zwe init certificate -c ./zowe1.yaml --update-config" successfully and certificates have been generated in the directory "/usr/lpp/zowe/keystore". I added the update lines to my zowe.yaml configuration I used to start zowe.

When I start ZOWE, it seems ZOWE doesn't find a file /usr/lpp/zowe/keystore/local_ca/local_ca.cer. I supposed this file should be generate by the srcipt but it's not right.

I used the zowe1.yaml to generate the certificates
I use zowe.yaml to start the ZWESLSTC ZOWE STC
The appserver server is the log of the STC ZOWE starting.

Regards
Gilles Peniguel
[appServer-2022-08-17-15-45.log](https://github.com/zowe/api-layer/files/9368247/appServer-2022-08-17-15-45.log)
[zowe.yaml.txt](https://github.com/zowe/api-layer/files/9368270/zowe.yaml.txt)
[zowe1.yaml.txt](https://github.com/zowe/api-layer/files/9368271/zowe1.yaml.txt)

**Comment by 1000TurquoisePogs** [comment]
> Hello,
> 
> I upgrade in 2.4 version and now new problems occur :
> 
> /usr/lpp/zowe/bin/zwe internal start prepare --config "FILE(/usr/lpp/zowe/instance/zowe.yaml)" --ha-instance sysa InternalError: invalid opcode (op=0,pc=0)
> 
> ZWESVUS ERROR ZWEL0029E start component list is empty
> 
> Regards Gilles Peniguel

This is very likely because I see a `@include: "/usr/lpp/zowe/bin/zowe1.yaml"` line in your YAML.
Zowe using configmgr does not support this. There's another way to group together multiple files, as described in https://docs.zowe.org/stable/user-guide/configmgr-using#splitting-configuration-into-multiple-files

**Comment by 1000TurquoisePogs** [comment]
> Hello
> 
> I regenerate with the install-app.sh so-auth plugin and clear the browser history.
> 
> Now if I put the URL https://sysa.dns21.socgen:8542/datasetMetadata/name/ZAS.**.INSTALL?detail=true&listMembers=true&addQualifiers=true in the browser
> 
> I get a message in the ZOWE sysout :
> 
> 022-09-01 13:44:52.509 ZWEADS1:DiscoveryClient-CacheRefreshExecutor-0:33554598 ZWESVUS INFO (o.z.a.p.g.GatewayInstanceInitializer) GatewayInstanceInitializer has been initialized with Gateway instance on url: https://sysa.dns21.socgen:7554 BPXTLS failed: rc=-1, return code=139, reason code=0x0be802af Error: service has no impersonation; make sure process user has sufficient authority: z/OS: program control flag must be set, UPDATE access to BPX.SERVER and BPX.DAEMON SAF resources is required Other platforms: impersonation is not supported
> 
> $ bpxmtext 0be802af BPXPTSEC 01/05/18 JREnvDirty: The specified function is not supported in an address space where a load was done that is not program controlled.
> 
> Action: Make sure that programs being loaded into this address space are defined as program controlled.
> 
> So I suppose an attrib +p misses an a file.
> 
> I verified the STC owner has BPX.SERVER and BPX.DAEMON UPDATE flag.
> 
> Regards Gilles

Don't run install-app.sh in v2, you should not be using any zowe scripts other than `zwe`. `zwe` calls other scripts as needed, but if you use them directly you may break Zowe.

Everything that needs `+p` should have it upon a fresh install or when using `zwe components install`. Or, it will warn if it didnt have the permission necessary to do that.
If you are lacking `+p`, you can try setting it on /components/zss/bin/zssServer and /components/zss/bin/zssServer64
When running, it may then give you errors if plugins of zss also are missing `+p`, but it would tell you the path of the files.

**Comment by GilPen** [comment]
Hello 

To summarize, the version 2.2.0 didn't work for me and you told me to upgrade to 2.4.0. 

So I don't use install-app.sh anymore but run the new script "zwe".

Once 2.4.0 version installation is finished, I tried to run the STC and got the error message 
"InternalError: invalid opcode (op=0, pc=0)"

And I also got the messageID ZWEL0029E which doesn't exist in any documentation.

So I tried to run the command with the root user and got the same error
$ su                                                                                                                    
£ /usr/lpp/zowe/bin/zwe internal start prepare --config "FILE(/usr/lpp/zowe/instance/zowe.yaml)" --ha-instance sysa 2>&1 
InternalError: invalid opcode (op=0, pc=0) 


Regards
Gilles Peniguel

**Comment by 1000TurquoisePogs** [comment]
Can you edit your zowe.yaml to turn `useConfigmgr: true` to `useConfigmgr: false` and see if Zowe is working?
The error message you see is coming from the configmgr code, but we cannot reproduce it so we'd like to know more about your environment.

Can you post your latest zowe.yaml & also run `zwe support` to verify environment info?
Note: when using `zwe support`, as well as when using `zwe` with `useConfigmgr: false`, `--config` should just be a simple `/path/to/a/file` rather than being wrapped with `FILE()`. The `FILE()` syntax only works with `useConfigmgr: true`, which is the new default but just letting you know for this troubleshooting.

**Comment by GilPen** [comment]
[zowe_yaml.txt](https://github.com/zowe/community/files/10073381/zowe_yaml.txt)
[ZWESLSTC.D231122.txt](https://github.com/zowe/community/files/10073382/ZWESLSTC.D231122.txt)

**Comment by GilPen** [comment]
[zwe_support.txt](https://github.com/zowe/community/files/10073427/zwe_support.txt)

Hello

Thank you for your help. I just sent you the "zwe support" command result, the STC sysout and the zowe.yaml

It seems I have an error in the yaml  but I build the yaml with the sample:

* Output:                                                                           
    Error: error reading input file: Map keys must be unique; "enabled" is repeated   
  * Output:                                                                          
    Error: error reading input file: Map keys must be unique; "enabled" is repeated  

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
[zwe_support.txt](https://github.com/zowe/community/files/10074630/zwe_support.txt)
[zowe_yaml.txt](https://github.com/zowe/community/files/10074633/zowe_yaml.txt)
Hello 

Thank you for the command 'zwe support'. I corrected the errors in the yaml. 

The new zowe.yaml file and 'zwe support' command is in the attached files.

Regards
Gilles Peniguel

[ZWESLSTC.D231122.txt](https://github.com/zowe/community/files/10074665/ZWESLSTC.D231122.txt)

**Comment by GilPen** [comment]
[zwe-support.2022-11-23-11-19-15.pax.gz](https://github.com/zowe/community/files/10074920/zwe-support.2022-11-23-11-19-15.pax.gz)

**Comment by 1000TurquoisePogs** [comment]
Can you run the command `/usr/lpp/zowe/bin/zwe internal get-launch-components --config "FILE(/usr/lpp/zowe/instance/zowe.yaml)" --ha-instance sysa` within a shell to see what it does? It's not clear from the logs, but that is the current command that is not working.
It might be due to your current zowe.yaml.
It looks like you commented out some things that need to be there.
You do need zowe.externalDomains to have at least 1 entry.
You also commented out explorer-mvs and explorer-uss. You an set them to `enabled: false` if you'd like, but don't comment them out. There may be other commented out things that shouldn't be versus the example file here https://github.com/zowe/zowe-install-packaging/blob/v2.x/master/example-zowe.yaml so you should review the differences to try and get the same properties existing.

**Comment by GilPen** [comment]
Hello

Thank you for your answer 

I put the value to explorer-mvs and explorer-uss to false.
And add the DNS value to externalDomains.

The command result is 

£ zwe internal get-launch-components --config "FILE(/usr/lpp/zowe/instance/zowe.yaml)" --ha-instance sysa                           
ERROR: Validation of /usr/lpp/zowe/extensions/api-zaas-utilities/manifest.yaml against schema ttps://zowe.org/schemas/v2/server-com
ponent-manifest found invalid JSON Schema data                                                                                      
ERROR: Validity Exceptions(s) with object at                                                                                        
ERROR:   Validity Exceptions(s) with object at /build                                                                               
ERROR:     type 'string' not permitted at /build/timestamp                                                                          

Regards
Gilles Peniguel

**Comment by GilPen** [comment]
Hello,

Now the yaml is correct. Is it possible to mention the yaml line in error in the job sysout. It would be very useful

Regards
Gilles Peniguel

**Comment by 1000TurquoisePogs** [comment]
There's work going on to make the validation error messages more useful here https://github.com/zowe/zowe-common-c/pull/336 and we'd like to get error lines there too, so look forward to that in a future release.
