### ISSUE TITLE
Zowe Event Management:  Review ZAC Requirements, propose next steps

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1804]
ZAC is looking to move Zowe Event Management forward and are hoping for an architectural review prior to presenting to the TSC to gain approval for an INCUBATOR project.

- Technical ramifications / concerns
- Community concerns (do we have the right skillsets?)
- Best guesstimate timeline for MVP delivery

Goal / Hill Statement is here:  https://ibm.box.com/s/t8kei85e8pnhoplhhtz991hicj0iuf0j
Proposed Diagram is here: https://ibm.box.com/s/qqh419ei97t3l9mhrt1k7weqt73a7ayo
Requirements are here: https://ibm.box.com/s/8b2rxk4z4o4rf2a2apnr7rnhhexlebhu

**Comment by nkocsis** [comment]
Requested people on the Architecture call to review links and we will come back next week to discuss.

**Comment by balhar-jakub** [comment]
I plan to bring the topic to TSC for discussion as well.

**Comment by MarkAckert** [comment]
We will continue this topic on Jan 24 w/ Event Management Working Group in attendance

**Comment by DivergentEuropeans** [comment]
@RASakach I'm getting this Rose

![image](https://user-images.githubusercontent.com/20528015/214315511-22486db6-52a0-4db3-9691-a4eaba500350.png)

**Comment by nkocsis** [comment]
Mark will be acting chair for now to lead this group

**Comment by balhar-jakub** [comment]
The original intention of this issue was resolved by TSC. Closing this issue in favor of https://github.com/zowe/community/issues/1965 which captures requirements for the next stage.
