### ISSUE TITLE
SMF records cut by the Zowe (API Mediation Layer)

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1818]
The current situation is that Zowe when running in HA mode with three nodes generates around 100k SMF records 119. It also generates a similar amount of SMF records 92 due to the nature of the sockets and connection handling in USS. 

This seems to be an issue for some of the customers, as this is just primary usage and doesn't take into account the moment when the automation starts to use the APIs available in the system, which could easily add 100ks more records leading to the large requirement on the SMF space and risks to the production SMF environment. 

@JirkaAichler may know more about the possible solutions, but it seems that it is possible to have a HLASM macro that captures the currently created SMF records and do something with them. 

The z/OS Connect went this way as well and produces separate SMF record (120, 123) that can be directed in a different log stream limiting risk for the production environment.

**Comment by nkocsis** [comment]
Should Zowe have a separate SMF record ? Is there anyone with experience on this topic ? Is there someone from z/OS Connect or TCPIP team that could help ?

**Comment by balhar-jakub** [comment]
This was resolved with the answer being yes, there is going to be separate subrecord within 81 and API ML will use it. There is plan in place. 

As such I am closing the issue.
