### ISSUE TITLE
App Framework Conformance Criteria out-of-date

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1849]
The Zowe V2 Conformance Test Criteria for the App Framework references versions of NODE that are off support and is no longer accurate.  The entry should be revised for new applicants.

The item that needs to be modified is:
Entry #39  in the ENCODING section of Zowe Application Framework Testing Criteria
Zowe V2 Conformance Program Test Evaluation Guide PDF
Currently reads as follows: 
![image](https://user-images.githubusercontent.com/42411859/217894404-54d1f2f9-4855-4fde-bd95-e762ef9f13ec.png)

The requested revision is:
**For z/OS Apps, all application files must be tagged according to their content type**

Note:  We probably want to cross-out the existing and make a notation that Node12 and prior versions are no longer supported and include an effective date (for any conformant extenders who submitted their application prior to this change).

**Comment by RASakach** [comment]
Onboarding has introduced a process for revising / correcting published conformance criteria.
https://vlameli.github.io/Zowe/

Next step:  Review with Web UI Squad Lead and publish

**Comment by jp669844** [comment]
A proposal of the new introduced section:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/55390120/221359767-090ceab1-d4e2-4643-b276-ab865a84383b.png">

**Comment by RASakach** [comment]
The new introduction section has been approved by Zowe TSC, we will update the current testing criteria via the Github process.

**Comment by RASakach** [comment]
@jmertic please review / approve this request:  https://github.com/openmainframeproject/foundation/pull/241 to update the conformance criteria and add the Revision History section.

**Comment by jmertic** [comment]
Updated now.
