### ISSUE TITLE
Innovation - Buddy plugin for Zowe CLI

### ISSUE THREAD

**Issue by pj892031** [zowe/community#1850]
The aim of this initiative is to improve the user experience of a user of Zowe CLI.

Buddy is a plugin for Zowe CLI, which extends the features of the CLI tool. The previous innovation was about adding autocompletion with a short response time.

This part of the innovation focuses on higher integration with the terminal and reusing the context between commands.

The user should write the complete commands with all arguments, even if they are similar or similar. After the treatment of any command is not easy to reuse the response value. All those steps could be improved, save time and improve user experience to the use.

**Archived results:**

- Improvements in auto-completion
- Prompting of missing positional
- Arguments context with history
- Results stored in exported system variables
- Wrapping standard Zowe CLI commands
- Reusing jobid between commands
- Could be extended for other similar values/commands
- Switching the Zowe implementation for daemon mode by Buddy
- Explaining of command (flag –explain)
- History file

**Future task:**

- Finish support of Oh My Fish
- Extending of history (new command for easy use)
- Publishing the version to the public and releasing first version

**Comment by nkocsis** [comment]
It was presented and can be closed
