### ISSUE TITLE
CLI + ZE: Open VSX Registry searching for new funding and governance model

### ISSUE THREAD

**Issue by zFernand0** [zowe/community#1861]
The CLI and ZE squads would like to discuss the following topic:
- Open VSX Registry searching for new funding and governance model

Details: https://blogs.eclipse.org/post/john-kellerman/help-us-sustain-open-vsxorg

### Extensions and downloads

**VSCode Marketplace**:
- Zowe Explorer: 
  - 84.3K (_unique_) | 436K (_total_)
- Zowe Explorer for FTP: 
  - 3.8K (_unique_) | 16K (_total_)
- Zowe Explorer for CICS:
  - 2.1K (_unique_) | 5.1K (_total_)
  
**Open VSX**:
- Zowe Explorer:
  - 4.4K (_total_)
- Zowe Explorer for FTP:
  - 1.4K (_total_)
- Zowe Explorer for CICS:
  - N/A

**Comment by balhar-jakub** [comment]
Closing the issue as the result from our side was to provide the VSX files via artifactory. The request is captured here: https://github.com/zowe/community/issues/1956
