### ISSUE TITLE
Zowe.org redesign next-rev

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1864]
Discussed during 3/21 ZAC call
Revisions include:

1. Add any missing components along with their lifecycle designation and software status, these include:  ZSS, 3 more SDKs
2. Add a link to the Zowe Quarterly Webinars playlist:  [https://www.youtube.com/playlist?list=PL8REpLGaY9QHtnElqPosteBFpITStkAxo](url)
3. Refresh the Zowe video (see required revisions in comments)
4. Enhance the responsive design

**Comment by RASakach** [comment]
During a review of the latest zowe.org overview video, we discovered some security/exposures that we would like to redact from the video.  @samanthasusu @balhar-jakub I will include these discoveries in a direct message to both of you instead of posting here (for the sake of limiting exposure).  Please refer to my slack message.

**Comment by balhar-jakub** [comment]
As a note we should also figure out, where do we put information about the upcoming releases. The users often look for this information.

**Comment by Phoebecdy91** [comment]
@balhar-jakub I just refined the webpage for responsive design. I noticed that you are setting the overall layout margin as 5%. Looks good, we can still keep it. Setting the breakpoints as below:

Screen size | Margin | Columns | Gutter | Tiles in one row
-- | -- | -- | -- | --
**360**-719 px | 5% | 4 | 16px | 2 / 1 / 1
**720**-1023 px | 5% | 8 | 16px | 2 / 1 / 1
**1024**-1439 px | 5% | 12 | 16px | 4 / 3 / 3
**1440**+ px | 5% | 16 | 16px | 4 / 3 / 4

I redesign the layout for each break points, feel free to check: https://www.figma.com/file/nloQ7TDh59YAKKWCXIKw0C/Zowe.org?node-id=301%3A3012&t=pAj9ynhAf5dkPALO-1
Let me know if there is any concern or feedback. 

BTW, for the event tiles, I think it would be good to remove the shadow so it can be consistent with the tiles in the second section that we won't have too many styles. THX!

**Comment by RASakach** [comment]
@balhar-jakub as we agreed on today's (10/5) TSC call, we should add a link to the OMP Zowe Quarterly Update Webinar replays:  https://www.youtube.com/playlist?list=PL8REpLGaY9QHtnElqPosteBFpITStkAxo

**Comment by balhar-jakub** [comment]
Do we have any idea on where we should exactly put it? 
Directly on homepage under the Next release?

**Comment by RASakach** [comment]
Yes, that's what I would recommend - on the home page, beneath the NEXT RELEASE
Something like this:   Did you know?  The Zowe Community hosts a webinar each quarter called _the Zowe Quarterly Update_ .  Watch the replays here:  <link>

**Comment by balhar-jakub** [comment]
The PR with the change is here: https://github.com/zowe/zowe.github.io/pull/866
