### ISSUE TITLE
Determine the format for the remaining CY23 Zowe Quarterly Update Webinars

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1865]
We have uncovered several challenges associated with the Zowe Quarterly Update Webinars:
(1) Often, the registration link does not work
(2) Some attendees submit registrations and do not receive confirmation
(3)  Many attendees are surprised by the ZOOM registration required to attend any Zowe meeting - we need to include instructions on what to do if this happens
(4) It would be more efficient and probably would gain more attendance if we reserved our dates in advance (with OMP) and allowed attendees to register for the calendar year (all 4 webinars) via a single registration link
(5) Do we want to incorporate Zowe System Demo's in all of the Webinars?  (perhaps this should be our August QoM?)

This issue should address all of the above.

**Comment by RASakach** [comment]
(1) Work with OMP to try to improve this issue
(2)  same + on the invite, ask folks to be sure they received confirmation
(3)  On the invite, describe the issue with ZOOM and ask attendees to establish the account
(4)  Content:  Make a proposal during PI planning and discuss as a group + use the statistics from the replays to determine what is resonating.
(5) Use the QoM to ask our consumers if they attend the QW and ask why not if they do not.

**Comment by RASakach** [comment]
Planning Upcoming Zowe Quarterly Updates / let's coordinate getting the registration out there with OMP once these topics are confirmed with Speakers:
Wed Sept 20 at 11:30:  What's new with the Zowe Explorers (VS Code + IntelliJ)
Dec 13 at 11:30:  Zowe's Latest & Greatest Technologies (ZEN & Event Management)

**Comment by RASakach** [comment]
We are leveraging the OMP distribution lists and including registration information in the calendar invites, zowe.org announcements and social media posts.  This has improved our attendance.  For CY24 we will reserve the dates earlier with OMP and see if we can secure registrations in advance.

**Comment by ApacheAde** [comment]
The link for the Squad Template is broken. Advise Fix,
