### ISSUE TITLE
Question-of-the-month for CY23 PI2 Months: May-Jun-Jul

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1903]
Publish Question-of-the-month for the PI2 Months:

- May
- June
- July

**Comment by RASakach** [comment]
Question of the month ideas for May - June - July
May:  Simple, are you using Zowe in Prod
June:  What other open source projects are you interested in or using?
July:  Containers interest

**Comment by balhar-jakub** [comment]
Mentioning here potential questions for further months:

1) Do you plan to install Zowe server side.
 - Yes
 - No
2) If your answer was yes, what is preventing you?
 - I don’t have the permissions to install and am waiting for someone else
 - I need to persuade the security, that the installation is safe
 - We need to expand hardware or software licensing for running of the Zowe
 - I don’t know where to start and the documentation isn’t helpful
 - I am stuck with getting correct certificate that would work with Zowe
 - Something else, please let us know


1) Are you willing to contribute?
 - Yes
 - No
2) If the answer was yes, is there anything preventing you from the contribution?
 - I don’t know where to start
 - I am not sure whether I have the right skills
 - I am not sure what needs to be done in order for my contribution to be accepted
 - Something else, please write what

**Comment by RASakach** [comment]
@balhar-jakub Great ideas!  Keep them coming.  We are tracking the list here:  https://ibm.box.com/s/o1rcn557z7vcawewasc98qbe8mv90xtq

@boris-bc:  we need more details to expand on the "containers" question.  I'm not sure what we want to ask and why.  Guessing we need to understand the amount of interest in Containers so that we know how much effort to put towards that delivery method.  Please let us know if you have suggestions.

**Comment by boris-bc** [comment]
@RASakach I think we may want to discuss in ZAC if we are interested in adding a zCX container delivery method. If we agree that this is a good idea, then we would have to follow up with a spike story for the appropriate squad to research what would it require technically to achieve it.

**Comment by RASakach** [comment]
This item is completed for 23PI2.
