### ISSUE TITLE
Require social media post for 23PI2

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#1908]
Thank you for taking the time to submit a blog post proposal.

Please reference [Zowe Blog Guidelines](https://github.com/zowe/community/blob/master/blogging/blog_guidelines.md).

**Blog category**

Zowe blogs are categorized to allow readers to distinguish content that discusses software that is available in Zowe core together with other technology available under permissive open source licenses by being flagged as `{Core}`.  Blogs that describe commercial offerings available under vendor licenses are permitted but are flagged as `{Ecosystem}` and the commercial offering should be Zowe conformant.  Projects that are under Zowe incubation are flagged `{Incubation}` to indicate the solution being discussed isn't part of a Zowe Long Term Support (LTS) release

What kind of blog are you proposing ?

- [ ] Zowe Core  
- [ ] Zowe Ecosystem  
- [ ] Zowe Incubation
- [x] Zowe PI Planning

If your blog falls out of one of these categories please submit it anyway and the editorial team will let you know if it is an article that is likely to be accepted.

Schedule of 23PI2 - (2023/04/25 - 2023/07/24)

Planning - 2023/04/25 - 2023/05/01

    Wednesday, April 26 - Opening (Day 1)
    Thursday, April 27 - Breakouts (Optional) (Day 2)
    Friday, April 28 - Final Readouts (Day 3)

Sprint 1 - 2023/05/02 - 2023/05/15 (Innovation Sprint)
Sprint 2 - 2023/05/16 - 2023/05/29
Sprint 3 - 2023/05/30 - 2023/06/12
Sprint 4 - 2023/06/13 - 2023/06/26
Sprint 5 - 2023/06/27 - 2023/07/10
Sprint 6 - 2023/07/11 - 2023/07/24

**Comment by RASakach** [comment]
@jmertic:  We are looking for OMP Social Media support to announce our upcoming Zowe PI planning.  I was hoping to tag Mae but do not see a github id that matches her name.  Can you help?  Here's what we are looking for:

Join the Zowe Community in their upcoming quarterly planning event!
Details:  

Zowe Quarter 2 Schedule:  (2023/04/25 - 2023/07/24)

Planning - 2023/04/25 - 2023/05/01

Wednesday, April 26 - Opening (Day 1)
Thursday, April 27 - Breakouts (Optional) (Day 2)
Friday, April 28 - Final Readouts (Day 3)

Agenda:  https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/23PI2%20Planning/README.md

**Comment by Maemalynn** [comment]
@RASakach - John pinged me yesterday, so I wrote a blog post with the meeting details. I sent it to you to review yesterday but have not received a response. Since this meeting is coming up quickly - can someone from the Zowe team please review this blog and approve it? Once approved, I can promote it on our social channels. Thanks!
[](https://www.openmainframeproject.org/blog/2023/04/19/zowe-quarterly-planning-meeting )

**Comment by Joe-Winchester** [comment]
Thank you @Maemalynn !  The blog looks awesome.  
We have a Zowe Onboarders meeting today (8am EST) when we'll look at this together (Rose, Mike Dubois, Domenico, myself and others will be there), and we'll do one last read over.

**Comment by balhar-jakub** [comment]
The PI Planning is behind us. As such I am closing this issue. 

As a note we mustn't forget to ask for this awareness two weeks before the PI Planning so Mae has enough time for preparation.
