### ISSUE TITLE
Zowe Docs:  Help bring visibility to the 1-year Feature-Function Roadmap (we want Google hits)

### ISSUE THREAD

**Issue by RASakach** [zowe/community#1950]
Consider adding a link in a very-visible area within Zowe Docs to the 1-year feature-function roadmap.

https://github.com/zowe/zowe.github.io/raw/master/assets/roadmap/Zowe%20Roadmap%20CY23Q1.pdf

**Comment by janan07** [comment]
Do you think the Zowe overview page would be a suitable place to include this link? https://docs.zowe.org/stable/getting-started/overview/
Also, we should include a short description to what is in this roadmap and perhaps a list of each of the squads listed with a corresponding roadmap.

**Comment by balhar-jakub** [comment]
Wouldn't it be better if we had a category on the left Roadmap, with the first page the whole roadmap including information on what it is good for and how we create and update it and then page per squad with their roadmap?

**Comment by armstro** [comment]
ZAC decided that having Zowe futures roadmap on zowe.org is enough and linking with doc is no longer required.
