### ISSUE TITLE
Enable Multi-factor Authentication for Zowe API users (Desktop and REST)

### ISSUE THREAD

**Issue by hogstrom** [zowe/community#197]
**Is your feature request related to a problem or limitation? Please describe.**
Several large banks have requested that their apps (some of which are using Zowe) support MFA for access to Desktop applications specifically.

**Describe the experience you'd like**
When users are experiencing new applications in Zowe that require authentication they would like to use the latest security procedures of which multi-factor authentication is one.

**Additional context**
This request sounds like it is going to be a barrier to adoption of Zowe for apps and the Desktop for several customers.  @Joe-Winchester it would be helpful to add this to the architecture meetings on Wed for a discussion.

@plavjanik Are you thinking about this capability or the API-ML as there is an authentication part of the ML.

@1000TurquoisePogs has there been any discussion of this capability in ZSS and the Desktop ?

@Tbr00ksy If we choose to implement this type of capability then we might add this to the conformance discussion as a feature of applications like supporting JWT for single-signon.

**Comment by 1000TurquoisePogs** [comment]
zlux: https://github.com/zowe/zlux/issues/164

**Comment by 1000TurquoisePogs** [comment]
One item we need to work on ASAP and independent of the rest of the ecosystem is the ability for the Desktop to handle a rich  multi-step Q&A about login. It's very barebones currently.
That will need to be powered by an MFA backend. It's not clear to me what our go-to MFA backend will be yet. In the absence of alternatives, I am aware of a REST API for the https://www.ibm.com/us-en/marketplace/ibm-multifactor-authentication-for-zos product. The app framework has an abstraction for what handles security already, so it can be put into there without much new design. However, this would only power Apps if done that way. An approach which covers any auth needs of APIML would also be good. In that way, I'd suggest the REST API communication with the IBM MFA product could occur between it and APIML, and the Desktop could talk to APIML for login. That communication channel currently exists for our stage-1 SSO by which the Desktop multi-casts credentials to both APIML & the app server.

**Comment by gmackinnon** [comment]
@hogstrom we are researching MFA, and should discuss it at some point on an arch call

**Comment by Joe-Winchester** [comment]
Adding the LTSR Label to get visibility of this into the LTSR discussions - rather than explicitly declaring it to be an LTSR requirement

**Comment by balhar-jakub** [comment]
I propose turning this into Epic, as it was requested again in the survey a lot and at least within the API ML this wasn't resolved so far and we probably should keep it in mind.
