### ISSUE TITLE
Why does Zowe PSWI doc require users to install CCS?

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/community#1981]
https://docs.zowe.org/stable/user-guide/install-zowe-pswi-address-requirements/
Has the following text,
> Before you install Zowe using IBM z/OSMF, address the following installation and security requirements. Your systems programmers and security administrators can complete these tasks in parallel.

>    Apply required maintenance for Common Components and Services for z/OS (CCS) Version 15.0 (SO12499)
        Role: Systems programmer
        The CCS PTF installs load module stubs for select IBM products into your installed CCS library hlq.ZWE0CALL. If you are prompted during installation for the data set name of a load library for an IBM product that is not installed, specify your installed hlq.ZWE0CALL data set name. 

Users are asking what this is and where to get it. Upon investigation, it appears to be Broadcom software. Is Broadcom software really required for setting up IBM z/OSMF? This sounds unlikely and perhaps instead there's a reason why some users need to do this, but not others.

Can someone who's familiar with the subject clarify? I don't want to mislead users either way.

**Comment by armstro** [comment]
Per discussion at ZAC I will remove ZAC tag from this issue to allow DOC/TSC to follow up on this issue. Per @pdubz3 the doc needs to be corrected.

**Comment by balhar-jakub** [comment]
Closing as the issue was resolved via the docs squad issue referenced above.
