### ISSUE TITLE
Due Jun 13th - close on recommendations for 5th anniversary plans (SHARE actions and Trinkets) 

### ISSUE THREAD

**Issue by armstro** [zowe/community#1984]
Ideas due to John Jun 13th - some ideas proposed 
- Cake at Share 
- T shirts 
- New/updated slogan 
- Stickers (either existing or with something new) 
- Other? (keychains, mug, ...)

**Comment by RASakach** [comment]
My thoughts:

- Yes!  Cake!  Happy Birthday Zowe!    Perhaps we advertise a celebration during our Roadmap Session on Thursday afternoon?
- "Zowe: the way forward" stickers
- OMP / Zowe Mugs  (for Zowe Day attendees or the first x Zowe Day attendees)
- OMP / Zowe reusable shopping bags

**Comment by armstro** [comment]
@jmertic to research cake cost and logistics 

@RASakach we discuss having cake of Zowe Day to start the week rather than later in the week - 

Zac needs to offer ideas on the "5 years of Zowe" sticker design for OMP to refine - Bruce to post something into the slack channels for ideas from the team 

John is willing to fund Zowe mugs (maybe something like good quality Yeti mugs) but we need to discuss who/how they would be distributed. Maybe as thank you to speakers or long time Zowe participants. We need to think through how we decide receipants.

**Comment by armstro** [comment]
Additional idea for trinket is a solar calculator if for some reason other ideas fall through. Calculator something everyone can use (fits in the narrative of "simple" and "useful").

**Comment by armstro** [comment]
[Zowe for 5 ideas .pdf](https://github.com/zowe/community/files/11739040/Zowe.for.5.ideas.pdf)
Some ideas for 5 year stickers

**Comment by RASakach** [comment]
Update:  

- John has agreed to order 50 mugs and we provided a shipping address at the SHARE site.
- @armstro I believe John has shared the idea for the 5 - year stickers and it has been approved.
- Cake to begin Zowe Day sounds great
- Awarding Zowe Mugs = To be decided, some ideas:
- - First come, first serve (attendees, not for Community members)  / the first 10 customers in each Zowe session
- - Attendees that ask Zowe questions or share their Zowe experiences 
- - A raffle - attendees submit a "ticket" with their name / email address and we raffle them off at the end of Zowe Day

**Comment by RASakach** [comment]
Final thoughts:

- No cupcakes / SHARE logistics prevent this
- We are going to advertise (word-of-mouth at Zowe day) a group photo during our Wed 5:15 Roadmap Session in room Bolden 4 (Same Room as Zowe Day)
