### ISSUE TITLE
Explore the options for publishing GraphQL documentation in API ML Catalog

### ISSUE THREAD

**Issue by pinpan** [zowe/community#1989]
Some services publish GraphQL APIs for all the benefits of that technology, such as client-tailored requests, and server-side filtering of responses. It would be helpful to publish more details and examples, defined query, and mutation types.
 to multiple resources with a single request, and services orchestration.

As the services are onboarded with API ML, they contribute a tile and details page to the API ML Catalog, displaying very basic documentation.

GraphQL server implementations provide explorer UI/IDE for exploring the live endpoints, but this is an external tool that can't be embedded easily and will take the focus from the Catalog. Additionally, there are security concerns about exposing the single GraphQL endpoint in production through the catalog.

Nevertheless, it would be helpful to publish more details and examples of how to use the schema-defined queries and mutation types.

Static generators exist

It would be also beneficial to have compliance criteria for GraphQL services documentation in order to help developers with uniformly structured and useful documentation.

**Comment by balhar-jakub** [comment]
This topic has other areas to be discussed e.g. how do we change the Conformance criteria to properly respect the GraphQL and mainly the way GraphQL provides the documentation. The current way that's workaround but works is to generate Swagger document with the link to the URL where the GraphQL documentation resides. 

For V3 we will remain with this requirement, but for V4 we should introduce the change to handle the GraphQL properly. I introduced the text change to guide into the workaround for V3

_Documentation is Swagger/Open API 2.0/Open API 3.0 compliant in case of GraphQL API please provide Swagger with one endpoint e.g. the GraphQL. This will be improved in V4._

It would be good to be able to visualize the GraphQL directly within the API Catalog the same way we do for the Swagger - There may be an option to integrate for example this https://github.com/graphql/graphiql - The issue lives in the API Mediation Layer repository - https://github.com/zowe/api-layer/issues/3187

As such, I am closing this issue, if someone feels like we should change it, feel free to reopen.
