### ISSUE TITLE
Transition Zowe community meetings to use LFX Meeting Management

### ISSUE THREAD

**Issue by jmertic** [zowe/community#1993]
We are looking to transition all our communities at the Linux Foundation to using our new LFX Meeting Management service. Key advantages of this include:

- Centralized meeting scheduling and Zoom provisioning ( i.e. not having to juggle between the accounts )
- Automatic recording and publishing recording to openprofile.dev
- Light gating of meetings ( either LF ID or providing name/email ) to prevent Zoom bombing
- Automatic meeting attendance recording; helpful for gauging engagement.

More details at https://community.lfx.dev/t/lfx-meeting-management-getting-started-guide/2056

The following groups have transitioned over...

ZAC
TSC
API ML
System
Web UI
Onboarding
Chat
CLI
Documentation
z/OS
Explorer
Intellij

Not doing:

~ZEBRA~ _(no longer active squad)_

**Comment by jmertic** [comment]
Let me know when this could an agenda item

**Comment by jmertic** [comment]
Hi - when could we get this on the TSC meeting agenda?

**Comment by balhar-jakub** [comment]
I missed it as I am still going over backlog of items, I will try to add it next Thrusday as I expect attendance this week to be limited due to Share.

**Comment by jmertic** [comment]
That works for me; I will mark to attend.

**Comment by jmertic** [comment]
Update: The following groups have transitioned over...

ZAC
TSC
API ML
System

In progress:

Onboarding

TODO:

App Framework/Desktop
CLI
Explorer
Documentation
z/OS
Intellij

@balhar-jakub Let me know if I am missing any squads or other groups.

**Comment by balhar-jakub** [comment]
You are missing:
 - Architecture, System Demos, PI Planning - Nick Kocsis is responsible for these meetings. 
 
From incubation squads:
- ZEBRA - This may become irrelevant after the TSC meeting on 7th September
- Zowe Chat - Mark Ackert is responsible

**Comment by jmertic** [comment]
Thanks @balhar-jakub - are those groups all squads/committees or just meetings? Just wanting to make sure I have the right setup.

**Comment by balhar-jakub** [comment]
The meetings are just regular meetings, but for System Demos and PI Planning with large audience and large amount of speakers. 
The incubation squads are squads. 
- Zowe Chat is probably the only one relevant .

**Comment by jmertic** [comment]
Got it - thanks @balhar-jakub !

**Comment by jmertic** [comment]
Hey @balhar-jakub - could I reach out to the below squad leads and work on moving them over?

CLI
Explorer
Documentation
z/OS
Intellij
Chat
ZEBRA

**Comment by balhar-jakub** [comment]
ZEBRA doesn't exist as squad anymore. For the rest let's mention it on TSC call on Thursday. 

Here I will mark people that can help you for specific squads
CLI - @adam-wolfe can help you
Explorer - @JillieBeanSim 
Documentation - @janan07  
z/OS - @JoeNemo 
Intellij - @KUGDev 
Chat - @MarkAckert

**Comment by jmertic** [comment]
Thank you all! We've moved everyone over.

I'll keep the old Zoom accounts active through the end of the year and then decommission them, just in case we run into any issues. Appreciate everyone's support!
