### ISSUE TITLE
Agree on extender Office Hour dates

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1996]
Office Hours for extenders together with the recordings and publishing of the recordings worked well for V2 and we intend to keep them for V3. 

The schedule should be available on the vNext page around the beginning of August.

**Comment by RASakach** [comment]
Current plan
Begin 10/6 (use the Onboarding 8am meeting slot)
Zowe V3 for Extenders will cover all LTS Core components with the following content:

- What's new in V3
- What's the impact to the Conformance program?  (V3 changes)
- How can Extenders test their extension?

1.  APIML  10/6
2. - CLI  10/13
3. - Explorer (VS Code) 10/20
4. - Web UI 10/27
5. - Other? 11/3

**Comment by balhar-jakub** [comment]
The API ML time works for me.

**Comment by balhar-jakub** [comment]
Done and the hours are in progress.

**Comment by DivergentEuropeans** [comment]
Some postponements for multiple calls are in discussion, thank you
