### ISSUE TITLE
Prepare document for every squad for planned conformance changes

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#1999]

**Comment by RASakach** [comment]
The template for V3 conformance changes (all squads) is located here:
https://ibm.box.com/s/qafqd63oda4vp4ie7p2xu9xfmbmmqnab 

Note:  The Zowe Explorer for IntelliJ and Zowe Client SDK worksheets are NEW and thus only require the V3 entries.  All others need to highlight any differences.
