### ISSUE TITLE
Zowe Blog: Zowe's Role in z/OS and Your Journey to Cloud

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#206]
[Zowe and Z Cloud Final Final .docx](https://github.com/zowe/community/files/3426977/Zowe.and.Z.Cloud.Final.Final.docx)
To be uploaded to the OMP blog site and promoted on social.

**Comment by christinevblum** [comment]
@jmertic do you want me to post the blog. If so, when do you want to schedule it for?

**Comment by jmertic** [comment]
I'd say work with Jesse to have him post and coordinate when to send live.
