### ISSUE TITLE
Cleanup and improve our Slack Channels structure

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#2120]
We currently went through the list of the channels that Zowe actually uses and we want to change it in this following:

Rename zowe-user to zowe-help
Rename zowe-build to zowe-nightly-builds
Rename zowe-cicd to zowe-system-squad
Rename zowe-api to zowe-apiml
Rename zowe-explorer to zowe-explorer-vsce 

Remove zowe-install-rework
Remove zowe-dev
Remove zowe-ux
Remove zowe-ha
Remove zowe-github-actions
Remove zowe-performance
Remove zowe-waffle
Remove zowe-workflow-wizard
Remove zowe-zosmf-config
Remove zowe-tls12
Rename zowe-client-sdk to zowe-client-sdks (plural)
Remove zowe-mobile

Add zowe-app-fw
Add zowe-feedback
Add zowe-announcements

**Comment by jmertic** [comment]
@yarille - would you mind making these adjustments?

**Comment by yarille** [comment]
@jmertic and @balhar-jakub this should be all done. Please let me know if you need anything else.

**Comment by balhar-jakub** [comment]
@yarille Thanks For doing that. I am closing the issue as done.
