### ISSUE TITLE
End of Support for Version 1 

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#2124]
The goal of this issue is to capture and keep the work around the preparation for End of Support for Version 1. 

The date is the 2024/09/30 - After this date there will be no new version of 1.x released and the community won't support in any way the version 1.x

The conformance program for V1 will be also closed and removed. 

We need to improve our guide on migrating from V1 to V2. The only thing available is here: https://docs.zowe.org/stable/extend/migrate-extensions

**Comment by balhar-jakub** [comment]
The proposed work needed including when it need to happen. 
- Prepare and publish the blog on the End of Support for V1. 
  - 2023/11
- Write to the #zowe-announcements channel
  - 2023/11  
  - 2024/08
- Write an email to the zowe-user mailing list
  - 2023/11  
  - 2024/08
- Prepare text of the notice that can be used by conformant providers. 
  - 2023/11

**Comment by balhar-jakub** [comment]
Proposed text for the email: 

Subject: Important Update: Zowe V1 Support Ending - Migrate to Zowe V2!

Dear Zowe User,

We hope this email finds you well. We wanted to bring an important update to your attention regarding the support for Zowe V1.

As of September 30, 2024, the Zowe community will be officially ending support for Zowe V1. To continue enjoying the benefits and features of Zowe, it is crucial that you migrate to Zowe V2 before this deadline.

Migrating to Zowe V2 is explained on our dedicated page at https://docs.zowe.org/stable/extend/migrate-extensions for step-by-step instructions on how to successfully migrate your Zowe.

By migrating to Zowe V2, you'll continue to experience enhanced functionality, improved security measures, and access to the latest updates and features that our community has been working hard on.

Should you have any questions or require assistance during the migration process, please don't hesitate to reach out via OMP Slack or Zowe GitHub. 

Best regards,

The Zowe Team

**Comment by balhar-jakub** [comment]
### Proposed text for the Slack

📢 Attention all Slack channel members!

We have an important announcement regarding the Zowe product. Starting on September 30, 2024, Zowe will no longer be providing support for version 1. It is crucial for all customers currently using version 1 to migrate to version 2 before this date, as the community will no longer be able to offer support for the older version.

To ensure a smooth transition, we have prepared instructions on how to migrate from version 1 to version 2. You can find all the necessary information on our documentation page at https://docs.zowe.org/stable/extend/migrate-extensions. We highly recommend reviewing this page and following the guide to facilitate the migration process.

Please take note of this important deadline and make it a priority to migrate your Zowe and extensions from version 1 to version 2 before September 30, 2024. This will ensure that you continue to receive the best possible support from both the Zowe community and our team.

Thank you for your attention and cooperation. If you have any questions or require further assistance, please don't hesitate to reach out. We're here to help!

**Comment by balhar-jakub** [comment]
### Proposed text for the Conformant Support Providers

We would like to inform you that Zowe product will be ending support for version 1 on September 20, 2024. As a result, we encourage all our customers to migrate to the latest version, V2, by this deadline. Kindly note that the community will no longer provide support for V1 after this date. To help with a transition, we have provided detailed instructions on how to migrate your extensions on our website. Please visit https://docs.zowe.org/stable/extend/migrate-extensions for more information. We appreciate your cooperation and thank you for choosing Zowe.

@armstro This may be relevant for you as this is the first version proposal for the Conformant Support Providers.

**Comment by armstro** [comment]
A couple comments (that might be too picky but I will state them anyway) 
- Zowe is not a "product" - I would think of a different word - that the Zowe LTS Components will be ending support 
- Do you want to say something about critical defect support rather than just support (technically we are in a period of only fixing critical defects and not defect support of all defects)

**Comment by balhar-jakub** [comment]
@armstro I removed the word product, I believe that without it it would work well. 
As for the second part we formally still claim the support it's just that it's more limited. Excerpt from our documentation about the releases - _"We will support older release lines in maintenance mode for 2.5 years. This support timeline allows us to support one active and one maintenance release line, along with a small window where we support one active and up to two maintenance release lines in parallel."_

**Comment by balhar-jakub** [comment]
### Proposed text for the Issues after Zowe support ends

Thank you for reaching out to us. I wanted to inform you that as of September 30, 2024, the support for Zowe Version 1 has officially ended. This means that the community will no longer be able to provide assistance with your request as it relates to the Zowe Version 1.

We understand that this may be disappointing news, but it is important to keep in mind that software updates and support discontinuations are common occurrences to ensure the development of newer and more advanced technologies. If you are still using Zowe Version 1, please upgrade to Version 2. More details on the migration are available in [Zowe Docs](https://docs.zowe.org/stable/extend/migrate-extensions)

**Comment by balhar-jakub** [comment]
## Proposed text for the banner

Zowe Version 1 End of Support is coming on September 30, 2024. Please migrate to version 2.

**Comment by balhar-jakub** [comment]
## Proposed text for Downloads

Zowe is approaching the end of support for major version 1, which you are currently downloading. The support will end on September 30, 2024. After this date, the community will not release any new versions or address any issues, including security fixes, related to version 1. To facilitate a smooth transition, we have prepared a comprehensive guide available here: [https://docs. zowe. org/stable/extend/migrate-extensions](https://docs. zowe. org/stable/extend/migrate-extensions). If you have any questions, please feel free to reach out to us via [OMP Slack](https://openmainframeproject. slack. com/archives/CC08782AG) or [Zowe GitHub](https://github. com/zowe).
