### ISSUE TITLE
Propose permanent resolutions to the consumer "authentic & fragmented zowe" concerns

### ISSUE THREAD

**Issue by RASakach** [zowe/community#2129]
Brainstorm ideas around how we might quickly and easily offer an "authentic" Zowe mark for Zowe.  

Present the outcomes to ZAC and TSC.

**Comment by RASakach** [comment]
We need to approach this from another angle.
Customers are concerned about the OPEN CORE Model of Zowe
TO DO:
ZAC discussion about this concern and the best way to mitigate it.

**Comment by balhar-jakub** [comment]
We also need to make it clear on what is Core for Zowe and what is not in a way that's more understandable and for the results we should make statements on zowe.org webpage and Zowe docs for everyone to clearly understand.

**Comment by RASakach** [comment]
We have introduce blogs on this topic and to-date have not heard any further concerns.
