### ISSUE TITLE
Archive the IMS CLI and IMS Operations API projects for Zowe v3

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#2132]
** Reason **
The Zowe projects for IMS Operations API and IMS CLI are no longer supported by the initial teams that created them.  Since their inception IMS Administration Foundation has been released by the IMS product which provides a more functional (and supported) set of REST APIs to administer IMS operations.

** Proposal **
Archive the IMS Operations API and IMS CLI projects, and remove reference to them in Zowe documentation and Zowe LTS for v3.

** Longer term solution **
At some future point a CLI replacement for the IMS Operations API would be created that would target the IMS Administration Foundation API REST APIs,  likely started as an incubator project within the v3 timeframe.  

I've discussed this with Fernando (CLI squad lead) and he is keen that we do this within the V3 timeframe.  Happy to put together a slide or two to talk to the history behind the IMS CLI and IMS Operations API and why this is a good time to archive the projects and also what their replacement could look like to fill the functional gap.

**Comment by balhar-jakub** [comment]
I will bring it to TSC, but I believe that as there is no squad owning the work, the archivation is correct approach.

**Comment by Joe-Winchester** [comment]
> I will bring it to TSC, but I believe that as there is no squad owning the work, the archivation is correct approach.

Thank you @balhar-jakub .   Is there a formal process to archive a project that @zFernand0 and I can reference or is this the first Zowe project to be archived ?   

Cheers !

**Comment by balhar-jakub** [comment]
The only information available is here: https://github.com/zowe/community/blob/master/Technical-Steering-Committee/projects.md

In general as this was never part of Core and therefore is an Extension and never reached the maturity of GA and above, I would do the same that we are doing for the metrics service. E.g. announce it on TSC and ZAC and if there are no objections archive it, we will do it together with V3 release date.

**Comment by balhar-jakub** [comment]
The agreement is that we will archive with V3 and the CLI and API ML Squads will notify the users on user focused office hours.

**Comment by zFernand0** [comment]
The IMS CLI Plug-in has been deprecated. And we also archived the repository.

However, I do not have permissions to archive the IMS Operations API repo 😢 
https://github.com/zowe/ims-operations-api

**Comment by zFernand0** [comment]
Thanks @MarkAckert for helping with the archival process 😋 

Closing!

**Comment by Joe-Winchester** [comment]
Well done @zFernand0  and @MarkAckert  !!!!   Excellent to see this done in time for V3.  Thank you !
