### ISSUE TITLE
Slack Channel #zowe-user should be listed as #zowe-help.

### ISSUE THREAD

**Issue by Andrew-J-Metzger** [zowe/community#2154]
On https://www.zowe.org/contribute, the Slack section lists `#zowe-user` as a popular channel. However, this channel has been renamed to `#zowe-help`. Perhaps this reference should be renamed to match. See screenshot below, with the offending channel outlined in red:
![chrome_2024-01-09_145553](https://github.com/zowe/community/assets/128719308/51859f4e-8f60-4523-bc67-61598a976b17)

**Comment by balhar-jakub** [comment]
Thanks for sharing, I created the PR with the change - https://github.com/zowe/zowe.github.io/pull/899

**Comment by balhar-jakub** [comment]
And now it's there.
