### ISSUE TITLE
Zowe V3 Delay Notification

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#2193]
Based on the TSC Discussion on Feb 23, 2024 and decision the V3 release will be delayed. The exact date is unclear and will be known by the End of March 2024.

The main reason for the delay is to understand better the security posture and requirements concerning the Zowe dependencies for Zowe V3. 

There is currently ongoing work on the analysis and understanding what upgrades are needed and how difficult they are.

**Comment by RASakach** [comment]
Zowe V3 Release will be delayed. The Zowe V2 release schedule will be adjusted to accommodate this change.  We expect to have a new V3 release date and further information on V2 by the end of the March and will notify you at that time.   

We are sorry for the inconvenience. During the due diligence phase in preparing for the V3 release, we discovered the dependent package support policies and subsequent requirements changed, therefore we need to perform further evaluation prior to releasing.

**Comment by balhar-jakub** [comment]
Published to: 

- zowe.org announcements
- zowe.org vNext
- Zowe Docs Banner
- zowe-zac, zowe-tsc, zowe-help and zowe-announcements Slack Channels
