### ISSUE TITLE
MVS Explore: Fetch Datasets failed for (XXXXXX)TSOID

### ISSUE THREAD

**Issue by Sam-Explorer** [zowe/community#2196]
Hello,
Good Day

When we access MVS Explorer from Zowe desktop portal, I get 'MVS Explore: Fetch Datasets failed for (XXXXXX)TSOID'

In Zowe.Yaml, I have enabled mvs & uss explorer
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  explorer-mvs:
    enabled: true
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  explorer-uss:
    enabled: true
    
 Any thing else that need to be taken in account for MVS & USS Explorer to work?
 
 Thanks

**Comment by balhar-jakub** [comment]
@struga0258 This seems like and issue related to Web UI, can you please move it to the proper Repository and take a look?

**Comment by Sam-Explorer** [comment]
Hi Jakub,
Thank you, however above mentioned issue has been fixed. It was due to network security.

I have marked it as done.
