### ISSUE TITLE
Cryptic error message issued during zwe start processing

### ISSUE THREAD

**Issue by outtheresomewhere** [zowe/community#2228]
Trying to initialize Zowe server on z/OS V2R5 with the USS command **zwe start --config /global/zowe/zowe.yaml**, and 
the following error messages are issued:

******2024-04-20 19:02:24 <ZWELNCH:16843708> ZWESVUSR ERROR ZWEL0070E Configuration has validity exceptions: 
Validity Exceptions(s) with object at                                                                  
  Validity Exceptions(s) with object at /zowe                                                          
    Validity Exceptions(s) with object at /zowe/setup                                                  
      Validity Exceptions(s) with object at /zowe/setup/dataset                                        
        unspecified additional property not allowed: 'security' at '/zowe/setup/dataset/security'      
        unspecified additional property not allowed: 'product' at '/zowe/setup/dataset/product'        
        unspecified additional property not allowed: 'groups' at '/zowe/setup/dataset/groups'          
        unspecified additional property not allowed: 'users' at '/zowe/setup/dataset/users'            
        unspecified additional property not allowed: 'stcs' at '/zowe/setup/dataset/stcs'              
    type 'string' not permitted at /zowe/environments; expecting type 'object'******        

Our yaml file DOES pass the syntax checks done by **yamlchecker.com**                 
****
**Steps to Reproduce**
****
1. Install Zowe with SMP/E
2. Try to start Zowe via USS command zwe start --config /global/zowe/zowe.yaml

**Expected behavior**

I was **EXPECTING** to see error messages that were clear, concise, and pointed to precisely what caused the error AND how to fix it.

**Details**
Zowe 2.0, executing on a zPDT under z/OS V2R5.

**Comment by balhar-jakub** [comment]
I don't have the .yaml file you are using, but based on the message it seems that some of the sections is incorrectly indented compared to the other sections. 

Specifically:

```
zowe:
    setup:
        dataset:
        security:
```

needs to be indented on the same level as dataset instead of being part of it e.g.

```
zowe:
    setup:
        dataset:
            security:
```

**Comment by outtheresomewhere** [comment]
Thank you. Indentation errors in zowe.yaml were the root cause of the errors I was seeing.

I hate yaml files; I wish zowe used some other type of file to establish its startup config. It is NOT user friendly...
