### ISSUE TITLE
Zowe & Discord Management

### ISSUE THREAD

**Issue by RASakach** [zowe/community#2249]
Review the platform and understand the expectations of the Onboarding Squad within this new FORUM

Includes:  
- Review of current discussions & bi-weekly updates shared with OB Squad
- Selection  & expectation of "moderators" for the Subgroup

**Comment by RASakach** [comment]
@zFernand0 will be researching Moderator responsibilities and capabilities.

@RASakach & @zFernand0 will coordinate a proposal for moderators for TSC review

**Comment by mindshackledsteven** [comment]
Hey folks, Steven Perva here. As for question #4, I wanted to add that we can have people who are badged as representatives of the Zowe project without giving them moderator authority over the Zowe channel. If you have people looking to answer questions but not be able to pin/manage messages this is a good option.

**Comment by RASakach** [comment]
Thank you @mindshackledsteven for describing the "Representatives" designation.  Very helpful!

We are still interested in understanding the recommendation for total number of Moderators within the Zowe Subgroup.  What do other subgroups have for Moderators as an example?  2 - 3?  More than that?    We appreciate any insight you can provide.

**Comment by mindshackledsteven** [comment]
@RASakach I would recommend at least 2. For clarity, the System Z Enthusiasts Discord moderation team will handle most of the responsibilities that community moderators would provide, we just want to impart as much control as possible onto the community to govern itself. The true role of the community moderation team is to liaise requirements to the Discord moderation team (event requests, additional channel requests, granting people official designations). That comes with the benefit of being able to pin messages, manipulate the channel "topic", delete any messages that may be considered harmful/necessary for deletion, as well as encourage others to stay on topic.

An example, we recently had a spam message land in all of our public channels. While our moderation team was quick to ban the user and clean up the messages. Some community moderators took the initiative to remove the message from their specific channels.

As for the other communities, it ranges from 2-5 moderators. I would consider 2 to be the minimum just to make sure there's no single point of "failure". There is nothing stopping you from having a dozen or more moderators. Our goal is to just make sure that the notification of someone being added comes from an official source (an existing moderator [ideally 2], an official email of an existing moderator, some official channel associated with the project) so we can be sure the community has integrity!

**Comment by RASakach** [comment]
Next steps are to secure 2 moderators.
We will bring this to TSC

**Comment by RASakach** [comment]
@mindshackledsteven : We have 2 volunteer moderators for Zowe
Sean Grady
Jakub Balhar

What are our next steps?

**Comment by mindshackledsteven** [comment]
@RASakach Please just ping me, on Discord, the Discord IDs of those two folks and I will have them setup! I'll expect it to come from your Discord ID so I know it's you.

**Comment by balhar-jakub** [comment]
@mindshackledsteven @RASakach My discord name is balharjakub

**Comment by zFernand0** [comment]
I know we haven't had much zowe activity on Discord.
But I believe that the goal of this issue was achieved 😋 
We have captured how it should be managed and we also have a few more folks added to the community 😋 

Should we close this issue for now? 
Not sure if we want to create some sort of document to capture this. 
Either way, this issue comes up when googling "zowe discord management".

**Comment by RASakach** [comment]
@zFernand0 I just need to confirm that Sean was added as a Moderator, then we can close this out.  Thank you for the reminder!
