### ISSUE TITLE
Filtering for Endevor Package - Zowe Explorer

### ISSUE THREAD

**Issue by Ngu0210** [zowe/community#2324]
**Is your feature request related to a problem or limitation? Please describe.**

Limitation. Navigating through hundreds or thousands of Endevor packages can be cumbersome, making it difficult to quickly locate specific packages or view only relevant ones. This lack of efficient navigation and filtering slows down workflows and increases the chance of overlooking critical packages.

**Describe the experience you’d like**

A streamlined, intuitive filtering feature within the Zowe Explorer VSCode extension that allows users to quickly refine their view to find specific Endevor packages based on key attributes. Ideally, this feature would include:

	1.	Package ID Search - The ability to filter packages by exact ID, prefix (using wildcards such as *), or partial match (using % for single-character wildcards).
	2.	User and Date Filters - Options to filter packages based on the creator’s User ID or creation date.
	3.      Saved Filter Profiles - The ability to save frequently-used filters, making it easy to reapply common searches with a single click.

**Comment by adam-wolfe** [comment]
Hi @Ngu0210, thank you for submitting this request, however issues for Explorer for Endevor should be opened here: https://github.com/eclipse-che4z/che-che4z-explorer-for-endevor.

Thanks
