### ISSUE TITLE
Revise the MIGRATING FROM ZOWE V2 to V3 section name

### ISSUE THREAD

**Issue by RASakach** [zowe/community#2326]
A customer asked for information on migrating from Zowe V1 to Zowe V3 and although we had details on this in our MIGRATING FROM ZOWE V2 to ZOWE V3 section, the reader assumed it wasn't there because of the section header.

![Image](https://github.com/user-attachments/assets/6c0b5491-ecc3-431c-9a3e-df8509edca84)

Can we modify that section name to read something like:
MIGRATING FROM ZOWE Vx to ZOWE V3

**Comment by janan07** [comment]
Sure. I can make this change.
