### ISSUE TITLE
Zowe App Directory - Zowe Apps

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#234]
I am working with the OMP to pre-populate the Zowe App Directory (which lists all Zowe conformant applications). 
Preview link: https://www.openmainframeproject.org/projects/zowe/conformance
Password: zowe
Wiki page for feedback: https://github.com/zowe/community/wiki/Zowe-App-Directory-Feedback

If I’m not mistaken, there are a few free Zowe apps/plug-ins/APIs that are not shipped within “base Zowe” but may qualify as Zowe conformant as they have been contributed to the open source project. Would anyone be able to review which of these apps/plug-ins should be listed in the Zowe App Directory?

List of apps, extensions and plug-ins (in no specific order):

- [ ] Sample Angular App: https://github.com/zowe/sample-angular-app
- [ ] Sample React App: https://github.com/zowe/sample-react-app
- [ ] Sample i-Frame App: https://github.com/zowe/sample-iframe-app
File Transfer: https://github.com/zowe/file-transfer-app (not ready, WIP)
z/OS Subsystem Explorer: https://github.com/zowe/zos-subsystems (not currently in Zowe “suite”)
- [ ] Zowe Jupyter App: https://github.com/zowe/jupyter-app
- [ ] DB2 Library for Zowe DB Browser: https://github.com/zowe/db-browser-db2
- [ ] VSCode Extension for Zowe: https://github.com/zowe/vscode-extension-for-zowe
- [ ] Zowe CLI Db2 Plug-in: https://github.com/zowe/zowe-cli-db2-plugin
- [ ] Zowe CLI CICS Plug-in: https://github.com/zowe/zowe-cli-cics-plugin
- [ ] Zowe CLI IMS Plug-in: https://github.com/zowe/zowe-cli-ims-plugin
- [ ] zTrial Sample CLI Plug-in: https://github.com/zowe/ztrial-sample-cli-plugin
- [ ] zLux Editor: https://github.com/zowe/zlux-editor
- [ ] USS Explorer: https://github.com/zowe/explorer-uss
- [ ] JES Explorer: https://github.com/zowe/explorer-jes
- [ ] MVS Explorer: https://github.com/zowe/explorer-mvs
- [ ] TN3270: https://github.com/zowe/tn3270-ng2
- [ ] VT App: https://github.com/zowe/vt-ng2
- [ ] Workflow Editor: https://github.com/zowe/zlux-workflow
- [ ] zLux API Catalog: https://github.com/zowe/api-layer/tree/master/zlux-api-catalog  

Are there others that should be added?

**Comment by nannanli** [comment]
Hi @Tbr00ksy @jmertic, Just FYI that I just left some feedback on the wiki page. : )

**Comment by jmertic** [comment]
Closing this issue as we are complete on the design of the initial App Directory. Will be looking at round 2 later in the year that looks more like https://www.cncf.io/certification/software-conformance/ - stay tuned!
