### ISSUE TITLE
Free Zowe Apps Listed in App Directory

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#253]
Objective: Show the extensibility and interoperability of the Framework by highlighting not just commercial extensions, but also free apps/apis/plug-ins. We want to inspire and encourage innovation through the expanding ecosystem of conformant applications and services.

Proposal:
In the "App Directory" which lists the Zowe Conformant Apps (https://www.openmainframeproject.org/projects/zowe/conformance) also list some of the free tools that are available in the Zowe community (and eventually anyone's repo that has passed the conformance criteria) that are not included in the base. 

If I’m not mistaken, there are a few free Zowe apps/plug-ins/APIs that are not shipped within “base Zowe” but may qualify as Zowe conformant as they have been contributed to the open source project. Would anyone be able to review which of these apps/plug-ins should be listed in the Zowe App Directory?

List of apps, extensions and plug-ins (in no specific order):

- [ ] Sample Angular App (in base - not applicable): https://github.com/zowe/sample-angular-app
- [ ] Sample React App (in base - not applicable): https://github.com/zowe/sample-react-app
- [ ] Sample i-Frame App (in base - not applicable): https://github.com/zowe/sample-iframe-app
- [ ] File Transfer: https://github.com/zowe/file-transfer-app (not ready, WIP)
- [ ] z/OS Subsystem Explorer: https://github.com/zowe/zos-subsystems (not currently in Zowe “suite”)
- [ ] Zowe Jupyter App: https://github.com/zowe/jupyter-app
- [ ] DB2 Library for Zowe DB Browser: https://github.com/zowe/db-browser-db2
- [ ] VSCode Extension for Zowe (Not applicable?): https://github.com/zowe/vscode-extension-for-zowe
- [x] Zowe CLI Db2 Plug-in: https://github.com/zowe/zowe-cli-db2-plugin
- [x] Zowe CLI CICS Plug-in: https://github.com/zowe/zowe-cli-cics-plugin
- [ ] Zowe CLI IMS Plug-in: https://github.com/zowe/zowe-cli-ims-plugin
- [ ] zTrial Sample CLI Plug-in: https://github.com/zowe/ztrial-sample-cli-plugin
- [ ] zLux Editor: https://github.com/zowe/zlux-editor
- [ ] USS Explorer: https://github.com/zowe/explorer-uss
- [ ] JES Explorer: https://github.com/zowe/explorer-jes
- [ ] MVS Explorer: https://github.com/zowe/explorer-mvs
- [ ] TN3270: https://github.com/zowe/tn3270-ng2
- [ ] VT App: https://github.com/zowe/vt-ng2
- [ ] Workflow Editor: https://github.com/zowe/zlux-workflow
- [ ]  zLux API Catalog: https://github.com/zowe/api-layer/tree/master/zlux-api-catalog

Are there others that should be added?

Once those Apps are identified, we can submit for conformance and have them listed in the "App Directory."

**Comment by MikeBauerCA** [comment]
Zowe CLI IMS and MQ Plug-ins can be added, but should have an @lts-incremental version which is a commitment to not release breaking changes to that tagged version. 

Once these plug-ins have an @lts-incremental they should be shipped with releases of Zowe just like the CICS and Db2 CLI plug-ins are today.

**Comment by MikeBauerCA** [comment]
Also, I am not sure how I unassigned @billpereira but it will not let me reassign. Feel free to reassign yourself if needed.

**Comment by Tbr00ksy** [comment]
Closing issue as we have had applicable Zowe apps added to the conformance page.
