### ISSUE TITLE
Doc to be updated with new URL for MVD in Zowe 0.9.4

### ISSUE THREAD

**Issue by kathysychan** [zowe/community#27]
I downloaded Zowe 0.9.4 RC2 and found that MVD is no longer available at:

https://hostname:8544/ZLUX/plugins/com.rs.mvd/web/index.html

I was then informed by another developer that I should instead be going to:

http://host:8544/

which redirects to:

https://hostname:8544/ZLUX/plugins/org.zowe.zlux.bootstrap/web/

The Using Zowe desktop documentation and What's New for Zowe 0.9.4 should be updated to reflect this.

**Comment by nannanli** [comment]
Julie has updated the document and What's new. See https://github.com/zowe/docs-site/blob/docs-staging/docs/getting-started/summaryofchanges.md.

**Comment by nannanli** [comment]
Julie has updated the document and What's new. See https://github.com/zowe/docs-site/blob/docs-staging/docs/getting-started/summaryofchanges.md.
