### ISSUE TITLE
Zowe- Automated New Feature Notifier

### ISSUE THREAD

**Issue by AWADHAMBIKA** [zowe/community#272]
### History:
Currently, ZOWE user community doesn't have any way to monitor the new developments and enhancements coming in ZOWE.

### Problem:
A user needs to keep checking for new code in GIT or check any forum and then if something new comes up then proceed accordingly.

### Solution:
As part of plugin definition file, we can have a set of new keys as part of **pluginDefinition.json** file to publish the same if contributor wants to and the same will be automatically communicated to user by social media channels. 

Proposed new keys for the same in pluginDefinition.json:
"newFeature": Value of this key can be the wording about the new feature to be published.
"toBePublished": Value of this key can be Yes/No. If yes the feature key above will be published to below social Media Handles
"publishedTo": Value of this key can be an array of URLs i.e. 
"publishedTo": {
      "url1":"www.linkedin.com/hgdhjsaf/fdtfdvy24632hshdvhdsfh",
      "url2": "www.twitter.com/API/hsdfjkshfkak/sfg656489",
    }

The URLs are the Developer API for social media websites to publish the content using code.

### How this works?
As soon the contributor/Developer finishes developing a new Plugin or enhancement, he updates the above content for publish and as soon as the ZOWE restarts, it reads the pluginDefinition.json for the plugin and parses the content and publishes the result based on that.

**Comment by balhar-jakub** [comment]
We are working on improvements on Common boards for tracking the changes here: https://github.com/zowe/community/issues/1013

We also have the release notes here: https://docs.zowe.org/stable/getting-started/summaryofchanges.html

With this I am closing this issue
