### ISSUE TITLE
Make the zss able to trust authentication tokens based on JWT

### ISSUE THREAD

**Issue by PeterHalsted** [zowe/community#295]
I would be of great value if Zowe would support the feeling of single sign-on by being able to configure an OpenID Connect server with e.g. support for Kerberos as initial token and return a JWT that would then be used to authenticate against the Zowe backend. One such OIDC could be Active Directory Federated Services on a corporate domain.

The backend (zss?) should then be able to map the username to a username in e.g. RACF - ICRX token? - and run e.g. CICS transactions as the user for e.g. tn3270 based applications.

There does not exist any alternatives for Zowe that I am aware of but one could enable e.g. the RACF for Kerberos, and then use that for authenticating against Zowe.

**Comment by 1000TurquoisePogs** [comment]
1.5.0 will have JWT validation logic in ZSS, via the PRs https://github.com/zowe/zss/pull/79 and https://github.com/zowe/zowe-common-c/pull/82
We still need to pull this together with the rest of Zowe to show that it is working properly.

**Comment by PeterHalsted** [comment]
Sounds great and looking very much forward to it - you Rocket guys really do rock ;)

Thanks a lot for yet another great news.

**Comment by NolanRogers** [comment]
Hello Peter, If you ever have questions for the Web UI squad, we meet every Friday and encourage others in the community to come with requests/ideas, see if they can help out, or even just listen in and learn more about the desktop in Zowe. Please see: https://lists.openmainframeproject.org/g/zowe-dev/viewevent?repeatid=9777&eventid=495178&calstart=2019-09-27  for the reoccurring meeting or reach out to me.

**Comment by PeterHalsted** [comment]
Thanks Nolan. I have added the calendar events and will see, if I can make it for tomorrow :)
