### ISSUE TITLE
Advancing the packaging of Zowe z/OS components to SMP/e or Portable Packages

### ISSUE THREAD

**Issue by solsu01** [zowe/community#30]
For the sake of conformance to platform standards, usability and credibility we should adopt standard z/OS packaging practices (SMP/e and Portable Packages) for Zowe's z/OS components like the Zowe Desktop and API Mediation Layer.

**Comment by Joe-Winchester** [comment]
This is being worked on and tracked in https://github.com/zowe/zowe-install-packaging/issues/414.  @solsu01 are you OK if I close this as a duplicate / superceded ?
