### ISSUE TITLE
Zowe.org homepage should make it easier to learn what Zowe is

### ISSUE THREAD

**Issue by rpenny125** [zowe/community#31]
As a potential Zowe user I need it to be easier for me to learn what Zowe really is so that I can decide if it will be of any help to me.

**Comment by rpenny125** [comment]
Comment from IBM-main below, but I interpret the main problem is that there is poor "progressive disclosure" on zowe.org.

------------------------------------
A colleague asked me, "WTF really *is* Zowe?" and the only answer I had was that I thought it was like z/OSMF, only more so (and ISTR that it's even built on top of z/OSMF), and open source. 
 
I've seen https://www.rocketsoftware.com/zowe-open-source-mainframe

but it just says "Zowe good" and "open source framework" and like that, never explains what it actually does. 

https://zowe.org/home/ is a bit better, seems to support my contention, but also waves hands about APIs and a command-line interface. That makes it sound like it's (conceptually) sorta z/OSMF + Dovetail + scp.

I guess my point here is that I lose interest before I get very far, because it all sounds like smoke and mirrors and "It's open source, it must be good".

Can someone correct my (presumed) misapprehensions, perhaps provide a product description that includes benefits, not just features?

**Comment by Tbr00ksy** [comment]
During the on-boarding squad call we were brainstorming about the possibility to have expand (drop down) option over the different component description which could point to additional resources like a video, blog or point to the user guide.

**Comment by nannanli** [comment]
On doc site, we added the demo video after the component description https://zowe.github.io/docs-site/latest/. It might be best to add an overview video that incorporates all that Matt describes on the landing page of Zowe.org. Also on the landing page, organize the sections by describing the benefits of Zowe instead of describing the components - more marketing focused style. Something like https://kubernetes.io/ does. My two cents.

**Comment by Tbr00ksy** [comment]
Would it make sense to make this issue part of a bigger epic to transition Zowe.org word press over to GitHub Pages? This would not be a 1.0 deliverable per se, but what do you think? Is that kubernetes site github pages?

**Comment by Tbr00ksy** [comment]
Link to boxnote where homepage refresh is being collaborated on.
https://ibm.box.com/s/0mw4ukq7f714j457rucwy5ncpfzp4bff

**Comment by jackjia-ibm** [comment]
@Tbr00ksy I know we are in middle of updating the video. Do you think we are ok to update the text changes of the website?

**Comment by Tbr00ksy** [comment]
@jackjia-ibm yes I think the text changes are good to go. You can embed the youtube video as well: https://www.youtube.com/watch?v=NX20ZMRoTtk&t=

The other video we were going to update can be published at a later time. 

Also, on the download page (https://zowe.org/download/) feel free to use the same text as on the homepage.

**Comment by alvin-tan** [comment]
@rpenny125 I heard similar feedback about folks struggling to get a quick understanding of Zowe and while we have some good documentation on the home page, I think a few mins of intro video would go a very long way in helping to address most of the initial questions about what Zowe is all about, what does it offer, etc.  Let us know your thoughts on this, we are proposing to move the intro video to the front (currently buried in the Doc section) as one of the ways to remedy the current limitation.

**Comment by jackjia-ibm** [comment]
@Tbr00ksy zowe.org homepage and download page are updated. please verify.

**Comment by Tbr00ksy** [comment]
updates verified and closing issue
