### ISSUE TITLE
Create a better zowe messaging strategy

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/community#33]
Currently the various APIs and UIs have different messaging and logging implementations.
We should create some clear and consistent standards for the apps to use.
We should consider:
- Globalisation - create a common set of message ids so we can do browser based translation independent from the server. I believe Matt has reserved the prefix OMP for this?
- Logging formats and service differentiators.

We should probably make a 'special interest group' or something where we can invite people create some guidelines and standards and possibly libraries and then each component can roll them out

**Comment by jplinardon** [comment]
I believe @hogstrom did some prep work relate to error codes. Looking for the material to link it here.

**Comment by alvin-tan** [comment]
> I believe @hogstrom did some prep work relate to error codes. Looking for the material to link it here.

https://github.com/zowe/zlc/blob/master/process/messageManagement.md

**Comment by jplinardon** [comment]
The Virtual Desktop and ZSS are part way through implementing the documented strategy.

**Comment by balhar-jakub** [comment]
Is anything missing? As far as I am aware the Web UI squad and the API ML squads are following these guidelines.

**Comment by balhar-jakub** [comment]
Closing as resolved as there is no update. If you feel something is missing please feel free to reopen.
