### ISSUE TITLE
Zowe Newsletter

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#347]
Working on initial plan in this wiki here: https://github.com/zowe/community/wiki/Zowe-Newsletter-Planning-Doc

Joe's first draft at an initial "Issue One": https://github.com/zowe/community/wiki/Zoweian-Issue-One

**Comment by NolanRogers** [comment]
Hello onboarding squad, I won't be able to make the call tomorrow. I unexpectedly had to take wed-Friday off. But I was thinking more about this and I'd like to own the Web UI section of the newsletter. Also I'd like to propose that we encourage squads to use the new "Roadmap" feature in Zenhub for epics. I think this would be great to see all the squads Roadmaps (with rough timelines, maybe by quarter)  and if we do go with that proposal, I would volunteer to own that part also.

**Comment by NolanRogers** [comment]
Closing as the Zoweian Newsletter is live now
