### ISSUE TITLE
Update the GitHub repo information on Zowe.org

### ISSUE THREAD

**Issue by nannanli** [zowe/community#36]
Due to the Liberty to Tomcat migration, several repos are archived and several are added. Therefore, we need to update the GitHub repo information on the Contribute tab on Zowe.org. Here are the changes that are required. 

### Remove 
Remove the following GitHub links and descriptions in the **Foundation (CI/CD)** section.

https://github.com/zowe/explorer-model 
https://github.com/zowe/explorer-server 
https://github.com/zowe/explorer-server-auth
https://github.com/zowe/explorer-server-tests 
https://github.com/zowe/explorer-utilities

### Add
Add the following GitHub links and descriptions in the **Foundation (CI/CD)** section. 

https://github.com/zowe/data-sets
The Spring Boot based data set APIs.

https://github.com/zowe/explorer-api-common 
Common explorer API components.

https://github.com/zowe/explorer-ui-server
A simple HTTPS server to serve Zowe Desktop Explorer plug-ins.

https://github.com/zowe/jobs
The Spring Boot based Jobs APIs.

**Comment by jackjia-ibm** [comment]
@nannanli @nkocsis   https://zowe.org/contribute/ is updated. Please verify.

**Comment by nannanli** [comment]
Thanks Jack! It looks great. Closing this issue now.
