### ISSUE TITLE
Zowe external certificate

### ISSUE THREAD

**Issue by AlbertoGCMF** [zowe/community#403]
Hello all,

We're installing a ZOWE v1.4.0 instance in our Mainframe instalation, using the certificates that the product provides for test. A few weeks ago, we start to try installing this version with an external certificate generated in Top Secret and signed for our internal CA, but we found some troubles when we try to start Zowe with this certificate. Seems the Eureka server can't recognize this new certificate and the handshake fails:

Ý33751832~ Problem making eureka request { Error: write EPROTO 5111066607577202689:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:KKaÂ Â Â Â[aÂ Â Â Â Â[Â[Â aÂ Â Â Â Â[Â[Â aÂ[Â[Â aÂ[Ã³mÂ Â Â£KÂ :1498:SSL alert number 46

Ý33751832~ 5111066607577202689:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:KKaÂ Â Â Â[aÂ Â Â Â Â[Â[Â aÂ Â Â Â Â[Â[Â aÂ[Â[Â aÂ[Ã³mÂ Â Â£KÂ :659:

Ý33751832~     at exports._errnoException (util.js:1020:11)                                                                         

Ý33751832~     at WriteWrap.afterWrite (net.js:806:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }                         

Ý33751832~ Error registering with eureka client. { Error: write EPROTO 5111066607577202689:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:KKaÂ Â Â Â[aÂ Â Â Â Â[Â[Â aÂ Â Â Â Â[Â[Â aÂ[Â[Â aÂ[Ã³mÂ Â Â£KÂ :1498:SSL alert number 46

Ý33751832~ 5111066607577202689:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:KKaÂ Â Â Â[aÂ Â Â Â Â[Â[Â aÂ Â Â Â Â[Â[Â aÂ[Â[Â aÂ[Ã³mÂ Â Â£KÂ :659:

Ý33751832~     at exports._errnoException (util.js:1020:11)                                                                        

Ý33751832~     at WriteWrap.afterWrite (net.js:806:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }                         

Ý33751832~ Error starting the Eureka Client { Error: write EPROTO 5111066607577202689:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:KKaÂ Â Â Â[aÂ Â Â Â Â[Â[Â aÂ Â Â Â Â[Â[Â aÂ[Â[Â aÂ[Ã³mÂ Â Â£KÂ :1498:SSL alert number 46

Ý33751832~ 5111066607577202689:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:KKaÂ Â Â Â[aÂ Â Â Â Â[Â[Â aÂ Â Â ÂÂ Â[Â[Â aÂ[Â[Â aÂ[Ã³mÂ Â Â£KÂ :659:

Ý33751832~     at exports._errnoException (util.js:1020:11)     

Maybe this is a problem with de keystore that we generate as external certificate. Someone found something similar to this?

This problem also make us question if it will be a possible to configure an external SAF certificate in next versions of Zowe, instead of the USS keystore. Is this in the development horizont for future Zowe releases?

Many thanks in advance,
Alberto

**Comment by Joe-Winchester** [comment]
@AlbertoGCMF  Tks for finding this problem and creating a git issue - It is in the area of Top Secret and the API layer springboot client so I've assigned it to the subject matter experts on those two areas (@MarkAckert and @plavjanik).  
Regarding your question
```
This problem also make us question if it will be a possible to configure an external SAF certificate in next versions of Zowe, instead of the USS keystore. Is this in the development horizont for future Zowe releases?
```
Yes we have heard this from other customers who want us to move away from USS keystores towards the ability to use SAF keystores which is in git issue https://github.com/zowe/zowe-install-packaging/issues/789.  This issue is not currently started but you add yourself as interested to the issue to track its progress.
