### ISSUE TITLE
unable to login to desktop version with error "Authentication failed for 1 types. Types: ["zss"]"

### ISSUE THREAD

**Issue by krutikasoman** [zowe/community#471]
**Describe the bug**
Getting error on all forms of login to Zowe. All issues show trouble with the generic password generated. Authentication failed for 1 types. Types: ["zss"]

**Steps to Reproduce**

1.Register and verify userID and Password
2. Try to login to Desktop version

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add server logs collected at the time of your problem.

**Web Browser Details (if the bug relates to Zowe Desktop usage):**
 - windows 10

**Comment by Joe-Winchester** [comment]
@krutikasoman - tks for creating this issue where you're having problems logging into the Zowe desktop.  There is a troubleshooting section in the doc https://docs.zowe.org/stable/troubleshoot/app-framework/app-known-issues.html#cannot-log-in-to-the-zowe-desktop that covers how to diagnose and troubleshoot desktop logon problems.  Can you follow the docs please and let us know if it describes a solution that works for you, and if not we can provide more help in how to look deeper.  Also let us know if the troubleshooting guide is clear enough or needs more work as we're always looking to make doc improvements.

**Comment by krutikasoman** [comment]
@Joe-Winchester , I have already reviewd the given link before opening an issue here. As I am new to this technology I did not understand how to open the log file.

Below is the solution mentioned in the link given by you.
To solve the problem, follow these steps:

Open the log file /zlux-app-server/log/zssServer-yyyy-mm-dd-hh-ss.log. This file is created each time ZWESVSTC is started and only the last five files are kept.

The document is not helpful for newbies I guess.

Note: I tried to login with same credentials in Desktop, CLI as well. both gave password issues.

**Comment by jplinardon** [comment]
Please provide details of the server setup you are connecting to.

**Comment by krutikasoman** [comment]
I am following get started with document mentioned below:
https://developer.ibm.com/tutorials/zowe-step-by-step-tutorial/

Server: 192.86.32.67

**Comment by jplinardon** [comment]
What were the results of your TSO login or SSH connection from the "Verify access to the mainframe" section:

Verify access to the mainframe
After you receive your login information, there are various ways to access the mainframe using credentials:

Access z/OS using a TN3270 Emulator IP: 192.86.32.67 & PORT: 23.

Access z/OS using an SSH client (PuTTY or GitBash for windows) using your credentials.

 ssh <username>@192.86.32.67

**Comment by krutikasoman** [comment]
@jplinardon it gives "Permission denied, please try again." twice and third time it gives error "Permission denied (publickey,password)."

The password given looks generic, Is there any way I can reset password and try again?

Thanks for the help!

**Comment by jplinardon** [comment]
Yes, but you need to get on Slack and make the request there.
Slack workspace name: Open Mainframe Project
Relevant channels:
#zowe-onboarding
#zowe-user
#zowe-dev

Pleaser remember to close this issue once you have obtained assistance.

**Comment by jplinardon** [comment]
Assistance is being provided in Slack, closing this issue.
