### ISSUE TITLE
Review generated AppScan Reports and OWASP dependency checks

### ISSUE THREAD

**Issue by jordanCain** [zowe/community#475]
All squads need to ensure their deliverables are being scanned by the build to generate the necessary reports. These reports must be checked by the squads. 

Reports to be reviewed: 

- AppScan Reports
- NPM Audit Scan Reports
- WICKED Scan Reports
- OWASP Scan Reports

https://github.com/zowe/community/security/advisories

**Comment by jplinardon** [comment]
@jordanCain is this meant as a recurring task, as a one time task to do a review, or as a one time task to establish a process?
Can you document links to the reports to review?
Any consideration for SonarCloud in this issue?

**Comment by jordanCain** [comment]
@jplinardon This is a recurring task that needs to be completed at least once in every PI cycle. 
The reports are all held in security advisories here https://github.com/zowe/community/security/advisories Though there is restricted access to these and the people who have access have instructions on how to review the reports (I can't remember off the top of my head who the person from your side of things has been given access but I'm pretty sure at east Sean has plus one more)

**Comment by jplinardon** [comment]
Thank you @jordanCain. @timgerstel is responsible for this recurring security review.
