### ISSUE TITLE
Update Zowe Web-UI Totorial with 1.0

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#48]
Work with IBM Ecosystem team to update the hands-on web-UI totrial system with 1.0. Ensure URLs are updated and ZSS component.

**Comment by Tbr00ksy** [comment]
@NolanRogers do you have an update for this issue? Is this still a work in progress?

**Comment by Tbr00ksy** [comment]
@NakulManchanda can this issue be closed?

**Comment by NolanRogers** [comment]
CC
@reetchow @1000TurquoisePogs

**Comment by NakulManchanda** [comment]
we did updated it couple of times since it opened,
in zlux recently all apps are optional and need to add step switch trivial auth to zss-auth
so i still need to verify latest steps and try out myself, will close couple days after latest RC release

**Comment by NolanRogers** [comment]
@NakulManchanda & @1000TurquoisePogs  have been handling this issue by issue in slack, and can close this and open new specific issues when they arise
