### ISSUE TITLE
Resolve and agree on how milestones should be used to track and plan sprint and release gitissues

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#481]
**Is your feature request related to a problem or limitation? Please describe.**
Currently milestones are used inconsistently between github.com/zowe repositories and squads.  This issue is to converge on a single approach.

**Describe the experience you'd like**
Plan work as part of a PI by assigning an overall PI for issues.
Move work into PI sprints as sprints begin to track sprint progress
Associate which work is planned to be included in a release to allow tracking the release and the sprint

**Additional context**
Some squads use labels to assign to releases.  Others use milestones.

**Comment by stevenhorsman** [comment]
Is the main issue here that the 'client' components ie Zowe Explorer, CLI & co. are released and distributed on a different schedule to the 'server' components. In which case does it make sense to try and merge them all into a single set of milestones?

**Comment by balhar-jakub** [comment]
I believe we reached a conclusion to use Milestones but it's more to track the ongoing work than actual releases. The work done in the release is being outlined and highlighted in demos and Changelogs. And also partially by the agreement on how to use Zenboard for the whole Zowe.
