### ISSUE TITLE
Zowe Joint PI Planning

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#497]
Create a joint PI Planning session with the Open Source Community

**Comment by armstro** [comment]
What was discussed at ZLC 

Proposal of next PI Planning - cross squad - one event - request temp working group formed for Project Managers to organize - outline: 
June 25, 26 and 29 (Thu, Fri, Mon) - Assume a few hrs per day mid morning to allow for time zones 
Prep session 2 weeks or 1 month prior with squads 
Day 1  - Public session - Business Context involving the ZLC - PMs giving "Train Vision"  
Day 2 - Checkpoint maybe 15-20 per squad allow for Q&A on priorities, identified cross squad inter-dependencies  
Day 3 - Public session Play out
Public - Maybe we do broadcast via webex/ zoom but customer input via slack/chat ? vs live audio Q&A that drags down a meeting.

**Comment by armstro** [comment]
Some suggestions 
- Some SAFe education for those not familiar 
- Possible use of surveys to the open community BEFORE day 1 to help gauge interest in candidate items 
- Public sessions be broadcast only (not verbal Q&A) - maybe slack or chat Q&A - the point is to make the session efficient 
- Day 2 not public? Squads only?

**Comment by balhar-jakub** [comment]
I am closing this issue as this is routinely happening now. 

Feel free to reopen, if there is something missing.
