### ISSUE TITLE
High Availability and Sysplex Distributor Questions

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#501]
Please record your questions for Gus Kassimis

**Comment by 1000TurquoisePogs** [comment]
Some questions:
* If we were to pre-req sysplex distributor, what is its availability? Besides configuration, is it available on all lpars that run in sysplex, or is it a commercial product that not everyone will have?
* I'm seeing parallels between what it does and what eureka does (as we see in api mediation layer). Can you elaborate on:
    * round robin capability
    * what the health-check actually is (such as, do programs need to code for this or is this a 0-code-modification health check)
    * hot backup as opposed to round-robin
    * ability to have an affinity for one of the servers so that the same client tends to go back to the same server
    * recommendations for stateful servers versus stateless servers in terms of accomplishing HA with good performance & data being current
    * is there a story for off-host? Such as, what if we wanted to run some content on zlinux, some on z/os, but have that be invisible to the end users by having them just be different routes to the same IP or hostname?

**Comment by nkocsis** [comment]
Meeting Minutes and charts here:
https://github.com/zowe/community/blob/master/Project%20Management/Architecture%20Call/System_Demo_Recordings.md

**Comment by 1000TurquoisePogs** [comment]
Should we close this since the event happened?
