### ISSUE TITLE
Zowe Webinars

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#52]
OMP would like to schedule a series of webinars/tech talks. 
List of potential webinars: https://ibm.box.com/s/14yg3r5yfzaxul60uizt71u64i0xv1ni

**Comment by Tbr00ksy** [comment]
@armstro you mentioned that you wanted to revisit this topic. Here is the issue with a list of potential webinar topics from the last TDM.

**Comment by balhar-jakub** [comment]
Aren't we already doing this now @RASakach ?

**Comment by RASakach** [comment]
@balhar-jakub I would say - yes - the Quarterly Zowe Webinars offers an opportunity to present Focus Topics / discussions 4 times per year.

I have copied the link to these notes as a reference for future topics.

This issue can be closed.

@armstro - FYI
