### ISSUE TITLE
Analyze Code Freeze & RC strategies in other Open Source Communities

### ISSUE THREAD

**Issue by Kyle-Woodworth** [zowe/community#520]

**Comment by MarkAckert** [comment]
I will setup a call with LF team where we can talk about their experiences and best practices in CI and Release Management. @Joe-Winchester @1000TurquoisePogs @jackjia-ibm @stevenhorsman Please add comments if you have other questions or topics you'd like to explore, or if I got something wrong :) 

Questions:
- How do you work with heterogenous communities? Polyglot codebase, with different pipelines, artifacts, etc. 
- Do you use software other than Jenkins for visualizing build results, pipelines, etc... Dashboard software?
- How do you typically go about releasing (RC) process? The period where you code freeze and harden. 
- How do you synchronize code releases with related materials like websites?

**Comment by jackjia-ibm** [comment]
I have question related how to handle sub-components releases in efficient way. For example, we have several repositories related to explorer UI plugins and APIs. We currently are releasing them independently. For example, a base dependency changed, we will release it as newer version and then update the upstreams to use the newer version. This results in many branches merging, pull requests when we updating base dependencies.

If we put all those repositories into one repository, it will solve the above issue but may bring in some other problems or concerns:

- How do we isolate the commit changes to only build the sub-component itself and upstreams.
- How do we avoid code coupling among sub-components?
- How to isolated the SonarQube coverage report by sub-components. One sub-components coverage failure shouldn't affect others.

**Comment by MarkAckert** [comment]
Short summary of our call with LF:

- Many of the pain points we're encountering are normal for a new project. We'll improv as we continue to work through them.
- Adding another nightly build which is "RC-like" (i.e., stable release versions) is valuable. We would expect "RC-like" nightly built to pass, while the "staging" nightly build (SNAPSHOTs) can fail frequently. Failing frequently on the "staging" nightly will be pretty normal.
- There's no particularly better way LF knows of for handling polyglot codebase. We are mimicking other package aggregations (like maven POM), but we have to roll our own solution to meet the challenge.
- Jenkins is used for visualization, with builds triggering other builds. You can trace build trees this way. No other software.
- LF experience with RC process is very similar to ours. To improve RC turnaround time, merge earlier and fail earlier. To reduce chance of failure, getting teams w/ dependencies to work together in a long-running packaging branch is best.
- No Github robots / ChatOps
- Re: monorepo, LF's opinion is to avoid this. It solves some problems and creates others; in particular component build complexity increases.

Actions:

- Create the second nightly build
- Better define the social contracts within community on RCs, dependencies across components.

**Comment by Kyle-Woodworth** [comment]
Second nightly build - Systems Squad 20PI3
Better social contracts - TBD
