### ISSUE TITLE
Attach names to each binary dependency

### ISSUE THREAD

**Issue by Kyle-Woodworth** [zowe/community#521]

**Comment by 1000TurquoisePogs** [comment]
Sounds like we mean "which person is the primary point of contact for each package"

**Comment by jackjia-ibm** [comment]
Current people we are contacting before building RC:

- Explorer API/Plugins - Jordan
- Zlux - James
- APIML - Mark / Petr P.
- CLI - Mark / Fernando

Would like to suggest the owner of the component(s) to create PR and define the static version they want to release on `rc` branch.

**Comment by 1000TurquoisePogs** [comment]
zss, xmem = also james

**Comment by Kyle-Woodworth** [comment]
Binary Dependencies: https://github.com/zowe/zowe-install-packaging/blob/master/manifest.json.template

Scope: Find one name for each BD above, place in file near the above template.  Contributors.md?

**Comment by Kyle-Woodworth** [comment]
Done
