### ISSUE TITLE
Remove versions from the manifest file

### ISSUE THREAD

**Issue by Kyle-Woodworth** [zowe/community#522]

**Comment by MarkAckert** [comment]
I don't think we should do this; replacing our current manifest will add more complexity to our build processes with minimal gain. If there's a reason teams can't update the manifest directly or if they have other reservations about it, I'd like to address those instead.

**Comment by jackjia-ibm** [comment]
I agree with Mark and think this is not a good approach for now until we evaluate the proposal suggested.

**Comment by Kyle-Woodworth** [comment]
Cadence is important.  Update 1 week before?  On release?  

Each squad to decide.

**Comment by Kyle-Woodworth** [comment]
Closed due to above comments
