### ISSUE TITLE
Analyze how we can do better testing in the open

### ISSUE THREAD

**Issue by Kyle-Woodworth** [zowe/community#523]

**Comment by Kyle-Woodworth** [comment]
Consider also how we can use data from multiple sources to perform more thorough testing

**Comment by Kyle-Woodworth** [comment]
Consider how tests will be scheduled to be a good citizen on Marist's infrastructure & to ensure all tests are periodically run

**Comment by jackjia-ibm** [comment]
There are several github issues I believe are part of this topic, but we may need more to fully fullfil the original intention of this issue.

- Investigate and run CLI plugins test on Marist https://github.com/zowe/zowe-install-packaging/issues/1201 and https://github.com/zowe/zowe-install-packaging/issues/689
- Build IMS plugins and have them been tested on Marist https://github.com/zowe/zowe-install-packaging/issues/1200
- Import app framework tests currently running in-house https://github.com/zowe/zowe-install-packaging/issues/700. Also related issues
  - Cross browser test support https://github.com/zowe/zlc/issues/159
  - Infrastructure: Selenium Grid https://github.com/zowe/zowe-install-packaging/issues/701
- Migrate explorer apis/plugins to Marist https://github.com/zowe/zowe-install-packaging/issues/878

**Comment by Kyle-Woodworth** [comment]
Two goals:

1. More confidence as we progress through a PI that overnight builds run exhaustive test suites.
2. Delivering content should pass smoke tests that don't consume too many resources.

Issues:
Some tests are tied to a framework not in the open community. (https://github.com/zowe/zowe-install-packaging/issues/700).  This would allow people to see better.

Todo: Ask each squad to look into how much testing is in private (in-company) vs visible to open source.

After that: Understand the effort to move those tests into the open, performance, capacity, etc.

**Comment by Kyle-Woodworth** [comment]
We need to acquire the ability to test Safari (Apple) & Microsoft Edge (Windows).  Possible solution is Github actions.

What kind of system tests are people performing?  How can we move them into the open?
Discussion to happen in Systems Squad.
