### ISSUE TITLE
Provide training to Zowe Developers

### ISSUE THREAD

**Issue by Kyle-Woodworth** [zowe/community#525]

**Comment by stevenhorsman** [comment]
What is the requirement here? What do you want to be delivered?

**Comment by 1000TurquoisePogs** [comment]
Does this mean "training about how jenkins works", or "training about how our tests work, where they are, what they do"? Could be two separate things.
Another good one never mentioned yet is github bots. Different repos use different ones. Are there some good ones others can learn about to use too?

**Comment by Kyle-Woodworth** [comment]
We were having build breakages that weren't found for some time, and took some time to fix.

Scope: Education on good contributing/committing habits?  Squads, pull requests, testing, etc.  

How do you begin contributing to Zowe?

If something changes on Zowe install packaging, the reviewer should ensure tests pass

Consider both education and guidelines/docs that should follow.

**Comment by Kyle-Woodworth** [comment]
Sign-off when you become a Zowe committer that you have had 'best practices' training?  (not set in stone yet) - What does best practices mean?  Maybe TSC?

Now - go to jenkins, use build with function by jenkins, input zowe build to test
After move to LF jenkins, this option is disabled for committers
This is accepted for now.  Many requests have been made, all rejected.  Mark to raise this again.

**Comment by Kyle-Woodworth** [comment]
Steve H provided training on running builds, what basic builds are, how to update manifest.

Ideas
- Update doc to be more committer focused?
- How do we be more transparent to outsiders on PI objs, sprint dates, what squads work on, etc?

Issues are already in the doc squad for 20PI3
