### ISSUE TITLE
Document the purpose of the many jobs running in Jenkins

### ISSUE THREAD

**Issue by Kyle-Woodworth** [zowe/community#527]

**Comment by jackjia-ibm** [comment]
I cleaned up some of the jobs in Jenkins.

- Some jobs didn’t run for over a year, I may move it to Archived folder. Some jobs I moved to Test folder based on the job name.
- Added some descriptions to the jobs.
- Created some Views to put relevant jobs together.

**Comment by 1000TurquoisePogs** [comment]
Here are a few
* zlux-core: It is used to build PRs for individual app server framework repos, or for entire zlux-core pax archives. By default, it builds from staging unless PRs are specified. It uses the scripts in the repo "zlux-build" to do the building of the core. Maybe, we could put a Jenkinsfile into "zlux-build" instead?
* zlux-plugins: It is used to build one of the apps at a time, but is designed one-per-repo currently.  Staging by default, unless a PR is specified.
* zlux-core-tagged: outdated, we were using it for testing. If we can move to a Jenkinsfile, it would be possible to just consolidate to zlux-core, but it seems like the fact that the framework is comprised of multiple repos makes the use if a single Jenkinsfile hard.
* zlux-plugins-tagged: also outdated and used for testing. Same thing.

* zss: this one does use a Jenkinsfile. It builds zss & zis, utilizing the zss and zowe-common-c repos. The pax includes the zssServer binary file, but also contents meant to go into datasets for loadlib and samplib, and some zss plugin-related scripts.

* zlux folder: currently used for the rc and release process.
    * zlux-core-release: It builds a release from rc branches, with a version given.
    * zlux-plugins-release: it's the same thing as core, but for plugins.
    * zlux-git-release: It can merge staging into rc, merge rc into master, and tag the repos.

**Comment by Kyle-Woodworth** [comment]
Consider polling the squads for the list of jenkins jobs they use and their purpose

Need help from CLI - Mark will cover.

**Comment by Kyle-Woodworth** [comment]
Will connect to Joe's contributor guidelines - Committer Playbook

**Comment by Kyle-Woodworth** [comment]
Sean to identify problematic jobs and review with Jack/Market

**Comment by Kyle-Woodworth** [comment]
Low priority, will migrate to jenkins file pattern.  Until that day, groovy script within jenkins job.
