### ISSUE TITLE
Create guidelines for blog inclusion on Zowe medium blog for core vs. ecosystem content

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#545]
**Is your feature request related to a problem or limitation? Please describe.**
https://medium.com/zowe

**Describe the experience you'd like**
Provide a set of guidelines and terms and conditions for an article's inclusion in the site regarding how it describes Zowe core content, open source content, ...
Provide a set of guidelines and terms and conditions for an article's inclusion in being flagged as "zowe ecsostem" where the blog discusses an offering that is not part of core Zowe, such as one that has a conformance badge, or one that discusses enterprise support for core Zowe.

**Comment by balhar-jakub** [comment]
Can we close this one?

The criteria seem to be here: https://github.com/zowe/community/blob/master/blogging/blog_guidelines.md

**Comment by Joe-Winchester** [comment]
Yes we should have closed this a while back, as the blogging guidelines have been created.  Tks for picking up on this.
