### ISSUE TITLE
Create playback deck for revised Zowe install/packaging design

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#56]
**Is your feature request related to a problem or limitation? Please describe.**
There are a number of issues that have been identified with the current way that Zowe is packaged and installed for its z/OS components.

**Describe the experience you'd like**
We are documenting the install issues here"
https://github.com/zowe/zowe-install-packaging/wiki/Install-Experience

Our first deliverable is a playback deck and material and giving that to audience(s) to validate and refine

**Comment by Tbr00ksy** [comment]
[Cupids Playforward.pptx](https://github.com/zowe/community/files/3128115/Cupids.Playforward.pptx)

the recording can be viewed here: https://zoom.us/recording/share/Lf8BmxIvmpXjTwJNfqXvvB-_jgkEMEE3Id3G_VRkiT2wIumekTziMw?startTime=1556031635000

**Comment by balhar-jakub** [comment]
Is this issue still relevant @jackjia-ibm ?

**Comment by jackjia-ibm** [comment]
Thanks Jakub, you are right, many contents here are already changed or fixed. Closing now.
