### ISSUE TITLE
Zowe should have a path to allow users to select nightly or stable forward releases

### ISSUE THREAD

**Issue by MarkAckert** [zowe/community#57]
Details to be filled out

**Is your feature request related to a problem or limitation? Please describe.**
A clear and concise description of what the problem or limitation is. Ex. I'm always frustrated when [...] happens, or I wish I was able to do [...] with Zowe.

**Describe the experience you'd like**
A clear and concise description of what you want to happen when you encounter the prior problem or limitation.

**Describe alternatives you've considered**

**Additional context**

**Comment by balhar-jakub** [comment]
@jackjia-ibm @FlappiTomic Do you know whether this is done, or whether it's an issue that still exists?
