### ISSUE TITLE
MQ APIs listed on conformance page as CLI

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#577]
@solsu01 commented on [Wed Apr 22 2020](https://github.com/zowe/zlc/issues/181)

Looks like an error:
![image](https://user-images.githubusercontent.com/35504644/79979357-67724600-846f-11ea-9db0-95cb9b0f35db.png)

---

@Joe-Winchester commented on [Mon Apr 27 2020](https://github.com/zowe/zlc/issues/181#issuecomment-619967801)

@solsu01 - yes it would be better if the text was "IBM MQ for z/OS" and the link was to the article https://community.ibm.com/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=adb8e2d4-f327-a93b-fdaa-b5da0e80d614&forceDialog=0 that describes how to surface the MQ APIs onto the API catalog which are valid for the 2019 conformance program

---

@Joe-Winchester commented on [Mon Apr 27 2020](https://github.com/zowe/zlc/issues/181#issuecomment-619968332)

@jmertic - is the Zowe Conformance web page in a github repo so Sujay and/or myself could create a PR for updating the text and links on the MQ CLI tile ?

---

@jmertic commented on [Mon Apr 27 2020](https://github.com/zowe/zlc/issues/181#issuecomment-619968852)

It is a GH repo - https://github.com/openmainframeproject/omp-landscape. Feel free to submit a PR for any changes needed.

---

@jmertic commented on [Mon Apr 27 2020](https://github.com/zowe/zlc/issues/181#issuecomment-619969355)

I will say that any links should point to an organization property ( i.e. with that having a Zowe logo, it should point to a Zowe/OMP location vs IBM )

---

@dkelosky commented on [Mon May 11 2020](https://github.com/zowe/zlc/issues/181#issuecomment-626721618)

This also seems like a problem for the App framework:
![image](https://user-images.githubusercontent.com/14940561/81570498-ab6db200-936e-11ea-89eb-2827f4e81790.png)

Are the IMS API & CLI conformant?  Should they appear there as well?

---

@jmertic commented on [Mon May 11 2020](https://github.com/zowe/zlc/issues/181#issuecomment-626756734)

For any additional apps needed, you should submit a conformance application so they are reviewed. 

---

@dkelosky commented on [Tue May 12 2020](https://github.com/zowe/zlc/issues/181#issuecomment-627390623)

Thanks.  Since this is a Zowe repo based app - who would submit?  Is it typically the folks that seeded the repo? 

---

@Joe-Winchester commented on [Tue May 12 2020](https://github.com/zowe/zlc/issues/181#issuecomment-627401967)

@dkelosky - I think it was the IBM MQ team who submitted the initial Zowe Conformance 2019 for the MQ CLI and MQ REST APIs.   @jmertic - I imagine they would have got an announcement e-mail for the Zowe Conformance v1 program when that went live a week or so ago ?  
For the IMS CLI and IMS Operations API we do want to get conformance for them also - I'll e-mail Haley and cc you as she will know more about whether that's in plan or not.  

---

@Joe-Winchester commented on [Wed May 20 2020](https://github.com/zowe/zlc/issues/181#issuecomment-631492577)

Moving this issue to `/community` as it doesn't feel it is the ZLC responsibility to track this.

**Comment by Joe-Winchester** [comment]
MQ is a z/OS runtime, and it has 2019 conformance for CLI, AppFramework and API Mediation Layer.  The badge should just say "IBM MQ for z/OS" for all three.   

I expect the reason it states "IBM MQ for z/OS for Zowe CLI" is a copy and paste error or misunderstanding when the conformance was submitted and titled incorrectly.  It'd be good to have the 2019 badges updated and I'd be happy to do this, however I'm not sure which repository they are held in.  I see them in raw format at https://landscape.openmainframeproject.org/category=zowe-conformant&format=logo-mode&grouping=category so the fix would be to change "IBM MQ for z/OS for Zowe CLI" to just be "IBM MQ for z/OS".  This is the same that other offerings such as CA Endeavor have done where conformance exists for >1 component.

**Comment by jmertic** [comment]
Feel free to submit a PR for any updates needed.

**Comment by Joe-Winchester** [comment]
Tks @jmertic - where is the repo that holds the badges ?

**Comment by balhar-jakub** [comment]
@Joe-Winchester It looks like for the CLI this issue is closed. 

As for the App Framework and API ML there is no conformance badge for the MQ.

**Comment by Joe-Winchester** [comment]
@balhar-jakub - yes the CLI has conformance which is great (I think @MikeBauerCA did the submission for that) but there isn't an APIML conformance.  We did have one for 2019 conformance based on the [blogpost instructions](https://community.ibm.com/community/user/integration/viewdocument/exposing-the-mq-rest-api-via-the-zo?CommunityKey=b382f2ab-42f1-4932-aa8b-8786ca722d55) however looking at the site now the formatting is a bit off, although the [PDF](https://community.ibm.com/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=adb8e2d4-f327-a93b-fdaa-b5da0e80d614&forceDialog=1) looks good.

My bad for letting this lapse,  I'll ping Matt to see if he wants to re-submit for v1 and I'll also do a quick test just to make sure it's going to work OK with a Zowe v1.

**Comment by balhar-jakub** [comment]
@Joe-Winchester Any update here?

**Comment by balhar-jakub** [comment]
Closing as the MQ API is listed including the V2 conformance.
