### ISSUE TITLE
Failed to reach the auth services host for address

### ISSUE THREAD

**Issue by Gie-Indesteege** [zowe/community#59]
Hi,
I started the tutorial (https://developer.ibm.com/tutorials/zowe-step-by-step-tutorial/), but encountered some problems. (Working on Windows 7).

The biggest problem, preventing me to continue the tutorial, is when starting up the zLUX server:

[2019-03-05 11:31:26.801 _zsf.bootstrap WARNING] - Could not spawn {"path":"C:\\Temp\\Zowe\\zlux\\zlux-app-server\\bin\\zssServer.sh","once":true}: spawn UNKNOWN
[2019-03-05 11:31:26.802 _zsf.network INFO] - HTTP config valid, will listen on: 0.0.0.0
[2019-03-05 11:31:26.808 _zsf.network INFO] - HTTPS config valid, will listen on: 0.0.0.0
[2019-03-05 11:31:26.809 _zsf.bootstrap INFO] - Using Certificate: C:\Temp\Zowe\zlux\zlux-app-server\deploy\product\ZLUX\serverConfig\zlux.keystore.cer
[2019-03-05 11:31:32.236 _zsf.proxy WARNING] - Failed to reach the auth services host for address 192.86.32.67:8542
could not start the server:  Communication with 192.86.32.67:8542 failed: Error: connect ECONNREFUSED 192.86.32.67:8542

Did the ZSS port number change? or is there another issue?

thanks for considering this problem 
Gie 

**Shell Environment Details (if the bug relates to CLI):**
 - Technology:  powershell and bash
 - OS: Windows 7

**Comment by 1000TurquoisePogs** [comment]
I suspect this is because in Zowe 1.0.1, ZSS does not by default listen on an external IP, but instead 127.0.0.1.
I think this section of the app server readme explains the solution, but please keep this updated if not: https://github.com/zowe/zlux-app-server/tree/staging#setup-for-zss

**Comment by 1000TurquoisePogs** [comment]
I'll keep this open until the link you referenced has these changes.

**Comment by Gie-Indesteege** [comment]
According to the tutorial -> 4. Run the server
"At this point, all server files have been configured and apps built, so ZSS and the app server are ready to run.
From the system with the zLUX Proxy Server, start it with a few parameters to hook it to ZSS. Make sure to replace “8542” with your zss port and “192.86.32.67” with your z/OS mainframe server IP address where ZSS is installed."

The zLUX Proxy Server should start on my Windows machine, the ZSS should be available and running on a z/OS mainframe server, provided by ZOWE/IBM?, for testing/discovering with the mentioned tutorial. (I did receive a userid and password for testing).

Whether I use
 `nodeServer.sh -h 192.86.32.67 -P 8542 -s 5000`
or
`nodeServer.sh -h 127.0.0.1 -P 8542 -s 5000`
I receive the same error message.

**Can you tell me where the provided ZSS server is running (IP and port), so that the zLUX Proxy server can attach and authenticate?**

Thank you
Gie

**Comment by Tbr00ksy** [comment]
@1000TurquoisePogs can this issue be closed?

**Comment by Gie-Indesteege** [comment]
Hi,

because of other project priorities, I could not continue the trial of zowe
based on the tutorial. The last test I did still failed, so for me, this
issue is not closed.
Perhaps other users of this tutorial and zowe trial can go on with the
tests;

Kind regards
Gie


                                                                           
             Tim Brooks                                                    
             <notifications@gi                                             
             thub.com>                                                  To 
                                       zowe/community                      
             21/08/2019 23:39          <community@noreply.github.com>,     
                                                                        cc 
                                       Gie-Indesteege                      
             Please respond to         <gindesteege@abis.be>, Author       
              zowe/community           <author@noreply.github.com>         
                  <reply                                           Subject 
             +AKMYB2EHIYWS5BJY         Re: [zowe/community] Failed to      
             MYKQGW53NLWKFEVBN         reach the auth services host for    
             HHBR7Y2T4@reply.g         address (#59)                       
                ithub.com>                                                 
                                                                           
                                                                           
                                                                           
                                                                           
                                                                           




@1000TurquoisePogs can this issue be closed?


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
