### ISSUE TITLE
EPIC: Mitigation of Non-EPL 2.0 Dependencies

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#6]
parent of gizafoundation/api-layer#66
parent of gizafoundation/api-layer#48
parent of zowe/zlc#17
parent of zowe/zlc#24
parent of zowe/zlc#25
parent of zowe/zlc#26

**Comment by nkocsis** [comment]
These are all the issues that need to be resolved to get us to full EPL 2.0

**Comment by stevenhorsman-ibm** [comment]
#parent of https://github.com/gizafoundation/api-layer/issues/66

**Comment by supmi01** [comment]
Thanks @stevenhorsman-ibm and #48 as well, it's removing CA proprietary libs - prerequisite to go EPL.2 as well. Potentially removing dependency on WAS Liberty of IBM Atlass servers - once we have that defined right.

**Comment by supmi01** [comment]
#parent of gizafoundation/api-layer#48

**Comment by Tbr00ksy** [comment]
@nkocsis @stevenhorsman @supmi01 can this issue be closed out with the release of 1.0.0?

**Comment by stevenhorsman** [comment]
All the children are closed now
