### ISSUE TITLE
Unable to connect to Zowe API mediation Layer

### ISSUE THREAD

**Issue by dsegoviaMF** [zowe/community#604]
Usually we have once times a week errors connecting to Zowe. We attach the error messages captured during the connection errors.

![zowe-error](https://user-images.githubusercontent.com/60257743/84802265-a00e4600-b000-11ea-8fa0-f71c8c446275.jpg)

Somebody has the same problem?

**Comment by balhar-jakub** [comment]
Would you mind moving this issue to the [api-layer](https://github.com/zowe/api-layer) repository? 
This seems like somehow linked to the API Mediation Layer.

**Comment by dsegoviaMF** [comment]
Post Moved! Thanks!
