### ISSUE TITLE
Marist System Preparation

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#64]
- Parent of https://github.com/zowe/community/issues/87 - Have License and Contract Signed with Marist College Build Environment 
- Parent of https://github.com/zowe/zowe-install-packaging/issues/476 - Install TSS/ACF2 On Marist College Build Environment
- Parent of https://github.com/zowe/zowe-install-packaging/issues/477 - Verify If Zowe Pre-reqs Are Installed Properly on Marist College Build Environment
- Parent of https://github.com/zowe/zowe-install-packaging/issues/478 - Create Snapshot for LPAR from Marist College Build Environment
- Parent of https://github.com/zowe/zowe-install-packaging/issues/474 - Migrating Pax Packaging to Marist College Build Environment
- Parent of https://github.com/zowe/zowe-install-test/issues/79 - Migrating Smoke Test to Marist College Build Environment
- Parent of https://github.com/zowe/zowe-install-test/issues/80 - Improve Smoke Test to Test TSS/ACF2 With Marist College Build Environment

**Comment by jackjia-ibm** [comment]
All works are done.
