### ISSUE TITLE
Submit conformance for MQ API

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#676]
**Is your feature request related to a problem or limitation? Please describe.**
Zowe 2019 conformance had MQ APIs included

**Describe the experience you'd like**
Get conformance for v1 MQ

**Additional context**
Zowe lifecycling is available in v1 so the solution for static onboarding may be enhanced to include lifecycling

**Comment by balhar-jakub** [comment]
Any update here @Joe-Winchester 

Plan for this PI?

**Comment by Joe-Winchester** [comment]
Hi @balhar-jakub , see https://github.com/zowe/community/issues/577.   I'll ping Matt Lemming who did the last submission for 2019 conformance to see if he wants to do it for v1 and if not I'll do some testing and submit the conformance badge.
