### ISSUE TITLE
DB2 plugin feature to ececute DB2 utilities also

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#689]
**Is your feature request related to a problem or limitation? Please describe.**
Limitation

**Describe the experience you'd like**
I would like to execute DB2 utilities from ZOWE CLI. Like Load and Unload, Reorg, Runstat, Copy, Recover, Report, etc. Those are usually part of our automation scripts.

**Describe alternatives you've considered**
zowe db2 utility uload tablespace --tablespace <mytablespace> --hlq <unload dataset prefix> --from <table> --fields <fieldlist> --when <sql query condition>....

_(of course I can execute them by running a JCL, but having a command for it would make programming easier)_

**Additional context**

**Comment by Joe-Winchester** [comment]
@zszabo14 - many thanks for raising this enhancement request.  The DB2 CLI is part of the https://github.com/zowe/zowe-cli-db2-plugin repository so I'll copy this issue there so the squad who looks after the plugin can respond to the issue.

**Comment by spufidoo** [comment]
Have you tried calling IBM-supplied stored proc, SYSPROC.DSNUTILS? That was provided to enable the invocation of utilities.

**Comment by zszabo14** [comment]
> 
> 
> Have you tried calling IBM-supplied stored proc, SYSPROC.DSNUTILS? That was provided to enable the invocation of utilities.

Can you please show any example?

**Comment by MikeBauerCA** [comment]
Closing since this was moved to the zowe-cli-db2-plugin repo.
