### ISSUE TITLE
Zowe Blog - Zowe CLI plug-in for z/OS Connect EE

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#69]
Blog read for OMP/LF promotion.

Link: https://developer.ibm.com/mainframe/2019/04/11/zowe-cli-plug-in-for-z-os-connect-ee/

**Comment by Tbr00ksy** [comment]
Social promotion only - not to be added to OMP blog page.

**Comment by Tbr00ksy** [comment]
https://twitter.com/tbr00ksy/status/1146040088842973188

https://www.linkedin.com/feed/update/urn:li:activity:6551805434007740416

**Comment by christinevblum** [comment]
I will get it scheduled
