### ISSUE TITLE
Zowe can crash z/OSMF?

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/community#698]
Multiple people have seen an issue where Zowe and z/OS MF can crash each other. From Sean: "The reason appears to be that a semaphore is being used incorrectly when caching classes on a shared filesystem, so the recommendation was to either have zosmf on a different filesystem from zowe, or to use the JVM_OPTION=-Xshareclasses:none on one or more of the servers."
It seems to have happened in 1.12 as everyone we'd heard it from hit the problem when upgrading from 1.11 to 1.12.
I’ve heard of someone who also got it upgrading to 1.12: They get the error when they have VERIFY_CERTIFICATES=true. If VERIFY_CERTIFICATES as false, but set external certificates in env file, it would also fail. It looks like whenever it’s using certificates, it fails, but not with VERIFY_CERTIFICATES=false and no external certificates.

**New info: It seems like the cases where this happens and we've been able to check have all been running under IZUSVR, and as https://github.com/zowe/community/issues/698#issuecomment-663004822 Vit has found that switching to ZWESVUSR as our default configuration is set up fixes the issue, which sounds like great news as only customers using a non-recommended configuration are hitting the problem**

We know of a workaroundin z/OSMF - update: `/var/zosmf/configuration/local_override.cfg`
and add a new line
`JVM_OPTIONS=-Xshareclasses:none`
which seems to fix it for everyone, but I don’t think that’s a real solution as it’s not something we can fix on Zowe and I don’t think customers will want us requiring configuration changes of other products in our holddata, even if we get coverage so they all see it.

I think we urgently need to doc the problem for past releases, and try and get a fix in 1.14 (can we just add -Xshareclasses:none in the start scripts all our java components?) as it seems like a pretty severe issue.

**Comment by Joe-Winchester** [comment]
I've written a troubleshooting guide PR here https://github.com/zowe/docs-site/blob/user/joewinchester/xshareclassesnon/docs/troubleshoot/troubleshoot-zos-services.md.   I've also raised a question in an IBM slack channel for the team that takes care of the IBM j9 VM on z/OS.  I'll post any replies here.

**Comment by vit-tomica** [comment]
I know about a user that had this problem when running Zowe and z/OSMF under the same userid (IZUSVR). The problem disappeared when a separate userid (ZWESVUSR) was created for Zowe.

**Comment by pierremontel** [comment]
I have had the same problem with the Zowe version 1.13. 
I also have different userid for z/osmf and zowe. 
Zowe was killing z/osmf which tries to restart again and again.
After doing the workaround in z/OSMF - update: /var/zosmf/configuration/local_override.cfg
and add a new line
JVM_OPTIONS=-Xshareclasses:none

All is working fine. Both tasks remains up and running.

**Comment by Joe-Winchester** [comment]
@pierremontel - do you still have your environment available ?  If so can you put z/OSMF back to where it was and try changing Zowe so that it's 5 Java runtimes use -Xshareclasses:none.  If this works for you we can change this as the default for Zowe itself going forward.  The instructions to change Zowe's startup require modifying three `start.sh` scripts and are at: https://github.com/zowe/docs-site/blob/user/joewinchester/xshareclassesnon/docs/troubleshoot/troubleshoot-zos-services.md.

**Comment by pierremontel** [comment]
@Joe-Winchester - I have done the changes as indicated and restart z/OSMF and then Zowe.
Here is the result:
$HASP100 ZWESVSTC ON STCINRDR                                           
IEF695I START ZWESVSTC WITH JOBNAME ZWESVSTC IS ASSIGNED TO USER        
ZWESVUSR, GROUP ZWEADMIN                                                
$HASP373 ZWESVSTC STARTED                                               
ACF9CCCD USERID ZWESVUSR IS ASSIGNED TO THIS JOB - ZWESVSTC             
IEF403I ZWESVSTC - STARTED - TIME=16.25.08                              
JVMSHRC364E SH_OSCachesysv::acquireWriteLock() call to j9shsem_wait     
331                                                                     
on semid 69636 has failed with error -328433.                           
                                                                        
JVMDUMP039I Processing dump event "traceassert", detail "" at 332       
2020/07/28 14:25:26 - please wait.                                      
                                                                        
JVMDUMP032I JVM requested System dump using 'IZUSVR.JVM.IZUSVR1.D20072  
333                                                                     
8.T142526.X&DS' in response to an event                                 
                                                                        
IGD101I SMS ALLOCATED TO DDNAME (SYS00011) 334                          
        DSN (IZUSVR.JVM.IZUSVR1.D200728.T142526.X001     )              
        STORCLAS (EAV) MGMTCLAS (        ) DATACLAS (        )          
        VOL SER NOS= STOR02                                             
...
JVMSHRC364E SH_OSCachesysv::acquireWriteLock() call to j9shsem_wait
495                                                                
on semid 69636 has failed with error -328433.                      

This last message is send 11 times per millisecond.
So I cancel Zowe and will redo the change in z/OSMF and return back as before in Zowe

Sorry that do not work.

**Comment by Joe-Winchester** [comment]
@pierremontel - sorry that didn't work for you and super thanks for trying.    
We are still working with the IBM team that works on the j9 virtual machine that is crashing for what is hopefully a more permanent fix, but what we'll do for now is document the workaround that you did with the -Xshareclasses:none in z/OSMF and put this into our 1.14 release.
The doc-site pull request is https://github.com/zowe/docs-site/pull/1335 and if you've got a moment to take a look and give any comments for if you think that's OK, any improvements that could be made, that'd be great.   In particular I'd be keen if there is enough information for someone searching the docs to find the workaround troubleshooting chapter (i.e. what error code condition did you see in the crash that you'd type into the docs search box and would that have helped you find the workaround.  Cheers !
![image](https://user-images.githubusercontent.com/28100302/89162776-74bdc700-d56c-11ea-880b-8bbe74d235d6.png)

**Comment by 1000TurquoisePogs** [comment]
Considering this has been merged, I think it can be closed?

**Comment by stevenhorsman** [comment]
I'm not sure that we ever fully worked out the cause, just added some doc and a warning, but given that we've not got any updates in the last 5 months I think we can close and re-open later if required

**Comment by balhar-jakub** [comment]
Closed, if this issue reoccurs, feel free to open it again.
