### ISSUE TITLE
Zowe Blog: Leverage Zowe to accelerate and simplify problem resolution in IBM Service Management Unite (SMU)

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#70]
Blog ready for OMP/LF promotion.

Link: https://www.ibm.com/developerworks/community/blogs/5e65990a-9690-42e2-93b1-c2267be7620c/entry/Leverage_Zowe_to_accelerate_and_simplify_problem_resolution_in_IBM_Service_Management_Unite_SMU?lang=en

**Comment by christinevblum** [comment]
I will get it scheduled
