### ISSUE TITLE
Inconsistent documentations

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#703]
Some parameters are listed on quotes, some without:

zowe zos-files list data-set "ibmuser.asm"
vs
zowe zos-files create data-set-classic NEW.CLASSIC.DATASET

minor issue, works in both ways...

**Comment by nannanli** [comment]
Issue moved to [zowe/docs-site #1323](https://github.com/zowe/docs-site/issues/1323) via [**ZenHub**](https://www.zenhub.com/)
