### ISSUE TITLE
Capture command return codes

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#706]
**Describe the bug**
I cannot handle return value of zos-files upload dir-to-pds

**Steps to Reproduce**
```
#!/bin/bash
STATUS=$(zowe zos-files upload dir-to-pds "$PKG_NUMBER/JCL" "ADDBDERT.$PKG_NUMBER.JCL")
echo $STATUS
if  [[ "$STATUS" == "success: true"* ]];
then
    echo "Files uploaded"
else
   echo "Upload failed"
fi
```
Please help how can the success or failure captured.

Thank You!

Try  echo $STATUS | cut -c1-13 and  echo $STATUS | cut -c1-28

**Comment by Alexandru-Dumitru** [comment]
I don't know of any builtin command to play nicely with JSON in a linux shell, but if you are willing to install [jq](https://github.com/stedolan/jq) you can have something like this:
```
$ status=$(zowe zosmf check status --rfj)
$ echo $status | jq -r '.success'
true
```
I won't go as far as parsing this like so. It's a lot of trial and error: 
```
$ echo $status
{ "success": true, "exitCode": 0, "message": "", "stdout": "The user XXXXXX successfully connected to z/OSMF on .............
```
```
$ echo $status | cut -c3-17
"success": true
```

See the `--rfj` flag which returns a JSON object, instead of having to parse the output as a string (no `cut`, `awk` etc.)
Or, you can use also Python, as it should be pre-installed. More info here: https://stackoverflow.com/questions/1955505/parsing-json-with-unix-tools, but personally I think `jq` looks cleaner.

**Comment by zszabo14** [comment]
Thank You for your advice. In some other commands, like zos-files list data-set and  zos-files create data-set-classic. The response seems to be normal test , while in this command it's JSON.

**Comment by Alexandru-Dumitru** [comment]
I used `--rfj (--response-format-json)` flag in my command to purposely generate the output as JSON. This was the reason it was added, to be able to programmatically handle to output of Zowe commands. By doing so you can get a standardized output that doesn't change across zowe commands.  I checked the output of your command, and by doing the way you exemplified, you are only checking the `success: true` status for the first file which is uploaded. For me this doesn't look reliable. Output example:

```
PS C:\Users\xxxxx\GitHub\TEST> $status=(zowe files upload dir-to-pds "test" "xxxxx.test1")
PS C:\Users\xxxxxxxx\GitHub\TEST> echo $status                                                                                         
success: true              <-------------------- this will be captured and checked
from:    C:\Users\xxxxx\GitHub\TEST\test\T1
to:      xxxxx.TEST1(T1)

success: true              <-------------------- what if this fails for some reason?
from:    C:\Users\xxxxx\GitHub\TEST\test\T2
to:      xxxxx.TEST1(T2)


file_to_upload: 2
success:        2
error:          0
skipped:
```

The JSON output is more reliable as it's structure will never change:

```
{
  "success": true,          <------------------/-- this is for the whole command
  "exitCode": 0,            <-----------------/
  "message": "",
  "stdout": "\u001b[33msuccess: \u001b[39m\u001b[32mtrue\u001b[39m\n\u001b[33mfrom: \u001b[39m   C:\\Users\\xxxxx\\GitHub\\TEST\\test\\T1\n\u001b[33mto: \u001b[39m     xxxxx.TEST1(T1)\n\n\n\u001b[33msuccess: \u001b[39m\u001b[32mtrue\u001b[39m\n\u001b[33mfrom: \u001b[39m   C:\\Users\\xxxxx\\GitHub\\TEST\\test\\T2\n\u001b[33mto: \u001b[39m     xxxxx.TEST1(T2)\n\n\n\u001b[33mfile_to_upload: \u001b[39m\u001b[34m2\u001b[39m\n\u001b[33msuccess: \u001b[39m       \u001b[34m2\u001b[39m\n\u001b[33merror: \u001b[39m         \u001b[34m0\u001b[39m\n\u001b[33mskipped: \u001b[39m       \u001b[34m0\u001b[39m\n\n\nData set uploaded successfully.\n",            <-------------------- STDOUT that you should not care about
  "stderr": "",
  "data": {
    "success": true,
    "commandResponse": "Data set uploaded successfully.",
    "apiResponse": [                 <-------------------- if needed, you can check the successful upload for each file in this array
      {
        "success": true,
        "from": "C:\\Users\\xxxxx\\GitHub\\TEST\\test\\T1",
        "to": "xxxxx.TEST1(T1)"
      },
      {
        "success": true,
        "from": "C:\\Users\\xxxxx\\GitHub\\TEST\\test\\T2",
        "to": "xxxxx.TEST1(T2)"
      }
    ]
  }
}
```

I hope this helps going forward with scripting around Zowe CLI.

**Comment by zszabo14** [comment]
Thank You!

My issue with this command was, that the return value for this command is a JOSN, even if you don't add --rfj (I can see it, because it's colored in the the command line)
While other commands response is a simple text, that's why the [[ "$STATUS" == "success: true"* ]]; works.

The other issue is, I think the overall command status should be enough for first test. It should show Failure if any of the file upload fails. The user should do further checks for each files, if the overall status is Failure.

**Comment by Alexandru-Dumitru** [comment]
> Thank You!
> 
> My issue with this command was, that the return value for this command is a JOSN, even if you don't add --rfj (I can see it, because it's colored in the the command line)
> While other commands response is a simple text, that's why the [[ "$STATUS" == "success: true"* ]]; works.

You're welcome. 

Would you mind sharing the command you are using and the full output with me? When I tried it, I didn't get a JSON format. I had to use `--rfj` for JSON. We need to know if this is a legitimate bug, because the command should not return a JSON object unless instructed to do so. It would also be good to know on which version of CLI you are. I am working with 6.16. (latest is 6.20, for reference).

Thanks.

**Comment by zszabo14** [comment]
So, as I see the response of the upload command interpreted as JSON (or some other "object") as it is colored by nodeJS:
![image](https://user-images.githubusercontent.com/42870072/89176955-c70de080-d58a-11ea-92cf-bd376c50c0d7.png)

While the all-members looks like a normal text:
![image](https://user-images.githubusercontent.com/42870072/89177064-f0c70780-d58a-11ea-9228-bfdcc34e4540.png)

I played with the response using cut, ant is seems there is 5 chars at the beginning of the text:
![image](https://user-images.githubusercontent.com/42870072/89177147-194f0180-d58b-11ea-86ca-bed02bf127d0.png)

zowe --version: 6.18.0

**Comment by zszabo14** [comment]
just recognized, if you upload the following files, they will overwritten each others. I think should be skipped at least
1WWFBAATL 
WWFBAATL
WWFBAATL1
WWFBAATL.JCL

**Comment by zszabo14** [comment]
![image](https://user-images.githubusercontent.com/42870072/89178662-67b1cf80-d58e-11ea-905b-163f16568137.png)

**Comment by zszabo14** [comment]
See stdout

![image](https://user-images.githubusercontent.com/42870072/89180114-603ff580-d591-11ea-9967-2b3cfc9690a7.png)
 vs
![image](https://user-images.githubusercontent.com/42870072/89180153-72ba2f00-d591-11ea-9a3f-fea1f86b0866.png)

**Comment by Alexandru-Dumitru** [comment]
I was looking at the same thing 😃 . 
- So the response is not returned as JSON by default (no bug there), but the console will color the text because we have these ANSI escape sequences passed in the output. `\u001b[33m` is yellow, for example. That's also the reason why `cut` is behaving that way.
- the overwrite issue, with overwriting:
    - It is possible that the name is trimmed to first 8 chars to comply with dataset name convention (I would have to verify the source)
    - also z/OSMF is overwriting the files by default, given the same name is provided (and if it is trimmed, this would be the case)

**Comment by zszabo14** [comment]
I think I will work with jq...

thank you!

**Comment by Alexandru-Dumitru** [comment]
You're very welcome, and sorry for the inconsistency provided in the plain output, although the JSON output gives stable results.

**Comment by Alexandru-Dumitru** [comment]
Final question, which I forgot to ask earlier is, if this information is sufficient, can we close this? Thanks.

**Comment by zszabo14** [comment]
yes, you can close

**Comment by Alexandru-Dumitru** [comment]
Thanks @zszabo14
