### ISSUE TITLE
ZOWE profile creation validation

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#721]
**Is your feature request related to a problem or limitation? Please describe.**
profile parameters are not validated when profile is created. profile created successfully, even if the hostname or user is not valid
![image](https://user-images.githubusercontent.com/42870072/89283792-0fda9d80-d64e-11ea-91b1-f0ebc819cd04.png)

**Describe the experience you'd like**
profile creation should fail if parameters are incorrect or have a 'validate' function for profiles

**Describe alternatives you've considered**

**Additional context**

**Comment by MikeBauerCA** [comment]
@zszabo14 what do you think about having a validate flag that you can specify on the command line (`--validate`)? Perhaps when specified, the `zowe zosmf check status` command could be subsequently run? 

I could see where some would not want to fail profile creation if perhaps the system was down at that moment. As an example, I typically automate profile creation as part of my GitHub projects (e.g. https://github.com/zowe/zowe-cli-sample-scripts/tree/master/use_cases/Profile-Automation) and I wouldn't want the profile creation automation to fail if the target system just happened to be unavailable at that moment.

Also, our current direction is to reduce the number of profiles needed for those leveraging APIML and its SSO capabilities. Users can now take advantage of base-profiles which can provide fallback values for options not specified in service-profiles (e.g. z/OSMF). More details on base-profiles are covered in this [blog](https://medium.com/zowe/using-tokens-in-the-zowe-cli-3b221f09ec5b). This means that profiles are not self-contained. For example, I may use a base-profile to store username, password, and host but a service profile to store port. Options can also be specified on the command line or in environment variables.

**Comment by balhar-jakub** [comment]
@MikeBauerCA Is this an issue that should move to the Zowe CLI?

**Comment by zszabo14** [comment]
@MikeBauerCA as you see on my picture, I was able to create a profile against whatever.server.com while it's not even exits. 
both option you mention is OK for me
Yes, you can close
