### ISSUE TITLE
Sample needed. Do you have any sample how to call a zowe command fron a nodeJS function?

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#730]
Please help me with a sample nodeJS function which shows how to call a zowe cli function. eg: submit a job. 
Using exec is the only way or there is a "deeper" integration to nodeJS?

thx

**Comment by Alexandru-Dumitru** [comment]
Hi @zszabo14,

Is this what you are looking for? https://github.com/zowe/zowe-cli/tree/master/packages/zosjobs (you can find a sample for submitting a job as well)

You can find more info here: https://github.com/zowe/zowe-cli#using-the-zowe-node-apis

**Comment by balhar-jakub** [comment]
@zszabo14 Did it solve the issue for you, or is there anything else needed?

**Comment by zszabo14** [comment]
yes
