### ISSUE TITLE
ZWED0064W - org.zowe.zosmf.workflows: invalid method options/head

### ISSUE THREAD

**Issue by pierremontel** [zowe/community#731]
Into the Zowe stclog, after each startup, I am seeing such warning messages and I have no clue what does they mean:
 
ZWED0060I - org.zowe.zosmf.workflows: installing data services                                                                  
ZWED0061I - org.zowe.zosmf.workflows: installing service zosmf                                                                  
**ZWED0064W - org.zowe.zosmf.workflows: invalid method options                                                                    
ZWED0064W - org.zowe.zosmf.workflows: invalid method head**                                                                       
ZWED0060I - org.zowe.zosmf.workflows: installing data services                                                                  
ZWED0062I - org.zowe.zosmf.workflows: installing router at /ZLUX/plugins/org.zowe.zosmf.workflows/services/zosmf/1.0.1          
ZWED0061I - org.zowe.zosmf.workflows: installing service zosmftracker                                                           
ZWED0061I - org.zowe.zosmf.workflows: installing service zosmf                                                                  
ZWED0062I - org.zowe.zosmf.workflows: installing router at /ZLUX/plugins/org.zowe.zosmf.workflows/services/zosmftracker/1.0.1   
**ZWED0064W - org.zowe.zosmf.workflows: invalid method options                                                                    
ZWED0064W - org.zowe.zosmf.workflows: invalid method head**                                                                       
ZWED0062I - org.zowe.zosmf.workflows: installing router at /ZLUX/plugins/org.zowe.zosmf.workflows/services/zosmf/1.0.1          
ZWED0061I - org.zowe.zosmf.workflows: installing service zosmftracker                                                           
ZWED0062I - org.zowe.zosmf.workflows: installing router at /ZLUX/plugins/org.zowe.zosmf.workflows/services/zosmftracker/1.0.1   
ZWED0065I - org.zowe.zosmf.workflows: installing static file handlers...                                                        
ZWED0066I - org.zowe.zosmf.workflows: serving static files at /ZLUX/plugins/org.zowe.zosmf.workflows/web                        
ZWED0065I - org.zowe.zosmf.workflows: installing static file handlers...                                                        
ZWED0066I - org.zowe.zosmf.workflows: serving static files at /ZLUX/plugins/org.zowe.zosmf.workflows/web                        

**Details**
 - Version '1.13.0+20200623' 
 - Node v12.18.0
 - Test environment: Mini system running z/OS 2.3 with ACF2 security tool

Zowe seems to work fine.
Thanks for your advice.
Pierre

**Comment by pierremontel** [comment]
Attached the ZWESVSTC log
[ZWESVSTC.LOG.txt](https://github.com/zowe/community/files/5056627/ZWESVSTC.LOG.txt)

**Comment by Joe-Winchester** [comment]
@1000TurquoisePogs - this looks like it's a zlux message.  Is it harmless ?  Cheers
