### ISSUE TITLE
copy data-set opstion should have replace option and list of members

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#734]
**Is your feature request related to a problem or limitation? Please describe.**
1. currently when you copy a PDS member if it has to be replaced error message generated: ISRZ002 Members not replaced - 1 members not replaced, 2 members copied
2, with one command you can only copy one member or all xxxx.yyyy(*)

**Describe the experience you'd like**
- copy-dataset option must have a --replace yes/no option
- there should be a new option like copy-members --list "member1, membe2, ...memberX" 

**Describe alternatives you've considered**

**Additional context**
if you have to copy multiple members you should initiate multiple commands, I don't know, but this could be an overhead as each command initiates an API connection, maybe does a login also. 

I don't know how the ZOWE works in the background, but form login point of view maybe you should consider to:
- use a "session". have an "zowe init-session --profile <profile>" option, which logs in and keeps the ZOWE session alive until "close-session"
- ability to list multiple set of parameters for a command, like:
zowe zos-files copy data-set ["USER.FROM.SET1" "USER.TO.SET1", "USER.FROM.SET2" "USER.TO.SET2", ... "USER.FROM.SETX" "USER.TO.SETX"]

**Comment by Joe-Winchester** [comment]
Hi @zszabo14 - this sounds like a great suggestion for an enhancement.  I'm moving this to the github repository that the Command Line Interface (CLI) squad use to track and plan their work,  where you'll be able to get on their radar.
