### ISSUE TITLE
CLI plugin for OPC(TWS)

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#737]
**Is your feature request related to a problem or limitation? Please describe.**
zowe CLI OPC plugin required

**Describe the experience you'd like**
There are major automation tasks related to OPC. It would be great to have OPC plugin also
Features:
- query applications, jobs, calendar, etc objects
- modify applications (add, remove jobs, change predecessor, successor, schedule, etc..)
- modify other objects...
- query plans
- update plans
- query application/job run statuses

**Describe alternatives you've considered**

**Additional context**

**Comment by Joe-Winchester** [comment]
Hi @zszabo14.  Is your question about Tivoli Workload Scheduler ?   If so then there is a Zowe Conformant TWS Command Line Interface available that Domenico wrote a great blog about recently https://medium.com/zowe/ibm-z-workload-scheduler-commands-are-now-available-in-zowe-cli-549a3c53f530.  Because TWS is provided by an independent software vendor (or ISV) - in this case IBM - it's not part of core Zowe and requests for feature enhancements are probably best directed to the product team taking care of TWS.  I've pinged Domenico Dalterio who is the IBM offering  manager for the product and hopefully he can provide a response.

**Comment by zszabo14** [comment]
Thank You!

**Comment by Fede75zos** [comment]
Hi,
I’m Federica, Tech Sales for IZWS.
Features currently available in the IZWS plugin for ZOWE are 
-	possibility to update a Special Resource in the plan (GET/UPDATE commands)
-	list Job, applications and special resources in the plan
-	list applications in the DB
-	Submit an application in the plan
-	execute WAPL (aka SOE) commands. 
WAPL, Workload Automation Programming Language, is a programming language that allows to access most of the features of IZWS PIF. Some of them have been also extended in WAPL
Using WAPL command in the CLI plugin you can run most of the actions in the IZWS DB and Plan. Here after a link to WAPL documentation, to get some more details:
[](https://www.ibm.com/support/knowledgecenter/en/SSGSPN_9.5.0/com.ibm.tivoli.itws.doc_9.5/zos/src_wapl/eqqw1mst_welcome.htm )
Another important point is that IZWS development team is working to enhance the CLI with additional commands in a continuous delivery. New commands will be available soon.
Taking as input your list of features
•	query applications, jobs, calendar, etc objects.   
Currently the query on the DB can be run against application (Jobstream)		 						
•	modify applications (add, remove jobs, change predecessor, successor, schedule, etc..).       
This command is in under evaluation for next delivery for job in the plan
•	modify other objects...									
As said before, it’s currently possible modify Special Resource in the Plan, using the GET/UPDATE commands
•	query plans	
You can query job and Jobstream in the plan using the list command. It’s not possible run query for WS in the plan or use the WS filter in Job and JobStream query
•	update plans			
It’s possible to add a Job or Jobstream in the Plan using the Submit command for JobStream and Execute WAPL command for Job.					
•	query application/job run statuses							
It’s possible to query Job/JobStream status using the list command
If you need some more information about Zowe CLI Plugin for IZWS please let us know. 
We will be pleased to assist you with a presentation or demo about the current usage of Zowe plugin for IZWS.
Federica

**Comment by balhar-jakub** [comment]
@zszabo14 Did the answers satisfied your need? Can we close the issue now?

**Comment by zszabo14** [comment]
yes, of course
