### ISSUE TITLE
zowe zos-files copy data-set : no replace option

### ISSUE THREAD

**Issue by zszabo14** [zowe/community#748]
**Is your feature request related to a problem or limitation? Please describe.**
zowe zos-files copy data-set doesn't have a REPLACE option

**Describe the experience you'd like**
please add REPLACE option

**Describe alternatives you've considered**

**Additional context**

**Comment by Joe-Winchester** [comment]
Thank you @zszabo14 for this enhancement request for the Zowe CLI.  I've moved the git issue to their repo https://github.com/zowe/zowe-cli and they'll be able to respond to it there.  Cheers !

**Comment by Joe-Winchester** [comment]
Issue moved to [zowe/zowe-cli #808](https://github.com/zowe/zowe-cli/issues/808) via [**ZenHub**](https://www.zenhub.com/)
