### ISSUE TITLE
Excessive ZOWESVR CPU and EXCP consumption

### ISSUE THREAD

**Issue by nkocsis** [zowe/community#8]
Several people are complaining about excessive ZOWESVR CPU and EXCP consumption, particularly on zD&T systems

**Comment by John-A-Davies** [comment]
This has been raised as RTC defect 21171.
https://jazzk01.hursley.ibm.com:9443/ccm/web/projects/Zowe#action=com.ibm.team.workitem.viewWorkItem&id=21171

**Comment by John-A-Davies** [comment]
Some questions:
1.  Is this normal for WAS Liberty servers?
2.  Is this only apparent on zD&T systems, or do zD&T systems suffer more?
3.  Is this consistent across different systems?  What is the CPU+EXCP  consumption per hour on an idle system?

**Comment by crshnburn** [comment]
It would be worth checking the Liberty configuration as by default it will poll for configuration and application updates and this will cause CPU consumption even in an idle system.

Polling can be turned off by adding
`<config updateTrigger="mbean"/>`
and
`<applicationMonitor updateTrigger="disabled"/>`
to server.xml configuration.

**Comment by John-A-Davies** [comment]
I've also heard of a recurrent CPU issue in Node, thought to be fixed in version 6.14.3 but now reappeared.  While Node contributes to the overall CPU of ZOWESVR, it's Liberty Atlas which consumes the most by far.

**Comment by John-A-Davies** [comment]
The CPU problem seemed to vanish after I tore down the ZOSMF server and angel processes a couple of times.  Currently ZOWESVR3, the greediest CPU user, is averaging 4.5% at idle.

**Comment by hogstrom** [comment]
I am hoping to have a CPU, memory and storage view of Zowe by the end of the week.  My big concern is the mix of processes (JAva, Node and C) under ZoweSVR

**Comment by Tbr00ksy** [comment]
Close by issue 21 below:
https://github.com/zowe/explorer-server/issues/21
