### ISSUE TITLE
Adresse space AD cpu consumption

### ISSUE THREAD

**Issue by F-LEMANER** [zowe/community#838]
Hello all,
See the following SDSF DA screenshot where ZOWE adresse space ZWE1AD is the 1st  cpu consumer of all running STC of the z/OS partition

![image](https://user-images.githubusercontent.com/63342548/96261131-4faff080-0fc0-11eb-97f6-d00ecb6f26aa.png)

We are quasi not using ZOWE , so what is he doing ? why this huge CPU consumtion ? How can we reduce it ?
Thanks a lot
Regards

**Comment by F-LEMANER** [comment]
Also a concern about 10 millions EXCP after running for 10 days

**Comment by Joe-Winchester** [comment]
@F-LEMANER - the ZWE1AD address space is used for Application Discovery.   I recall from a while back that there were problems with the Springboot server where a timeout value increase helped.  https://github.com/zowe/api-layer/issues/282 looks like it has some suggestions.  If you add `-DLatencyUtils.useActualTime=false \` to the `start.sh` script in `api-components/scripts` does this help ?   
I'll move this issue to the api mediation layer repository to see if they have any suggestions for what might be causing the high CPI consumption and any possible workarounds or fixes.
