### ISSUE TITLE
Categorize repositories and their role and reponsibilities

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/community#908]
**Is your feature request related to a problem or limitation? Please describe.**
Zowe has a number of repositories.  This includes
- code that is package with core Zowe deliverable  
- sample code that isn't built but users can clone and create extensions or learn about Zowe from 
- code that is built and shipped but not part of core Zowe
- code that is built and shipped but not included in a test pipeline
- incubators

**Describe the experience you'd like**
Provide guildelines for projects and what types are, to help people understand more and also to help provide a roadmap for folks wanting to contribute code for the steps required to transition between sample / incubator / delivered / included in core / ...

**Comment by jmertic** [comment]
Great idea and would added a ton of value @Joe-Winchester !

**Comment by balhar-jakub** [comment]
There are few things: 
All the projects are now categorized here: https://github.com/zowe/community/blob/master/PROJECTS.md

This doesn't reflect all the repositories and/or links to the repositories. There are repositories that are outdated and/or not owned by any squad and we should make sure that this is visible. 

We can use topics on the repositories to resolve this problem. But first we need to figure out what topics are important for us.
