### ISSUE TITLE
Zowe Blog: How to Automate z/OS Data Set Allocation using Zowe & JSON

### ISSUE THREAD

**Issue by Tbr00ksy** [zowe/community#91]
Link to blog: https://medium.com/@dkelosky/how-to-automate-z-os-data-set-allocation-using-zowe-json-30e70fb960d8

**Comment by Tbr00ksy** [comment]
Social promotion - not to be added to OMP blog page

**Comment by christinevblum** [comment]
I will get it scheduled for social
