### ISSUE TITLE
Involvement of Zowe within the Mentoring program

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#920]
The meetings around the OMP Mentorship program are starting next week and as such, we need to provide someone who will join these meetings and present Zowe for the potential Mentees. 

@balhar-jakub is already involved from earlier, but if someone feels that they could be better for this such as @MikeBauerCA the knowledge and communication around the time slots can be transferred. 

There will be a 2021 Mentorship Brainstorming session with potential Mentors & Mentees on January 12th.  See Registration link below
https://www.openmainframeproject.org/blog/2020/12/17/join-the-open-mainframe-project-mentorship-program
Anyone with a project idea (or not) is encouraged to attend. We should provide a short background on the project and needed enhancements.  

The presentation from the last year is available here: https://drive.google.com/file/d/1pxX8_WjNMB_d4zaVcSggPvd17KjtEQVp/view?usp=sharing

As for the access to the z Systems Leonard Santalucia stated that they have z14 instance that they can make available for the students. This was in response to the query from last meeting by Sean Grady

**Comment by MikeBauerCA** [comment]
@balhar-jakub would you like to team up on this? I would like to attend and can contribute if needed. I also plan to attend from the COBOL Programming Course perspective. Do you know if we use the same registration link, or is that just for Mentees?

**Comment by balhar-jakub** [comment]
@MikeBauerCA I would like to team on that and as far as I am aware it's the same registration link. 

As for the integration between the projects. It would be great to look for more projects integrating projects within OMP. 

There is another idea about integration with GenevaERS in the zowe-explorere channel.

**Comment by MikeBauerCA** [comment]
Closing as we completed the kick-off presentation and call. We can open new issues for any additional efforts related to the Mentorship program.
