### ISSUE TITLE
Prepare the document outlining the roles within Zowe

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#922]
There are some roles within the Zowe that are being done by the people Contributing. We need to outline as TSC at least the key specifics of these roles with providing guidance on how a member is accepted into the roles that have Zowe wide voting privileges

**Comment by 1000TurquoisePogs** [comment]
I'd like everyone to provide suggestions on which roles you think exist and how they relate to permissions.
Regardless of quantity and types of roles, they should be recorded in the form of github teams https://github.com/orgs/zowe/teams for the purpose of tracking and relating to github permissions when appropriate.


Here's my thoughts:

* What do you call a person who is contributing to the community for the first time? 
    * What if they open a PR to submit code to a repo owned by a squad
    * What if they made a video for us
    * What if they provide documentation tips
All of these things can be put into github, even though they are different types of content. I rather like the idea of having a copy of the video someone put on youtube to also be in github, because it makes us independent of the whims of youtube policy.

To me, a person who submitted a change that was accepted, into a repo managed by a squad, is a CONTRIBUTOR of that squad.
I think contributors could be allowed, at discretion of the squad, to have repo abilities that don't change settings or code. Such as responding to issues, creating branches, reviewing pull requests.

The next level up is being able to merge pull requests. Reviews dont hurt, but merging effects end-user code, so it must be restricted. A person should only be able to do this if the squad votes them into the role. I call this role a COMMITTER. This may extend to other related change-oriented tasks, like publishing a video or updating a website.

Finally, there is administrative tasks: the ability to add someone to a group, to modify permissions of branches, and much more. These tasks go beyond just making edits to code, because a github administrator has the ability to change visibility or delete repos, so actually they have complete control of code if given it, and therefore it's a very important role to not abuse.

So, I end up with 4 roles:

Anyone
- Can read the code
- Can file issues

Contributors
- Can make branches
- Can review PRs
- Can comment on issues

Committers
- Can merge code
- Can close issues
- Can close PRs
- Can delete unprotected branches
- Can publish videos using zowe channels?
- Can update website?

Administrators
- Can add/remove users to any of these roles (after following squad procedures about role approval)
- Can change branch permissions
- Can add/remove github hooks
- Can change repo status, such as archive

These are per-squad.

**Comment by balhar-jakub** [comment]
Just a few comments. In the Linux Foundation documents, the person that contributes in any way such as creating a new issue or opening a PR for the first time is named Contributor. I would probably keep up with this as there are some requirements towards anyone who is contributing literally anything. 

I agree with the distinction between the four roles, but below I outline some changes to the proposed responsibilities and rights.

Anyone
- Can read code

Contributor (There is no voting on this role, anyone who does any of the things below becomes one, also there is no privilege with respect to the maintaining the Zowe)
- Can file issues
- Can create PRs
- Can review PRs
- Can comment on issues
- Can make branches - Possibly limit to Committers?

Committers (Voted into the role)
- Can merge code
- Can close issues
- Can close PRs
- Can delete unprotected branches
- Can publish videos using zowe channels?
- Can update the website?
- Can publish blog posts?

Administrators - Squad role / Administrator for the squad isn't by default administrator for another squad. 
- Can add/remove users to any of these roles (after following squad procedures about role approval)
- Can change branch permissions
- Can add/remove GitHub hooks
- Can change repo status, such as archive


What is important and not yet really outlined is how does Zowe make decisions such as the creation of TSC. The last time it was by asking all Committers to vote. If this is going to be the case for future as well then the process of introducing and removing Committers is of major importance to Zowe and as such needs to be handled similarly throughout the Zowe. 

The obvious solution would be that to add new committer majority of all committers needs to agree with that, but that would remove a lot of flexibility for the squads around committers rights, which for sure isn't something we want. 

The solution that I think might actually work is that squads can add Committers as they want but when there is a Zowe wide vote then each squad will be represented by one member. It has its issues and drawbacks as well, such as if there is one person minority within squad it won't be reflected in the way on the Zowe wide level.

**Comment by ifakhrutdinov** [comment]
I agree with the proposal but I would move the ability to create branches to the committer role. If someone needs to work on a feature/bugfix they can always create a branch in their forks and make a pull-request. A valid case would be collaboration but that can be done via committers, that should also ensure that all the rules like branch naming is followed. The main repository usually has a limited set of branches (like releases) in most of the cases.

As for updating the website, are we talking about zowe.org?

**Comment by balhar-jakub** [comment]
I agree with the creation of the branchers as the commiters right. 

I believe that the zowe.org page is the one, but @1000TurquoisePogs may add more to this

**Comment by jackjia-ibm** [comment]
If we want to align the roles with Github, or overlap with Github default roles, this is the role list provided by Github settings:

- **Read**: Can read and clone this repository. Can also open and comment on issues and pull requests.
- **Triage**: Can read and clone this repository. Can also manage issues and pull requests.
- **Write**: Can read, clone, and push to this repository. Can also manage issues and pull requests.
- **Maintain**: Can read, clone, and push to this repository. They can also manage issues, pull requests, and some repository settings.
- **Admin**: Can read, clone, and push to this repository. Can also manage issues, pull requests, and repository settings, including adding collaborators.

**Comment by balhar-jakub** [comment]
As a part of this, we need to prepare the guidance into how to approach the selection of the voting member into the TSC

**Comment by Joe-Winchester** [comment]
> If we want to align the roles with Github, or overlap with Github default roles, this is the role list provided by Github settings:
> 
> * **Read**: Can read and clone this repository. Can also open and comment on issues and pull requests.
> * **Triage**: Can read and clone this repository. Can also manage issues and pull requests.
> * **Write**: Can read, clone, and push to this repository. Can also manage issues and pull requests.
> * **Maintain**: Can read, clone, and push to this repository. They can also manage issues, pull requests, and some repository settings.
> * **Admin**: Can read, clone, and push to this repository. Can also manage issues, pull requests, and repository settings, including adding collaborators.

Hi @jackjia-ibm - in this list would "Can create branches" be  in **Write** ?  /That allows **Read** and **Triage** able to fork if they want to contribute.

**Comment by jackjia-ibm** [comment]
@Joe-Winchester yes for "Can create branches" be in **Write**. It needs directly write (push) permission to the repository. I just found a very detail list of the github permission explanation here https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level.

**Comment by balhar-jakub** [comment]
This is the current document outlining the roles within Zowe: https://github.com/zowe/zlc/blob/master/process/roles.md

**Comment by 1000TurquoisePogs** [comment]
OK, I tried to combine all of the feedback thus far and compare them to what github does and see if there's some compromise that makes it fit the github model better.
Basically, we restricted some things to contributor/committer that are already available at the lowest level of permission on github, "READ" or "TRIAGE" so I moved a few things down the list. The only thing I don't like about READ is that it gives access to write on the "wiki". The issue with the wiki is there is no form of PRs to github wikis, rather anyone can edit without review and the only way to prevent bad edits is to revert them after the occur (like wikipedia)

Here's the list:

# Roles

Anyone: (Github READ minus PR review, wiki editing)
- Can read code
- Can file issues
- Can create PRs
- Can comment on issues

Anyone can become a contributor upon request after doing one of the following:
- File an issue
- Create a PR


Contributor: (Github TRIAGE minus wiki editing)
- Everything "Anyone" can do plus
- Can review PRs
- Edit issues and PRs (labels, closing)
- Can submit blog posts for approval
- Can submit videos for approval

Contributors can become Committers via being voted into the role by Committers

Committers: (Github WRITE)
- Everything "Contributors" can do plus
- Can make branches
- Can create releases
- Can merge code
- Can delete unprotected branches
- Can approve blog posts
- Can approve videos
- Can update the website (the action of taking the latest branch and making it public, is this committer or admin?)
- Can edit wikis


Committers can become Administrators of a squad by being voted into the role by Committers

Administrators (Squad) (Github ADMIN):
- Everything "Contributors" can do plus
- Every action not already listed, such as but not limited to
- Adding and removing users to the roles
- Changing branch permissions
- Changing github hooks
- Changing repo status

## Misc

Votes: Must be cast in a public place, such as github, mailing list, or slack. A simple majority is recommended.

Record keeping: Roles (all, or only those related to github?) must be assigned via Github Teams (https://github.com/orgs/zowe/teams) to make it all visible in one place, and provide for simple assignment of github permissions by roles.



Global admins: They exist but are not codified currently. It includes people above the Zowe level, such as the OMP and LF. But, at the Zowe level, who would they be? Appointed by the TSC? TSC members themselves? Global admins exist to solve issues around security, visibility, and repo problems squad admins are having an issue with as they arise

Odd issues such as creation of the TSC: Now handled by the TSC, so no need to describe it in the roles document.

**Comment by balhar-jakub** [comment]
Transition to commiters: Is there a need to add more complex requirements for the transition to commiter other than just being voted?

One of the option is to provide the guidance with respect to what the squads should generally integrate into their admission to the commiter status.
- The person should be decent, capable and implemented something above their capability as an example. 

TSC should be able to step in in the case of a try to a hostile takeover.

Every squad should have a contributing guideline (CONTRIBUTING.md) trying to codify what it does take to becoming a contributor.

**Comment by balhar-jakub** [comment]
What should happen when someone becomes inactive?

Complex topic:
- One of the issues is what should happen when somebody leaves the company the person was previously with
- How should we approach the definition of roles with respect to the activity. 

TBD with John - How should we handle Media (medium.com, blog, videos), How should we handle the pipeline, How other Open Source projects handle the inactivity and movements across companies.

**Comment by balhar-jakub** [comment]
This PR seems to be linked to this topic: https://github.com/zowe/community/pull/880

**Comment by Joe-Winchester** [comment]
FYI: The blog process for [medium.com/zowe](https://medium.com/zowe) submissions, approval and publication are at: [https://github.com/zowe/community/blob/master/blogging/blog_guidelines.md](https://github.com/zowe/community/blob/master/blogging/blog_guidelines.md)

**Comment by balhar-jakub** [comment]
What should the Squad do when someone becomes inactive?

Example reasons for inactivity:
- Changes in life removing the possibility for the person to continue in the current role
- Changing company to another in which the person won't have the possibility to contribute
- Changing project within a company to another where the person won't be able to contribute
- Any other reason for stopping the contribution 

We expect the person in any of the situations that will limit their ability to contribute in the roles Commiter and Administrator to let the members of the squad know either via the Slack channel or on the next squad meeting that such situation is arising. 

The TSC will prepare general expectations towards the roles and the squads will adapt and complete the template provided by TSC with the specific squad-related requirements. 

In case any person stops fulfilling the roles of the specific role without any reason such as mid-term illness, it is the right and requirement on the squad to remove the person from such position. The removal happens automatically without a vote and the squad is just acknowledging the situation. In case there is a conflict about the situation it is possible to escalate the matter to the TSC. 

@RASakach Would something like this alleviate your concerns?

**Comment by balhar-jakub** [comment]
Clearly identify the actions that should be taken.

**Comment by balhar-jakub** [comment]
When the temporary absence is happening, it is possible for squad to decide to say that this person remains in the role.

**Comment by balhar-jakub** [comment]
@1000TurquoisePogs Do you have anything to add? We should try wrapping this topic in a reasonable time frame.
