### ISSUE TITLE
Outline and make more visible documentation around the major release change

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#924]
At some point during the lifetime of the Zowe, there will another major version. There is already some documentation and process outlined about the topic but it's a bit hidden while it needs to be visible to those using the Zowe. 

There are also few topics that need to be properly figured out such as the Conformance programs and the impact of such changes on them and the fact that the new major version is probably going to have new FMID.

**Comment by ifakhrutdinov** [comment]
> There is already some documentation and process outlined about the topic but it's a bit hidden while it needs to be visible to those using the Zowe.

@balhar-jakub, can you please share links to the existing doc?

**Comment by balhar-jakub** [comment]
I am aware of this but it outlines just the standard releases: https://github.com/zowe/community/blob/master/Project%20Management/Schedule/Zowe%20PI%20%26%20Sprint%20Cadence.md

@jackjia-ibm had something around this in one of presentations for the Architecture I thing. Could you maybe try to find it and share it here?

**Comment by ifakhrutdinov** [comment]
Would that include technical details like some early warnings about things being deprecated/removed/broken? For example, we'd like to rework some of the parts of the common C library which would make it incompatible with v1.x, I think we should start mentioning that somewhere so there are no surprises.

**Comment by balhar-jakub** [comment]
Yes I think this is one of the things that will be there. Some meaningful place to see the changes that are going to be backward incompatible.

**Comment by jackjia-ibm** [comment]
Sorry I missed this notification. I think the docs Jakub mentioned are:

- related to YAML configuration of Zowe defined here https://github.com/zowe/zowe-install-packaging/issues/1793. I will try to work on a version compatible with v1, but would like to drop support of instance.env in v2 to make code cleaner.
- related to manifest and packaging format. Some information can be found here https://github.com/zowe/zowe-install-packaging/issues/1692. Would like to see the standard packaging format become part of the conformance program, make to conformance staging and make it mandatory for v2. This will clear the way to setup Zowe App Store.

There is another small thing I would like to see in v2 is dropping support of accessing Desktop with desktop port directly. Every usage should go through Gateway, and use <gateway>/ui/v1/zlux to use Desktop. This will solve many cross domain (port) issues.

Hope these items make sense to others and we can have detail discussion.

**Comment by balhar-jakub** [comment]
I also think that @armstro mentioned some information around the length of support for the old and new LTS version. Could you please share it here?

**Comment by armstro** [comment]
Just to be sure we keep the terminology right - my comments were regarding new VERSIONs (not releases) and in this case we are concerned primarily breaking changes on the z/OS components (we understand breaking changes on the client components may or may not have impact to the consumers). Even client slide code might be a problem if consumers have automated using interfaces or deployed to many clients. (This might need to be a survey question in the future OR we be sure the "Current" development (before the future Active LTS is clearly communicated for an extended period of time.) 

See Release Timeline on the download page https://www.zowe.org/download and discussed here https://github.com/zowe/zlc/blob/master/process/ReleaseProcess.md Yes this has become a bit hidden over time and redesign of the web site. There was recent email discussion about making this on the initial zowe.org site but I recommended we not make it more visible until we are ready to announce something. The current diagram implies we will make a decision in 1Q for a new version - I see no harm in delaying that until we have a better idea on time line. 

We say the need for a new version will be decided annually - the picture implies the first of each year (but I have not found where we say that it the text - still need to dig).

**Comment by armstro** [comment]
I guess one more comment - a new version should not just be about breaking changes but should have some new significant capability/change in architecture or some "wow"  - the only one that comes to mind at the moment would be Docker/Kubernetes support which (I think) will take us a few months to figure out and declare a new "Current" release in 2H2021.....but that is just my opinion - it will be interesting to see if our consumers are interested in Kubernetes.

**Comment by MikeBauerCA** [comment]
Zowe CLI has some [early access features](https://www.npmjs.com/package/@zowe/cli#early-access-features) that are planned for the next major LTS release.  They are available for validation on public npm. We could also add them to the Zowe Technical Preview section on the Zowe Downloads page.

Currently, we are planning these key features for that release:
- Core Zowe CLI has Secure Credential Storage built-in instead of a separate plugin
- Simplified Getting Started Experience enabling config to be easily shared within an organization/project - see this [blog](https://medium.com/zowe/zowe-cli-getting-started-made-easy-f53d769c678e)
- A faster Zowe CLI experience via Daemon Mode - see this [blog](https://medium.com/zowe/zowe-cli-daemon-mode-29c0dc29c22f)

More to come...

**Comment by balhar-jakub** [comment]
Reach out to all the squads and collect what would be in the v2

**Comment by balhar-jakub** [comment]
What impact would that mean on Conformance?

**Comment by Joe-Winchester** [comment]
I've created a community wiki [Zowe release moving to a new major version](https://github.com/zowe/community/wiki/Zowe-release---moving-to-a-new-major-version) to capture the background, issues and concerns.   I'll move across comments from this issue + notes taken at the last TSC,  so we can have the two side by side (issue and meeting discussion) and use that to shape the wiki that become the summary discussion to help move forward.

**Comment by jandadav** [comment]
### **Api Squad's V2**
_(let's edit this post and add to it)_

#### Breaking change
- Drop support of old path pattern in Gateway routes `/api/v1/serviceid` in favor of the new pattern `/serviceid/api/v1`
- Drop support for onboarding same service where authentication config differs on individual instances

#### Wow
- Per service route configuration of gateway features (Authentication, CORS, Authorization)

**Comment by Joe-Winchester** [comment]
@jandadav - for APIML wow would it be possible to include:
 - Sticky routing of services (based on rules, to begin with same user ID always routed to same service instance)

**Comment by 1000TurquoisePogs** [comment]
Web UI squad V2 ideas (not final)
- Consolidation of web explorer servers (node code rolled into app-server) to reduce process count... breaking due to change of URLs (bookmarks break)
- High performance cluster-less mode for app-server... research needed to know if this is fully compatible with z/os, or if there are compromises https://github.com/1000TurquoisePogs/zlux-app-server/tree/test/forever-nocluster-mode
- desktop library upgrades (angular 6->10?, corejs 2->3)... can break plugins, but could choose minor upgrades that are less likely to do so
- desktop library removal: bootstrap... bootstrap infects root, making it challenging to use other style libraries. Can have apps bring their own bootstrap as a solution, but is breaking as a result.

**Comment by MikeBauerCA** [comment]
Zowe CLI squad v2 ideas
  - [Simplified Config](https://medium.com/zowe/zowe-cli-getting-started-made-easy-f53d769c678e) (currently in validation)
  - [Daemon Mode](https://medium.com/zowe/zowe-cli-daemon-mode-29c0dc29c22f) (performance improvement - currently in validation)
  - Conformance Program Update
  - Zowe Explorer to make use of simplified config
  - Automatic client configuration for API Mediation Layer Users
  - Node & Python SDKs could become LTS on Zowe.org
  - Profile migration utility
  - Add property to JSON config to better communicate what type of authentication to perform for specific services (creds direct to service, API ML with token, etc.)

**Comment by jellypuno** [comment]
Zowe Explorer Squad v2 ideas
- Approved Conformance Criteria
- Extensible APIs and Conformance Rules
- Handling of the simplified config file
- Multi-select support
- Zowe Explorer Templates
- Allocate multiple datasets using templates specified in the team config file

**Comment by Joe-Winchester** [comment]
@1000TurquoisePogs - for Zowe Desktop some ideas are:
- Support File Editor launch at resource,  for example. if you have a URL `<host>:<port>/zlux/fileeditor?DSNAME=ABC.DS(XYZ)&line=30` then that takes you straight into the desktop with a fill screen File Editor - the nav bar and the data set open at that line.  From there you could back up into the editor if you wanted to navigate off the data set, but in the customer scenario where they have a help ticket or work item pointing at a PDS file, a USS file, allow that to have a URL to that resource

**Comment by balhar-jakub** [comment]
I am closing this issue as I believe we have done what was the intention. 
We have the https://zowe.org/vNext.html webpage for all the information about the next release. 
And we have the https://www.zowe.org/download.html with Release Timeline explaining how we will approach further releases.
