### ISSUE TITLE
Zowe wide AT-TLS support

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/community#945]
**Is your feature request related to a problem or limitation? Please describe.**
At the moment in order to run Zowe securely it is necessary to configure all the services properly to use HTTPS. Different services have different setups and this makes the configuration more complex.  

**Describe the experience you'd like**
I would like to be able to delegate the security related topic to the MF itself instead of having everything configured to use HTTPS. 

**Additional context**
The API ML squad has this goal as one of the goals within the PI and we are looking for a buy-in throughout the wider Zowe community to ideally have a setup whre all the Zowe components will be using the AT-TLS to run on the zOS as one of the configuration options.

**Comment by balhar-jakub** [comment]
At the moment the ZSS supports AT-TLS. 

The API ML support for AT-TLS is planned, which for Zowe wide support leaves the servers such as datasets, jobs and web related servers.

**Comment by jackjia-ibm** [comment]
I have few questions @balhar-jakub,

- Will this change the way how APIML to verify the service certificate? More specifically about the config of `ZOWE_APIM_VERIFY_CERTIFICATES`.
- Will this change become the only way to configure certificates, or we have plan to support both? 
- With this change, do we plan to work on some automation of AT-TLS configuration?

**Comment by balhar-jakub** [comment]
We plan to support both AT-TLS and TLS without AT-TLS. 
It would be great to get some automation of the AT-TLS configuration.

As for ZOWE_APIM_VERIFY_CERTIFICATES we will verify during this PI. We have some preparatory work for this topic to understand it well.
