### ISSUE TITLE
Google Summer of Code participation (TSC)

### ISSUE THREAD

**Issue by armstro** [zowe/community#952]
@armstro commented on [Thu Oct 01 2020](https://github.com/zowe/zlc/issues/216)

How (if) to have Zowe participation in the event  https://summerofcode.withgoogle.com/archive/  Follow up from Oct 1 PI Planning for 2020 

---

@balhar-jakub commented on [Wed Oct 14 2020](https://github.com/zowe/zlc/issues/216#issuecomment-708389022)

It seems that the Linux Foundation is usually part of the Google Summer of Code as organization.
So I guess we just need to get in touch with the people who propose Linux Foundation to the GSOC. 
And if there is no objections from their side then we just need to prepare the potential projects that the students could apply to. 

I have been working on this preparation within OS4Geo on one of their projects, so I guess I can help there a bit. 

---

@armstro commented on [Wed Oct 14 2020](https://github.com/zowe/zlc/issues/216#issuecomment-708422394)

@jmertic Please advise - see comments above - is this something that the Zowe team could get involved in? 

---

@jmertic commented on [Wed Oct 14 2020](https://github.com/zowe/zlc/issues/216#issuecomment-708466390)

Sure thing - there are some thoughts of coordinating mentorships for this program in addition to our normal summer mentorship program. The main thing that is needed is projects to work on ;-)

@bobdahlberg adding you here as well. Thinking this could be something to chat about at the TAC as well.

---

@balhar-jakub commented on [Tue Jan 19 2021](https://github.com/zowe/zlc/issues/216#issuecomment-762703221)

@armstro Could you please move that to the Community repo with TSC label?

@jmertic You mentioned that some other project within the Linux Foundation is discussing the involvement. 

For everyone there are multiple ways how to participate. 
- Either Linux Foundation will participate as umbrella organization - In this case at this moment someone from the Linux Foundation needs to prepare the application for the GSoC as the organization. Based on what I found this seemed to be the case in previous years. This would require us to get in contact with the LF responsible person and discuss what and how many mentors and projects we would like to see within the GSoC for Zowe. 
- Open Mainframe Project decides to apply in case the LF isn't going to apply as organization. Then the decisions and work will be on the OMP and I guess either Bob, or me if he isn't interested in the preparation. 
- OMP isn't going to be interested in participating, then we still can apply as Zowe ourselves, it just would mean that we would need to prepare the application. The application in itself isn't difficult and I am willing to prepare it if nobody above is going to be interested and of course if we have any projects the squads will be interested in sharing with students under the GSoC program. 

Below I am sharing the email with the information about how to apply as an organization and what the project for GSoC means. 

Just a quick reminder that if your org would like to apply for the 2021 GSoC program please start thinking about the ~175 hr projects you would like students to work on and also reach out to your community members to ask if they would like to be mentors for the program. Having a thorough and well thought out list of Project Ideas is the most important part of your application.

We realize many of you have project ideas from a previous GSoC Ideas List based on a 350 hour size project, please look at ways to either break the project into smaller chunks or consider completely new project ideas that will be ~175 hours for students to work on over the summer.

You can check out the 2021 GSoC Org Application Questions if you’d like to start preparing your responses in advance so you can copy over your answers once the org applications open Jan 29 - Feb 19 at g.co/gsoc - there are a few new questions this year.

Please encourage other open source orgs to apply -- if you know of other open source projects that may be interested in applying to GSoC as a first time org please remind them to check out the available resources below and have them put your org (or you) down as a reference.

Open source projects can apply to be mentoring organizations from January 29th - February 19th at 1900 UTC.

@1000TurquoisePogs I believe that within the GSoC we can look and find projects within Zowe that has limited or zero dependency on the zOS for development. Would some projects created by students interesting in this way? I know that within the OMP mentorships the focus is understandably more on the zOS side, but here it could be more in bringing the students into the Open Source community. 

---

@jmertic commented on [Tue Jan 19 2021](https://github.com/zowe/zlc/issues/216#issuecomment-762818719)

@balhar-jakub Generally we've seen each LF project/umbrella apply separately vs having one blanket organization for all 450+ hosted projects. I think Jakub having you apply for Open Mainframe Project as an org makes the most sense.

---

@Joe-Winchester commented on [Tue Jan 19 2021](https://github.com/zowe/zlc/issues/216#issuecomment-762925636)

Proposal:  **Graphical awareness of UIs in the API Gateway**
Problem:   Logging onto the API Gateway takes the user to the API Catalog which shows a set of tiles for registered API services.  The API Mediation layer can also have UIs registered.  Base Zowe has four UIs registered (ZLUX, MVS Explorer, USS Explorer, JES Explorer) and Zowe conformant plugins can (and do) introduce their own.  The URLs to launch these is <gateway>/ui/v1/pluginId.  Unless a user knows of their existence they may not use these.
Solution:  Provide a way for registered UIs to be visible on the API Gateway.  On the API Gateway homepage there could be a link to the UI services (similar to the link for the catalog) and the list of services could allow linking into each of the registered UIs.  

---

@balhar-jakub commented on [Tue Jan 19 2021](https://github.com/zowe/zlc/issues/216#issuecomment-762925923)

@jmertic Ok I will continue with the execution with this in mind and looking into applying as the Open Mainframe Project. 

@bobdahlberg Could we have maybe a short discussion to make sure that we don't canibalize in any way on the Open Mainframe Project mentorships?

It seems that there are some ideas available within the Zowe, that may be interesting for the mentees and for which we could find mentors. 

#### The ideas mentioned within the Architecture call:

From Sean Grady
- Patch to the Linux PAX project to understand the headers properly. Allowing us to decide properly whether file is encoded as EBCDIC or ASCII
- Reading more complex information from the extensions and plugins and presenting them in the API Catalog
- Improving the startup of the app server to wait for the startup of the API Mediation Layer before fully starting

From Jakub Balhar
- Metrics related improvements within the API Mediation Layer

#### Potential mentors:
- @balhar-jakub 
- Lenny

**Comment by Joe-Winchester** [comment]
Possible other ideas:
 
- Slack integration to Zowe.  Allow a user to create a slack channel to their mainframe and ask questions, e.g. "Is my job finished" or "Is task ABCD still running", ...    Slack communicates using Zowe CLI commands and a text to command language parser creates the calls, e.g. Watson AI assistant
- GitHub integration to Zowe.  When a PR is being reviewed have an integrated powerup that allows the ability to build and deploy a Zowe system, and to log onto it, so the user can do some testing and verification of the environment and manual testing, without having to manually download, install and do manual test.   When the PR is merged the environment is torn down.

**Comment by balhar-jakub** [comment]
The application was created. We will know the results on the March 9th. If you want to add any more projects. The list is here: https://github.com/openmainframeproject-internship/resources/blob/master/gsoc/2021-Projects.MD
