### ISSUE TITLE
Use of Telemetry in Zowe Explorer (and collecting info in general)

### ISSUE THREAD

**Issue by armstro** [zowe/community#953]
@zdmullen commented on [Wed Dec 09 2020](https://github.com/zowe/zlc/issues/221)

This stems from the discussion that I brought up in the December 9 meeting. 

The question is about introducing telemetry in Zowe Explorer. As a Visual Studio Code extension, we can follow the guidance that VS Code provides for implementing telemetry in extensions to do so in Zowe Explorer. This of course raises several questions for the dev team and others to resolve:

- What is the scope for the information we want to collect? UI or specific data, a mix of both? 
- How do we set up an Azure account where the data can be collected *and* accessed by squad members?
- What is the best way to bring this to the attention of users and what is the default behavior?

From this initial question, we also talked about collection of user data in z/OS and also the API ML (both of which were discussed at some point in the past). 

Shall we have a more formal discussion of this in a future ZLC meeting? Who should the team follow up with otherwise? 

Thanks!

---

@balhar-jakub commented on [Thu Jan 07 2021](https://github.com/zowe/zlc/issues/221#issuecomment-756019230)

We have been having similar questions within the API Mediation Layer squad for a new functionality that we would like to introduce and it turned out that after we figure out internally what we actually want there is a formal process for confirmation that we can do that on the level of Linux Foundation. 

This is the relevant document: https://lfprojects.org/policies/telemetry-data-policy/

---

@armstro commented on [Thu Jan 07 2021](https://github.com/zowe/zlc/issues/221#issuecomment-756107464)

Thanks for additional info - another aspect of the data collection that I recall someone mentioning is the possibility of being charged money for collection of the data? Do you know anything about this? I assume charges for collection, protection, storage/archieve, display of the data? This would be something else we would need to understand before proceeding. I assume OMP would be reluctant to pay for variable costs unless there is a compelling ROI on the data. I think it is still worth discussion - I am not saying we give up on the idea but needs more thought (something that would be good for both TSC and ZLC to work on with OMP).

**Comment by balhar-jakub** [comment]
Closing the issue as the process is quite complex for open source under Linux Foundation.
