### ISSUE TITLE
PR Approvers for sub-projects (TSC)

### ISSUE THREAD

**Issue by solsu01** [zowe/community#955]
Question came up on the Zowe Explorer squad kick off about the process in adding PR approvers for a Zowe Sub-Project. The current process is not well defined and is left up to the individual squad to expand the PR approvers for the sub-projects they manage.

Do we want Zowe to have formal guidance around how PR approvers are selected/elected or continue with the informal process?

**Comment by balhar-jakub** [comment]
There is an open issue already for this topic https://github.com/zowe/community/issues/922 

I propose closing this one and continuing the discussion in the linked one.
