### ISSUE TITLE
Explore use of Portable Software Instance (PSI) - (TSC) 

### ISSUE THREAD

**Issue by armstro** [zowe/community#956]
Proposal to support Zowe install by Portable Software Instance(PSI) - research needed - software prereqs, use of build environment, automation, etc.....

Text from zlc email - Few  comments - 
- I have meeting today with Marna Walle to get some education on PSI - she a I spoke last year and - at the time - PSI was a z/OS 2.4 item and we (Zowe team) stayed with SMP/E. I have seen comments implying the capability has been rolled back to prior z/OS level 
- We need to be sensitive to the fact the build environment (Marist) is at z/OS 2.3 and therefore may need PTFs added to support PSI - they control the changes and help Zowe on a best effort basis - they are great to work with but changes need to be requested and coordinated 
- We need to understand how PSI can be automated in the CI/CD pipeline - I hear mention of REST APIs - I assume for driving the process programmatically 
- CI/CD pipeline team already spread thin - great to get help if possible - PSI work needs to be prioritized - I think the highest priority is to get to Linux Foundation Jenkins when technical issues sorted out  BUT I do not know what else is in the backlog - I recall some Ansible work too.

**Comment by balhar-jakub** [comment]
It's happening as part of the Systems squad work.

**Comment by balhar-jakub** [comment]
I am closing the issue as there is now an Objective within the Systems squad to provide PSI for the Zowe
