### ISSUE TITLE
Investigate OpenSSF / CII (TSC) 

### ISSUE THREAD

**Issue by MarkAckert** [zowe/community#957]
[OpenSSF](https://openssf.org/#faq) is a new initiative to define standards and practices for developing and securing open source software. Zowe already has a CII badge which captures adherence to a similar set of best practices, but OpenSSF looks like the evolution of CII moving forward. Zowe needs to investigate OpenSSF's timeline for developing best practices guidelines, decide if we should use OpenSSF, and plan accordingly.  Select quotes from OpenSSF below.

"The OpenSSF is a cross-industry collaboration that brings together leaders to improve the security of open source software (OSS) by building a broader community, targeted initiatives, and best practices."

"The CII was funded largely by grants, OpenSSF will be supported by Linux Foundation membership dues with targeted organization contributions to support initiatives. The CII plans to contribute resources and experience to the OpenSSF and plans to work through their project approval process shepherded by the OpenSSF TAC for desired projects. In the long term, the CII will dissolve efforts with work happening under the OpenSSF umbrella."

**Comment by MarkAckert** [comment]
It still looks premature to adopt OpenSSF standards right now. Circle back to this Fall '21?

**Comment by balhar-jakub** [comment]
I am closing the issue, we now follow the OpenSSF and use the knowledge based on their current findings they are also now responsible for the CII where we aim to get the golden badge which is a separate issue.
