### ISSUE TITLE
Should PSIs be standardized by Zowe or can vendors create their own PSIs for redistributing Zowe? (TSC) 

### ISSUE THREAD

**Issue by solsu01** [zowe/community#960]
Should Zowe standardize PSI distribution of Zowe?

Or do should vendors be allowed to determine what should be included in their PSIs?

Should there be "conformance" for vendor distributions of Zowe to enforce preferences like this?

**Comment by balhar-jakub** [comment]
The answer is of know Zowe provides PSI and the vendors should use the default Zowe PSI and not modify it so that all the support vendors can properly support Zowe installed by any of the vendors.
